/* Doctor module worklists — UX prototype mock interactions only.
   This layer never changes the approved consultation screen or its data-entry flow. */
(function(){
  const baseShowPage = window.showPage;
  const state = {
    queueFilter:'all', search:'', patientFilter:'all', patientSearch:'',
    results:[
      {id:'R-01',uhid:'HSP24-00123',test:'HbA1c',value:'8.2%',flag:'High',received:'Today, 08:42',status:'new'},
      {id:'R-02',uhid:'HSP24-00125',test:'Chest X-ray',value:'Mild hyperinflation',flag:'Review',received:'Today, 09:05',status:'new'},
      {id:'R-03',uhid:'HSP24-00124',test:'TSH',value:'3.1 mIU/L',flag:'Normal',received:'Yesterday',status:'new'}
    ],
    followups:[
      {id:'F-01',uhid:'HSP24-00123',reason:'Review HbA1c and diabetic control',due:'Today',priority:'Due today',status:'open',appointment:{status:'Not booked'}},
      {id:'F-02',uhid:'HSP24-00125',reason:'COPD inhaler technique review',due:'06 Sep 2026',priority:'Upcoming',status:'open',appointment:{status:'Booked',date:'06 Sep 2026',time:'10:30 AM',mode:'In clinic',bookedBy:'Reception'}},
      {id:'F-03',uhid:'HSP24-00126',reason:'First-visit clinical review',due:'10 Sep 2026',priority:'Upcoming',status:'open',appointment:{status:'Not booked'}}
    ],
    referrals:[
      {id:'RF-01',uhid:'HSP24-00125',to:'Pulmonology',reason:'COPD review',status:'Awaiting response'},
      {id:'RF-02',uhid:'HSP24-00123',to:'Diabetology',reason:'HbA1c review',status:'Awaiting response'}
    ],
    availability:{Mon:true,Tue:true,Wed:true,Thu:true,Fri:true,Sat:true,Sun:false},
    bookingPreferences:{duration:'15',advance:'30',clinic:true,video:true,audio:true}
  };
  const moduleNames = ['doctorQueue','doctorPatients','doctorProfile','doctorInbox','doctorFollowups','doctorAvailability','doctorPrescriptions'];
  const todayQueue = () => typeof queue !== 'undefined' ? queue : [];
  const known = () => typeof getKnownPatients==='function' ? getKnownPatients() : todayQueue();
  const patient = uhid => known().find(p=>p.uhid===uhid) || todayQueue().find(p=>p.uhid===uhid);
  const esc = s => String(s || '').replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const byUhid = u => { const p=patient(u)||{}; return p; };
  const visitRows = () => todayQueue().map(p=>Object.assign({status:p.action==='upcoming'?'Scheduled':'Ready'},p));
  const visitReason = uhid => ({'HSP24-00123':'Chest tightness on exertion','HSP24-00124':'Thyroid follow-up','HSP24-00125':'Breathlessness review','HSP24-00126':'First clinical review','HSP24-00127':'Quarterly follow-up'}[uhid] || 'Clinical consultation');
  const clinical = uhid => (typeof MOCK_PATIENTS!=='undefined' && MOCK_PATIENTS[uhid]) || {};
  const hasVitals = record => !!(record && record.vitals && record.vitals.bp);
  const allergyState = record => {
    if((record.allergies||[]).length) return {label:'Drug allergy recorded',kind:'alert'};
    if(record.allergiesConfirmed) return {label:'No known drug allergies',kind:'ready'};
    return {label:'Allergy status not recorded',kind:'waiting'};
  };
  const readiness = (visit,record) => visit.action==='upcoming' ? {label:'Scheduled',kind:'waiting'} : hasVitals(record) ? {label:'Vitals ready',kind:'ready'} : {label:'Vitals pending',kind:'alert'};
  const nextVisit = uhid => todayQueue().find(v=>v.uhid===uhid) || null;
  const patientFlags = (p,record) => {
    const flags=[];
    (record.conditions||[]).slice(0,2).forEach(c=>flags.push(c.name));
    if(state.followups.some(f=>f.uhid===p.uhid&&f.status==='open'&&f.priority==='Due today')) flags.push('Follow-up due');
    return flags;
  };

  function activate(page){
    ['navDashboard','navReception','navPatients','navPrescriptions','navReports','navSettings','navAvailability'].forEach(id=>{const el=document.getElementById(id);if(el)el.classList.remove('active');});
    const map={dashboard:'navDashboard',doctorQueue:'navReception',doctorPatients:'navPatients',doctorProfile:'navPatients',doctorInbox:'navReports',doctorFollowups:'navSettings',doctorAvailability:'navAvailability',doctorPrescriptions:'navPrescriptions'};
    const el=document.getElementById(map[page]); if(el)el.classList.add('active');
  }
  function hideBase(){
    ['dashboard','consultation','queue','reception','adminOverview','patients','prescriptions','reports','settings'].forEach(n=>{const el=document.getElementById('page-'+n);if(el)el.style.display='none';});
    const module=document.getElementById('page-doctorModule'); if(module)module.style.display='';
  }
  function doctorDashboard(){
    ['consultation','queue','reception','adminOverview','patients','prescriptions','reports','settings'].forEach(n=>{const el=document.getElementById('page-'+n);if(el)el.style.display='none';});
    const module=document.getElementById('page-doctorModule');if(module)module.style.display='none';
    const root=document.getElementById('page-dashboard'); root.style.display='block'; root.className='content-wrap doctor-dashboard';
    const rows=visitRows(); const openResults=state.results.filter(r=>r.status==='new'); const recentRx=typeof prescriptionsList!=='undefined'?prescriptionsList.slice(0,3):[]; const readyVisits=rows.filter(p=>readiness(p,clinical(p.uhid)).kind==='ready').length; const pendingVitals=rows.filter(p=>readiness(p,clinical(p.uhid)).label==='Vitals pending').length; const dueFollowups=state.followups.filter(f=>f.status==='open'&&f.priority==='Due today').length; const abnormalResults=openResults.filter(r=>r.flag!=='Normal').length;
    root.innerHTML=`<div class="dd-head"><div><h1>Dashboard</h1><div class="dd-sub">Friday, 04 September 2026 · Your clinical workday at a glance</div></div><div class="dd-spacer"></div><button class="dw-btn primary" onclick="doctorModule.schedule()">Schedule appointment</button></div>
      <div class="dd-stat-grid dd-stat-grid-priority"><div class="dd-stat"><div class="dd-stat-num">${rows.length}</div><div class="dd-stat-label">Today's appointments</div></div><div class="dd-stat ready"><div class="dd-stat-num">${readyVisits}</div><div class="dd-stat-label">Ready to consult</div></div><div class="dd-stat waiting"><div class="dd-stat-num">${pendingVitals}</div><div class="dd-stat-label">Vitals pending</div></div><div class="dd-stat alert"><div class="dd-stat-num">${openResults.length}</div><div class="dd-stat-label">Results need review</div></div><div class="dd-stat alert"><div class="dd-stat-num">${dueFollowups}</div><div class="dd-stat-label">Follow-ups due today</div></div></div>
      <div class="dd-main-grid"><div class="dd-card"><div class="dd-card-head"><h2>Upcoming appointments</h2><button class="dw-link" onclick="showPage('doctorQueue')">Open today’s queue</button></div><table class="dd-queue"><thead><tr><th>Time</th><th>Patient</th><th>Clinical context</th><th>Vitals</th><th>Readiness</th><th>Action</th></tr></thead><tbody>${rows.map(p=>{const c=clinical(p.uhid),allergy=allergyState(c),visitReadiness=readiness(p,c),visitLabel=p.freq==='First Visit'?'First visit':p.type==='clinic'?'In clinic':p.type==='video'?'Video':p.type==='audio'?'Audio':'Visit';return `<tr><td class="dd-time">${esc(p.time)}</td><td><div class="dd-person">${esc(p.name)}</div><div class="dd-mini">${esc(p.uhid)} · ${p.age}Y · ${esc(p.gender||'')}</div></td><td><div>${esc(visitReason(p.uhid))}</div><div class="dd-mini"><span class="dd-visit">${visitLabel}</span>${allergy.kind==='alert'?' · <span class="dd-safety">Drug allergy</span>':''}</div></td><td><div>${hasVitals(c)?'BP '+esc(c.vitals.bp):'Not recorded'}</div><div class="dd-mini">${hasVitals(c)?'P '+esc(c.vitals.pulse)+' · SpO₂ '+esc(c.vitals.spo2)+'%':'Record vitals before consultation'}</div></td><td><span class="dw-chip ${visitReadiness.kind}">${visitReadiness.label}</span></td><td>${p.action==='upcoming'?'<button class="dw-link" onclick="doctorModule.record(\''+p.uhid+'\')">View record</button>':`<button class="dw-btn primary" onclick="doctorModule.start('${p.uhid}','${p.type}')">${p.type==='video'?'Join Video':p.type==='audio'?'Join Audio':'Start Consultation'}</button>`}</td></tr>`;}).join('')}</tbody></table></div>
      <aside class="dd-card"><div class="dd-card-head"><h2>Clinical priorities</h2><button class="dw-link" onclick="showPage('doctorInbox')">Open inbox</button></div><div class="dd-side-row"><div class="dd-side-title">${openResults.length} results need review</div><div class="dd-side-copy">${abnormalResults} abnormal · ${openResults.length-abnormalResults} routine result${openResults.length===1?'':'s'} awaiting a clinical decision.</div></div><div class="dd-side-row"><div class="dd-side-title">${dueFollowups} follow-up due today</div><div class="dd-side-copy">Review HbA1c and diabetic control for Rahul Sharma.</div><button class="dw-link" onclick="showPage('doctorFollowups')">View follow-ups</button></div><div class="dd-side-row"><div class="dd-side-title">${state.referrals.length} referrals awaiting response</div><div class="dd-side-copy">Keep referrals visible until accepted or actioned.</div><button class="dw-link" onclick="showPage('doctorInbox')">View referrals</button></div></aside></div>
      <div class="dd-bottom-grid"><section class="dd-card"><div class="dd-card-head"><h2>Pending lab results</h2><button class="dw-link" onclick="showPage('doctorInbox')">Review all</button></div>${openResults.map(r=>{const p=byUhid(r.uhid);return `<div class="dd-item"><div class="dd-item-copy"><div class="dd-item-title">${esc(r.test)} · ${esc(p.name)}</div><div class="dd-item-sub">${esc(r.value)} · received ${esc(r.received)}</div></div><span class="dd-state ${r.flag==='Normal'?'':'urgent'}">${esc(r.flag)}</span></div>`}).join('')||'<div class="dw-empty">No pending results.</div>'}</section><section class="dd-card"><div class="dd-card-head"><h2>Recent prescriptions</h2><button class="dw-link" onclick="showPage('prescriptions')">View all</button></div>${recentRx.length?recentRx.map(r=>`<div class="dd-item"><div class="dd-item-copy"><div class="dd-item-title">${esc(r.patientName)}</div><div class="dd-item-sub">${esc(r.date||'Today')} · ${esc(r.status||'Signed')}</div></div><span class="dd-state signed">Signed</span></div>`).join(''):'<div class="dw-empty">No recent prescriptions.</div>'}</section></div>`;
    activate('dashboard'); window.scrollTo(0,0);
  }
  window.showPage = function(name){
    if(!moduleNames.includes(name)){
      if(name==='queue') name='doctorQueue';
      else if(name==='patients') name='doctorPatients';
      else if(name==='prescriptions') name='doctorPrescriptions';
      else if(name==='reports') name='doctorInbox';
      else if(name==='settings') name='doctorAvailability';
      else if(name==='reception') name='doctorQueue';
    }
    if(name==='dashboard'){doctorDashboard();return;}
    if(moduleNames.includes(name)){ hideBase(); activate(name); render(name); window.scrollTo(0,0); return; }
    const module=document.getElementById('page-doctorModule');if(module)module.style.display='none';
    baseShowPage(name); activate(name);
  };

  function layout(title,sub,actions,body){
    document.getElementById('doctorModuleContent').innerHTML=`<div class="dw-header"><div><div class="dw-title">${title}</div><div class="dw-sub">${sub}</div></div><div class="dw-spacer"></div><div class="dw-actions">${actions||''}</div></div>${body}`;
  }
  function queuePage(){
    const rows=visitRows().filter(p=>{
      const query=state.search.toLowerCase(); const match=!query||p.name.toLowerCase().includes(query)||p.uhid.toLowerCase().includes(query);
      return match && (state.queueFilter==='all'||p.type===state.queueFilter);
    });
    layout("Today's Queue",'Choose a visit to review the record or begin the approved consultation.','<button class="dw-btn" onclick="doctorModule.schedule()">Schedule appointment</button>',`
      <div class="dw-toolbar"><input class="dw-search" value="${esc(state.search)}" oninput="doctorModule.search(this.value)" placeholder="Search name or UHID"><button class="dw-filter ${state.queueFilter==='all'?'active':''}" onclick="doctorModule.filter('all')">All</button><button class="dw-filter ${state.queueFilter==='clinic'?'active':''}" onclick="doctorModule.filter('clinic')">In clinic</button><button class="dw-filter ${state.queueFilter==='video'?'active':''}" onclick="doctorModule.filter('video')">Video</button><button class="dw-filter ${state.queueFilter==='audio'?'active':''}" onclick="doctorModule.filter('audio')">Audio</button></div>
      <div class="dw-table-wrap"><table class="dw-table"><thead><tr><th>Time</th><th>Patient</th><th>Reason / alert</th><th>Visit</th><th>Latest vitals</th><th>Readiness</th><th>Action</th></tr></thead><tbody>${rows.map(p=>{const c=clinical(p.uhid),hasAlert=(c.allergies||[]).length>0,visitReadiness=readiness(p,c);return `<tr onclick="doctorModule.record('${p.uhid}')"><td><b>${esc(p.time)}</b></td><td><div class="dw-person">${esc(p.name)}</div><div class="dw-muted">${esc(p.uhid)} · ${p.age}Y · ${esc(p.gender)}</div></td><td><div>${esc(visitReason(p.uhid))}</div>${hasAlert?'<div class="dw-muted" style="color:#b91c1c">Drug allergy recorded</div>':'<div class="dw-muted">No alert recorded</div>'}</td><td><span class="dw-chip">${p.type==='clinic'?'In clinic':esc(p.type)}</span><div class="dw-muted">${esc(p.freq||'')}</div></td><td><div>${hasVitals(c)?'BP '+esc(c.vitals.bp)+' · P '+esc(c.vitals.pulse):'Not recorded'}</div><div class="dw-muted">${hasVitals(c)?'SpO₂ '+esc(c.vitals.spo2)+'%':'Record vitals before consultation'}</div></td><td><span class="dw-chip ${visitReadiness.kind}">${visitReadiness.label}</span></td><td>${p.action==='upcoming'?`<button class="dw-link" onclick="event.stopPropagation();doctorModule.record('${p.uhid}')">View record</button>`:`<button class="dw-btn primary" onclick="event.stopPropagation();doctorModule.start('${p.uhid}','${p.type}')">${p.type==='video'?'Join Video':p.type==='audio'?'Join Audio':'Start Consultation'}</button>`}</td></tr>`;}).join('')||'<tr><td colspan="7" class="dw-empty">No visits match this filter.</td></tr>'}</tbody></table></div>`);
  }
  function patientsPage(){
    layout('My Patients','Find a patient record and review only the clinical context needed to select it safely.','<button class="dw-btn" onclick="doctorModule.schedule()">Schedule appointment</button>',`<div class="dw-toolbar dw-directory-toolbar"><input class="dw-search" value="${esc(state.patientSearch)}" oninput="doctorModule.patientSearch(this.value)" placeholder="Search name, UHID, or phone" aria-label="Search patients"><button class="dw-filter ${state.patientFilter==='all'?'active':''}" onclick="doctorModule.patientFilter('all')">All patients</button><button class="dw-filter ${state.patientFilter==='recent'?'active':''}" onclick="doctorModule.patientFilter('recent')">Recent</button><button class="dw-filter ${state.patientFilter==='upcoming'?'active':''}" onclick="doctorModule.patientFilter('upcoming')">Upcoming visit</button><button class="dw-filter ${state.patientFilter==='safety'?'active':''}" onclick="doctorModule.patientFilter('safety')">Safety alert</button><button class="dw-filter ${state.patientFilter==='followup'?'active':''}" onclick="doctorModule.patientFilter('followup')">Follow-up due</button></div><div class="dw-directory-meta" id="doctorPatientCount"></div><div id="doctorPatientList" class="dw-table-wrap"></div>`);
    renderPatientList();
  }
  function filteredPatients(){
    const query=state.patientSearch.toLowerCase();
    return known().filter(p=>{
      const c=clinical(p.uhid), allergy=allergyState(c), visit=nextVisit(p.uhid), due=state.followups.some(f=>f.uhid===p.uhid&&f.status==='open'&&f.priority==='Due today');
      const match=!query||[p.name,p.uhid,p.phone].some(x=>String(x||'').toLowerCase().includes(query));
      const byFilter=state.patientFilter==='all'||(state.patientFilter==='recent'&&(c.records||[]).length>0)||(state.patientFilter==='upcoming'&&!!visit)||(state.patientFilter==='safety'&&allergy.kind==='alert')||(state.patientFilter==='followup'&&due);
      return match&&byFilter;
    });
  }
  function renderPatientList(){
    const records=filteredPatients();
    const target=document.getElementById('doctorPatientList'); if(!target)return;
    const count=document.getElementById('doctorPatientCount'); if(count)count.textContent=`Showing ${records.length} of ${known().length} patients`;
    target.innerHTML=records.length?`<table class="dw-table dw-patient-table"><thead><tr><th>Patient</th><th>Clinical flags</th><th>Last clinical activity</th><th>Next visit</th><th>Safety status</th><th>Action</th></tr></thead><tbody>${records.map(p=>{const c=clinical(p.uhid),allergy=allergyState(c),visit=nextVisit(p.uhid),flags=patientFlags(p,c),last=(c.records||[])[0];return `<tr><td><div class="dw-person">${esc(p.name)}</div><div class="dw-muted">${esc(p.uhid)} · ${p.age||'—'}Y · ${esc(p.gender||'')}</div></td><td>${flags.length?flags.map(flag=>`<span class="dw-chip ${flag==='Follow-up due'?'alert':''}">${esc(flag)}</span>`).join(' '):'<span class="dw-muted">No active flags</span>'}</td><td>${last?`<div>${esc(last.name)}</div><div class="dw-muted">${esc(last.date)}</div>`:'<span class="dw-muted">No clinical activity recorded</span>'}</td><td>${visit?`<div>${esc(visit.time)} · ${visit.type==='clinic'?'In clinic':esc(visit.type)}</div><div class="dw-muted">${esc(visit.freq||'Today')}</div>`:'<span class="dw-muted">No visit scheduled</span>'}</td><td><span class="dw-chip ${allergy.kind}">${esc(allergy.label)}</span></td><td><button class="dw-link" onclick="doctorModule.record('${p.uhid}')">Open record</button></td></tr>`;}).join('')}</tbody></table>`:'<div class="dw-empty">No patient records match the selected filters.</div>';
  }
  function patientProfilePage(){
    const p=state.profileUhid ? byUhid(state.profileUhid) : null;
    if(!p){showPage('doctorPatients');return;}
    const c=clinical(p.uhid), active=todayQueue().find(v=>v.uhid===p.uhid && v.action!=='upcoming');
    const allergies=(c.allergies||[]), meds=(c.currentMeds||[]), conditions=(c.conditions||[]), vitals=c.vitals||{};
    layout('Patient record','Read the patient’s longitudinal context before starting a new visit.',`<button class="dw-btn" onclick="showPage('doctorPatients')">Back to My Patients</button>${active?`<button class="dw-btn primary" onclick="doctorModule.start('${p.uhid}','${active.type}')">${active.type==='video'?'Join Video':active.type==='audio'?'Join Audio':'Start Consultation'}</button>`:''}`,`
      <div class="dp-summary"><div class="dp-hero"><div class="dp-name">${esc(p.name)}</div><div class="dp-meta">${esc(p.uhid)} · ${p.age||'—'}Y · ${esc(p.gender||'')} · ${esc(p.phone||'')}</div><div class="dp-meta">ABHA: ${esc(c.abhaId||'Not linked')} · Blood group: ${esc(c.bloodGroup||'Not recorded')}</div></div><div class="dp-hero"><div class="dp-label">Allergy status</div>${allergies.length?allergies.map(a=>`<div class="dp-pill alert">${esc(a.substance)} · ${esc(a.severity)}</div>`).join(''):`<div class="dp-value">${c.allergiesConfirmed?'No known drug allergies confirmed':'Not recorded'}</div>`}</div><div class="dp-hero"><div class="dp-label">Latest vitals</div><div class="dp-value">BP ${esc(vitals.bp||'—')} · Pulse ${esc(vitals.pulse||'—')}</div><div class="dp-meta">SpO₂ ${esc(vitals.spo2||'—')}% · ${esc(vitals.measuredAt||'Not recorded')}</div></div></div>
      <div class="dp-grid"><section class="dp-card"><h2>Active conditions</h2><div class="dp-list">${conditions.length?conditions.map(x=>`<span class="dp-pill">${esc(x.name)} · ${esc(x.since)}</span>`).join(''):'<div class="dw-muted">No conditions recorded.</div>'}</div></section><section class="dp-card"><h2>Current medications</h2><div class="dp-list">${meds.length?meds.map(x=>`<div><div class="dp-value">${esc(x.drug)} ${esc(x.strength)}</div><div class="dw-muted">${esc(x.frequency)} · since ${esc(x.since)}</div></div>`).join(''):'<div class="dw-muted">No current medication recorded.</div>'}</div></section><section class="dp-card"><h2>Recent clinical activity</h2><div class="dp-list"><div><div class="dp-value">Today’s reason</div><div class="dw-muted">${esc(visitReason(p.uhid))}</div></div><div><div class="dp-value">Follow-up status</div><div class="dw-muted">${state.followups.filter(f=>f.uhid===p.uhid&&f.status==='open').length} open follow-up task(s)</div></div></div></section><section class="dp-card"><h2>Records</h2><div class="dp-list">${(c.records||[]).slice(0,4).map(r=>`<div><div class="dp-value">${esc(r.name)}</div><div class="dw-muted">${esc(r.date)}</div></div>`).join('')||'<div class="dw-muted">No records available.</div>'}</div></section></div>`);
  }
  function prescriptionsPage(){
    const items=typeof prescriptionsList!=='undefined'?prescriptionsList.slice().reverse():[];
    layout('Prescriptions','Track prescriptions after they are signed in the approved consultation workflow.','<button class="dw-btn" onclick="showPage(\'doctorQueue\')">Open today’s queue</button>',`<div class="dw-note">New prescriptions are created within a consultation, so the medicine, diagnosis, and patient context remain together.</div><div class="dw-panel"><div class="dw-list">${items.map(r=>`<div class="dw-list-row" style="padding:14px 17px"><div class="grow"><div class="dw-person">${esc(r.patientName)}</div><div class="dw-muted">${esc(r.medications)} · ${esc(r.date)}</div></div><span class="dw-chip reviewed">Signed</span><button class="dw-link" onclick="doctorModule.recordByName('${esc(r.patientName)}')">Patient record</button></div>`).join('')||'<div class="dw-empty">No signed prescriptions yet.</div>'}</div></div>`);
  }
  function inboxPage(){
    const open=state.results.filter(r=>r.status==='new');
    layout('Clinical Inbox','Review incoming results, document the decision, and create the next clinical action.','<button class="dw-btn primary" onclick="doctorModule.newReferral()">Create referral</button>',`<div class="dw-grid"><div class="dw-card"><h3>Needs review</h3><div class="dw-number">${open.length}</div><p>New results awaiting a clinical decision</p></div><div class="dw-card"><h3>Abnormal / urgent</h3><div class="dw-number">${open.filter(r=>r.flag==='High'||r.flag==='Review').length}</div><p>Review before the end of the session</p></div><div class="dw-card"><h3>Referrals</h3><div class="dw-number">${state.referrals.length}</div><p>Open referrals awaiting specialist response</p></div></div><div class="dw-section"><div class="dw-section-head"><h2>Incoming results</h2></div><div class="dw-panel"><div class="dw-list">${state.results.map(r=>{const p=byUhid(r.uhid);return `<div class="dw-list-row" style="padding:13px 17px"><div class="grow"><div class="dw-person">${esc(r.test)} <span class="dw-chip ${r.flag==='Normal'?'reviewed':'alert'}">${esc(r.flag)}</span></div><div class="dw-muted">${esc(p.name)} · ${esc(r.value)} · received ${esc(r.received)}</div></div>${r.status==='new'?`<button class="dw-btn primary" onclick="doctorModule.reviewResult('${r.id}')">Review result</button>`:'<span class="dw-chip reviewed">Reviewed</span>'}<button class="dw-link" onclick="doctorModule.record('${r.uhid}')">Patient record</button></div>`}).join('')}</div></div></div><div class="dw-section"><div class="dw-section-head"><h2>Open referrals</h2></div><div class="dw-panel"><div class="dw-list">${state.referrals.map(r=>{const p=byUhid(r.uhid);return `<div class="dw-list-row" style="padding:13px 17px"><div class="grow"><div class="dw-person">${esc(p.name)} → ${esc(r.to)}</div><div class="dw-muted">${esc(r.reason)} · ${esc(r.status)}</div></div><button class="dw-link" onclick="doctorModule.record('${r.uhid}')">Patient record</button></div>`}).join('')}</div></div></div>`);
  }
  function followupsPage(){
    const open=state.followups.filter(f=>f.status==='open'), booked=open.filter(f=>f.appointment?.status==='Booked').length, unbooked=open.length-booked;
    layout('Follow-ups','Clinical follow-up requirements created during consultation. Appointment booking can be completed by the doctor, reception, nurse, or patient.','',`<div class="dw-followup-summary"><div><b>${open.length} open clinical follow-up${open.length===1?'':'s'}</b><span>${unbooked} need${unbooked===1?'s':''} an appointment · ${booked} booked</span></div><div class="dw-muted">Create or change the clinical requirement from the Consultation; manage appointment status here.</div></div><div class="dw-panel"><div class="dw-followup-head"><span>Patient & clinical purpose</span><span>Appointment status</span><span>Clinical status</span><span>Actions</span></div><div class="dw-list dw-followup-list">${state.followups.map(f=>{const p=byUhid(f.uhid),a=f.appointment||{status:'Not booked'},booked=a.status==='Booked';return `<div class="dw-followup-row"><div><div class="dw-person">${esc(p.name)}</div><div class="dw-muted">${esc(f.reason)} · due ${esc(f.due)}</div></div><div>${booked?`<div class="dw-person">${esc(a.date)} · ${esc(a.time)}</div><div class="dw-muted">${esc(a.mode)} · booked by ${esc(a.bookedBy)}</div>`:'<div class="dw-person">Not booked</div><div class="dw-muted">Scheduling can be completed by reception, nurse, patient, or doctor.</div>'}</div><div><span class="dw-chip ${f.status==='closed'?'reviewed':f.priority==='Due today'?'alert':'waiting'}">${f.status==='closed'?'Closed':esc(f.priority)}</span></div><div class="dw-followup-actions">${f.status==='closed'?'<span class="dw-muted">No further action</span>':booked?`<button class="dw-btn" onclick="doctorModule.viewFollowupAppointment('${f.id}')">View appointment</button>`:`<button class="dw-btn primary" onclick="doctorModule.bookFollowup('${f.id}')">Book appointment</button>`}<button class="dw-link" onclick="doctorModule.record('${f.uhid}')">Record</button>${f.status==='open'?`<button class="dw-link" onclick="doctorModule.closeFollowup('${f.id}')">Close follow-up</button>`:''}</div></div>`;}).join('')}</div></div>`);
  }
  function availabilityPage(){
    const days=Object.keys(state.availability), prefs=state.bookingPreferences; layout('Availability','Set when and how patients can book with you. Clinic-wide constraints remain visible as read-only context.','<button class="dw-btn primary" onclick="doctorModule.saveAvailability()">Save availability</button>',`<div class="dw-availability"><div class="dw-panel" style="padding:5px 17px">${days.map(d=>`<div class="dw-day"><div class="dw-day-name">${d}</div><div class="dw-slot">${d==='Sun'?'Not available':'10:00 AM – 1:00 PM · 5:00 PM – 8:00 PM'}</div><button class="dw-toggle ${state.availability[d]?'on':''}" onclick="doctorModule.toggleDay('${d}')" aria-label="Toggle ${d}"></button></div>`).join('')}</div><div class="dw-card"><h3>Your booking preferences</h3><div class="dw-form-grid"><label>Appointment duration<select id="dwDuration"><option value="15" ${prefs.duration==='15'?'selected':''}>15 minutes</option><option value="20" ${prefs.duration==='20'?'selected':''}>20 minutes</option><option value="30" ${prefs.duration==='30'?'selected':''}>30 minutes</option></select></label><label>Accept bookings up to<select id="dwAdvance"><option value="7" ${prefs.advance==='7'?'selected':''}>7 days ahead</option><option value="14" ${prefs.advance==='14'?'selected':''}>14 days ahead</option><option value="30" ${prefs.advance==='30'?'selected':''}>30 days ahead</option></select></label></div><div class="dw-mode-list"><label><input type="checkbox" id="dwModeClinic" ${prefs.clinic?'checked':''}> In-clinic consultations</label><label><input type="checkbox" id="dwModeVideo" ${prefs.video?'checked':''}> Video consultations</label><label><input type="checkbox" id="dwModeAudio" ${prefs.audio?'checked':''}> Audio consultations</label></div><div class="dw-readonly-note"><b>Clinic constraints</b><br>CityCare Clinic is open 9:00 AM–8:00 PM. Urgent slots and clinic closures are managed by the Organization Admin.</div></div></div>`);
  }
  function render(name){({doctorQueue:queuePage,doctorPatients:patientsPage,doctorProfile:patientProfilePage,doctorInbox:inboxPage,doctorFollowups:followupsPage,doctorAvailability:availabilityPage,doctorPrescriptions:prescriptionsPage}[name])();}
  function enhanceDashboard(){
    const side=document.querySelector('#page-dashboard .side-col');if(!side||document.getElementById('doctorDashboardPulse'))return;
    const card=document.createElement('div');card.className='card';card.id='doctorDashboardPulse';card.innerHTML=`<div class="card-title" style="margin-bottom:10px">Clinical priorities</div><div class="dw-list-row"><div class="grow"><b style="font-size:13px">${state.results.filter(r=>r.status==='new').length} results need review</b><div class="dw-muted">Includes 2 abnormal / clinical-review items</div></div><button class="dw-link" onclick="showPage('doctorInbox')">Open inbox</button></div><div class="dw-list-row"><div class="grow"><b style="font-size:13px">1 follow-up due today</b><div class="dw-muted">Rahul Sharma · HbA1c review</div></div><button class="dw-link" onclick="showPage('doctorFollowups')">View</button></div>`;side.appendChild(card);
  }
  function modal(title,fields,onSave){const content=document.createElement('div');content.className='dw-modal';content.id='doctorModuleModal';content.innerHTML=`<div class="dw-modal-box" role="dialog" aria-modal="true"><h2>${title}</h2><p class="dw-sub">Prototype interaction — saved to this screen’s mock data.</p>${fields}<div class="dw-modal-foot"><button class="dw-btn" onclick="doctorModule.closeModal()">Cancel</button><button class="dw-btn primary" id="dwModalSave">Save</button></div></div>`;document.body.appendChild(content);document.getElementById('dwModalSave').onclick=onSave;}
  window.doctorModule={
    filter:v=>{state.queueFilter=v;queuePage();},search:v=>{state.search=v;queuePage();},
    patientFilter:v=>{state.patientFilter=v;patientsPage();},patientSearch:v=>{state.patientSearch=v;renderPatientList();},
    start:(uhid,mode)=>{const p=todayQueue().find(x=>x.uhid===uhid);if(!p){window.showToast&&showToast('This patient has no active visit today.',true);return;}if(mode==='clinic'||mode==='walkin'||mode==='notes'){populateConsultation(p);return;}requestStartConsultation(p,mode);},
    record:uhid=>{state.profileUhid=uhid;showPage('doctorProfile');},
    recordByName:name=>{const p=known().find(x=>x.name===name);if(p)doctorModule.record(p.uhid);},
    reviewResult:id=>{const r=state.results.find(x=>x.id===id);if(!r)return; r.status='reviewed';state.followups.unshift({id:'F-'+Date.now(),uhid:r.uhid,reason:'Follow up: '+r.test+' result',due:'Within 48 hours',priority:'New task',status:'open',appointment:{status:'Not booked'}});inboxPage();window.showToast&&showToast('Result reviewed and a follow-up task was created.');},
    bookFollowup:id=>{const f=state.followups.find(x=>x.id===id);if(!f)return;const p=byUhid(f.uhid);modal('Book follow-up appointment',`<div class="dw-note">${esc(p.name)} · ${esc(f.reason)}</div><label>Date</label><input id="dwFollowupDate" type="date"><label>Time</label><input id="dwFollowupTime" type="time" value="10:30"><label>Consultation mode</label><select id="dwFollowupMode"><option>In clinic</option><option>Video</option><option>Audio</option></select><label>Booked by</label><select id="dwFollowupOwner"><option>Doctor</option><option>Reception</option><option>Nurse</option><option>Patient</option></select>`,()=>{const date=document.getElementById('dwFollowupDate').value,time=document.getElementById('dwFollowupTime').value;if(!date||!time){window.showToast&&showToast('Choose an appointment date and time.',true);return;}const displayDate=new Date(date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}),[hour,minute]=time.split(':').map(Number),displayTime=String(((hour+11)%12)+1).padStart(2,'0')+':'+String(minute).padStart(2,'0')+' '+(hour>=12?'PM':'AM');f.appointment={status:'Booked',date:displayDate,time:displayTime,mode:document.getElementById('dwFollowupMode').value,bookedBy:document.getElementById('dwFollowupOwner').value};doctorModule.closeModal();followupsPage();window.showToast&&showToast('Follow-up appointment booked in the prototype.');});},
    viewFollowupAppointment:id=>{const f=state.followups.find(x=>x.id===id),a=f?.appointment;if(!f||!a)return;const p=byUhid(f.uhid);const existing=document.getElementById('doctorModuleModal');if(existing)existing.remove();const content=document.createElement('div');content.className='dw-modal';content.id='doctorModuleModal';content.innerHTML=`<div class="dw-modal-box" role="dialog" aria-modal="true"><h2>Follow-up appointment</h2><p class="dw-sub">${esc(p.name)} · ${esc(f.reason)}</p><div class="dw-appointment-detail"><b>${esc(a.date)} · ${esc(a.time)}</b><span>${esc(a.mode)} · booked by ${esc(a.bookedBy)}</span></div><div class="dw-modal-foot"><button class="dw-btn primary" onclick="doctorModule.closeModal()">Close</button></div></div>`;document.body.appendChild(content);},
    closeFollowup:id=>{const f=state.followups.find(x=>x.id===id);if(!f)return;modal('Close clinical follow-up',`<div class="dw-note">Close this only when no further clinical review is required. Appointment scheduling alone does not close a follow-up.</div><label>Closure note</label><input id="dwClosureNote" placeholder="Reason clinical follow-up is no longer required">`,()=>{if(!document.getElementById('dwClosureNote').value.trim()){window.showToast&&showToast('Enter a closure note.',true);return;}f.status='closed';doctorModule.closeModal();followupsPage();window.showToast&&showToast('Clinical follow-up closed in the prototype.');});},
    toggleDay:d=>{state.availability[d]=!state.availability[d];availabilityPage();},
    saveAvailability:()=>{
      state.bookingPreferences={
        duration:document.getElementById('dwDuration')?.value||state.bookingPreferences.duration,
        advance:document.getElementById('dwAdvance')?.value||state.bookingPreferences.advance,
        clinic:!!document.getElementById('dwModeClinic')?.checked,
        video:!!document.getElementById('dwModeVideo')?.checked,
        audio:!!document.getElementById('dwModeAudio')?.checked
      };
      window.showToast&&showToast('Your availability and booking preferences were saved for the prototype.');
    },
    showPatientDetails:uhid=>{
      const p=byUhid(uhid),c=clinical(uhid),allergies=c.allergies||[],conditions=c.conditions||[],meds=c.currentMeds||[],records=c.records||[];
      const existing=document.getElementById('doctorPatientDetailsModal'); if(existing)existing.remove();
      const modal=document.createElement('div'); modal.className='dw-modal'; modal.id='doctorPatientDetailsModal'; modal.innerHTML=`<div class="dw-modal-box dw-patient-details" role="dialog" aria-modal="true" aria-labelledby="patientDetailsTitle"><div class="dw-modal-head"><div><h2 id="patientDetailsTitle">Patient details</h2><p class="dw-sub">Read-only context for this consultation.</p></div><button class="dw-icon-btn" aria-label="Close patient details" onclick="doctorModule.closePatientDetails()">×</button></div><div class="dw-detail-grid"><section><div class="dw-detail-label">Patient</div><div class="dw-person">${esc(p.name)}</div><div class="dw-muted">${esc(p.uhid)} · ${esc(p.age)}Y · ${esc(p.gender)} · ${esc(p.phone||'Not recorded')}</div><div class="dw-muted">ABHA: ${esc(c.abhaId||'Not linked')} · Blood group: ${esc(c.bloodGroup||'Not recorded')}</div></section><section><div class="dw-detail-label">Allergy status</div>${allergies.length?allergies.map(a=>`<span class="dw-chip alert">${esc(a.substance)} · ${esc(a.severity)}</span>`).join(' '):`<div class="dw-muted">${c.allergiesConfirmed?'No known drug allergies confirmed':'Allergy status not recorded'}</div>`}</section><section><div class="dw-detail-label">Active conditions</div>${conditions.length?conditions.map(x=>`<div class="dw-muted">${esc(x.name)} · ${esc(x.since)}</div>`).join(''):'<div class="dw-muted">No active conditions recorded.</div>'}</section><section><div class="dw-detail-label">Current medications</div>${meds.length?meds.map(x=>`<div class="dw-muted">${esc(x.drug)} ${esc(x.strength)} · ${esc(x.frequency)}</div>`).join(''):'<div class="dw-muted">No current medication recorded.</div>'}</section><section><div class="dw-detail-label">Recent records</div>${records.length?records.slice(0,3).map(x=>`<div class="dw-muted">${esc(x.name)} · ${esc(x.date)}</div>`).join(''):'<div class="dw-muted">No records available.</div>'}</section></div><div class="dw-modal-foot"><button class="dw-btn primary" onclick="doctorModule.closePatientDetails()">Close</button></div></div>`; document.body.appendChild(modal);
    },
    closePatientDetails:()=>{const el=document.getElementById('doctorPatientDetailsModal');if(el)el.remove();},
    schedule:()=>modal('Schedule appointment','<label>Patient</label><select id="dwAppointmentPatient">'+known().map(p=>`<option value="${p.uhid}">${esc(p.name)} — ${esc(p.uhid)}</option>`).join('')+'</select><label>Consultation mode</label><select id="dwAppointmentType"><option value="clinic">In clinic</option><option value="video">Video</option><option value="audio">Audio</option></select><label>Time</label><input id="dwAppointmentTime" type="time" value="11:30">',()=>{const uhid=document.getElementById('dwAppointmentPatient').value,p=byUhid(uhid),type=document.getElementById('dwAppointmentType').value,time=document.getElementById('dwAppointmentTime').value;if(!time){window.showToast&&showToast('Choose an appointment time.',true);return;}const [h,m]=time.split(':').map(Number),suffix=h>=12?'PM':'AM',hour=((h+11)%12)+1;todayQueue().push({time:String(hour).padStart(2,'0')+':'+String(m).padStart(2,'0')+' '+suffix,name:p.name,uhid:p.uhid,age:p.age,gender:p.gender,phone:p.phone,type,freq:'Scheduled',freqIcon:'cal',action:'upcoming',caption:'Appointment scheduled',paid:true,doctor:'Dr. Arjun Patel',paymentMethod:'Pending'});doctorModule.closeModal();showPage('doctorQueue');window.showToast&&showToast('Appointment scheduled and added to today’s queue.');}),
    newReferral:()=>modal('Create referral','<label>Patient</label><select id="dwPatient">'+known().map(p=>`<option value="${p.uhid}">${esc(p.name)} — ${esc(p.uhid)}</option>`).join('')+'</select><label>Refer to</label><input id="dwReferralTo" placeholder="e.g. Pulmonology"><label>Clinical reason</label><input id="dwReferralReason" placeholder="Reason for referral">',()=>{const to=document.getElementById('dwReferralTo').value.trim(),reason=document.getElementById('dwReferralReason').value.trim();if(!to||!reason){window.showToast&&showToast('Enter the referral destination and clinical reason.',true);return;}state.referrals.unshift({id:'RF-'+Date.now(),uhid:document.getElementById('dwPatient').value,to,reason,status:'Awaiting response'});doctorModule.closeModal();inboxPage();window.showToast&&showToast('Referral created and added to the clinical inbox.');}),
    newFollowup:()=>modal('Add follow-up','<label>Patient</label><select id="dwPatient">'+known().map(p=>`<option value="${p.uhid}">${esc(p.name)}</option>`).join('')+'</select><label>Clinical reason</label><input id="dwReason" placeholder="e.g. Review blood pressure"><label>Due date</label><input id="dwDue" type="date">',()=>{const reason=document.getElementById('dwReason').value.trim();if(!reason){window.showToast&&showToast('Enter the clinical reason.',true);return;}state.followups.unshift({id:'F-'+Date.now(),uhid:document.getElementById('dwPatient').value,reason,due:document.getElementById('dwDue').value||'Not scheduled',priority:'New task',status:'open'});doctorModule.closeModal();followupsPage();window.showToast&&showToast('Follow-up added.');}),
    newWalkin:()=>modal('Add walk-in visit','<label>Patient</label><select id="dwWalkinPatient">'+known().map(p=>`<option value="${p.uhid}">${esc(p.name)} — ${esc(p.uhid)}</option>`).join('')+'</select><label>Arrival time</label><input id="dwWalkinTime" type="time" value="12:00">',()=>{const uhid=document.getElementById('dwWalkinPatient').value,p=byUhid(uhid),time=document.getElementById('dwWalkinTime').value;if(!time){window.showToast&&showToast('Choose an arrival time.',true);return;}const [h,m]=time.split(':').map(Number),suffix=h>=12?'PM':'AM',hour=((h+11)%12)+1;todayQueue().push({time:String(hour).padStart(2,'0')+':'+String(m).padStart(2,'0')+' '+suffix,name:p.name,uhid:p.uhid,age:p.age,gender:p.gender,phone:p.phone,type:'clinic',freq:'Walk-in',freqIcon:'walkin',action:'active',caption:'Walk-in visit',paid:true,doctor:'Dr. Arjun Patel',paymentMethod:'Pending'});doctorModule.closeModal();showPage('doctorQueue');window.showToast&&showToast('Walk-in visit added to today’s queue.');}),
    closeModal:()=>{const el=document.getElementById('doctorModuleModal');if(el)el.remove();}
  };
  const followupsNav = document.getElementById('navSettings');
  if(followupsNav){
    followupsNav.title='Follow-ups';
    const label=followupsNav.querySelector('.nav-label'); if(label) label.textContent='Follow-ups';
  }
  // Keep the approved consultation UI unchanged. When its existing follow-up
  // fields are completed, create the clinical requirement in this worklist.
  const baseCompleteConsultation = window.completeConsultation;
  if(typeof baseCompleteConsultation==='function'){
    window.completeConsultation=function(){
      const uhid=currentPatientUhid;
      const due=document.getElementById('dateValue')?.textContent.trim();
      const type=document.getElementById('typeValue')?.textContent.trim();
      const purpose=document.getElementById('followPurpose')?.value.trim();
      const priority=document.getElementById('followPriority')?.value;
      const selectedDate=due&&due!=='Select date';
      if(uhid&&selectedDate){
        const reason=purpose||'Follow-up consultation';
        const exists=state.followups.some(f=>f.uhid===uhid&&f.reason===reason&&f.due===due&&f.status==='open');
        if(!exists) state.followups.unshift({id:'F-'+Date.now(),uhid,reason,due,priority:priority==='Urgent'?'Urgent':'Scheduled',status:'open',appointment:{status:'Not booked',preferredType:type&&type!=='Select type'?type:''}});
      }
      return baseCompleteConsultation.apply(this,arguments);
    };
  }
  doctorDashboard();
})();
