/* UX-only Emergency Care. Clinical priority is selected by a clinician, never inferred. */
(() => {
 'use strict';
 const $=s=>document.querySelector(s), KEY='hospitall-emergency-ux-v1';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stamp=()=>new Date().toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
 const registry=[{id:'PAT-1195',name:'Sana Ali',age:'29Y · Female',allergy:'No known allergies (recorded)'},{id:'PAT-1103',name:'Arjun Patel',age:'34Y · Male',allergy:'Not recorded'},{id:'PAT-1301',name:'Nila Das',age:'51Y · Female',allergy:'Not recorded'}];
 function encounter(id,p,priority,status,reason,minutes){return {id,patient:{...p},priority,status,reason,location:'Triage area',arrived:Date.now()-minutes*60000,doctor:'Dr. Priya Sharma',assessment:'',impression:'',meds:[],orders:[],observations:[],events:[],escalation:false,plan:'',reviewAt:'',disposition:null,closed:false};}
 function seed(){const list=[encounter('ER-1001',registry[0],'Not triaged','Awaiting triage','Abdominal discomfort',12),encounter('ER-1002',{id:'TEMP-1002',name:'Unidentified patient 1002',age:'Age / sex not recorded',allergy:'Unknown',temporary:true},'Immediate','In treatment','Brought after a fall',8),encounter('ER-1003',registry[1],'Standard','Observation','Dizziness review',40),encounter('ER-1004',registry[2],'Urgent','Awaiting bed','Continued monitored care requested',55)];list[1].location='Resuscitation bay 1';list[2].assessment='Initial assessment documented for this fictional encounter.';list[2].impression='Symptoms under observation';list[2].plan='Continue the documented observation plan and repeat clinician review.';list[2].reviewAt=new Date(Date.now()+30*60000).toISOString();list[3].assessment='Emergency assessment completed in this fictional scenario.';list[3].impression='Requires continued inpatient care';list[3].disposition={type:'Admission',unit:'ICU',doctor:'Dr. Amit Joshi',reason:'Continued monitored care',status:'Awaiting bed'};list.forEach(e=>e.events.push({at:stamp(),actor:'Demo fixture',text:'Emergency encounter opened.'}));return {version:1,seq:1005,encounters:list};}
 let state;try{state=DemoStore.enabled?null:JSON.parse(sessionStorage.getItem(KEY));}catch(_){}if(!state||state.version!==1||!Array.isArray(state.encounters))state=seed();
 let role='Emergency nurse',q='',priority='All priorities',status='All statuses',dirty=false,modalDirty=false,returnFocus=null;
 const nurse=()=>role==='Emergency nurse',doctor=()=>role==='Emergency doctor',desk=()=>role==='Admissions desk',clinical=()=>nurse()||doctor();
 const actor=()=>doctor()?'Dr. Priya Sharma · Emergency doctor':role;
 const persist=()=>{try{if(!DemoStore.enabled)sessionStorage.setItem(KEY,JSON.stringify(state));}catch(_){$('#notice').textContent='Browser storage unavailable. Keep this page open; cross-module handover is unavailable.';}};
 const log=(e,text)=>e.events.unshift({at:stamp(),actor:actor(),text});
 const current=()=>state.encounters.find(e=>e.id===location.hash.slice(1).split('/')[1]);
 const b=(label,action,id='',primary=false,disabled=false)=>`<button type="button" ${primary?'class="primary"':''} data-action="${action}" data-id="${esc(id)}" ${disabled?'disabled':''}>${esc(label)}</button>`;
 const a=(label,path)=>`<a class="record-link" href="#${path}">${esc(label)}</a>`;
 const badge=(label,cls='')=>`<span class="badge ${cls}">${esc(label)}</span>`;
 const field=(name,label,value='',type='text',required=true)=>`<label>${esc(label)}<input name="${name}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}" ${required?'required':''}></label>`;
 const area=(name,label,value='',required=true)=>`<label class="wide">${esc(label)}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea></label>`;
 const select=(name,label,options,value='',required=true)=>`<label>${esc(label)}<select name="${name}" ${required?'required':''}>${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
 const check=(name,label)=>`<label class="check"><input name="${name}" type="checkbox" required>${esc(label)}</label>`;
 const card=(title,body)=>`<section class="card"><h2>${esc(title)}</h2>${body}</section>`;
 const head=(title,sub,actions='')=>`<div class="page-heading"><div><h1 tabindex="-1">${esc(title)}</h1><p>${esc(sub)}</p></div><div class="actions">${actions}</div></div>`;
 const empty=text=>`<p class="empty">${esc(text)}</p>`;
 const details=rows=>rows.map(([k,v])=>`<div class="summary-row"><span>${esc(k)}</span><span>${esc(v||'Not recorded')}</span></div>`).join('');
 const nextLabels={type:'Next care',unit:'Care setting',doctor:'Receiving doctor',reason:'Clinical reason',status:'Progress',requestedAt:'Requested',bed:'Assigned bed',receiver:'Receiving clinician / team',completedAt:'Completed',facility:'Receiving hospital',transport:'Transport and escort',diagnosis:'Discharge impression',advice:'Advice and return precautions',followup:'Follow-up plan',pendingPlan:'Pending-result ownership',signedBy:'Signed by (mock)',signedAt:'Signed at'};
 const nextRows=d=>Object.entries(d).filter(([k])=>k!=='snapshot').map(([k,v])=>[nextLabels[k]||k,v]);
 const pending=e=>e.orders.filter(o=>o.status!=='Reviewed');
 const history=e=>`<ul class="timeline">${e.events.map(x=>`<li><p class="read-text">${esc(x.text)}</p><small>${esc(x.at)} · ${esc(x.actor)}</small></li>`).join('')}</ul>`;
 function notice(text){$('#notice').textContent=text;}
 function done(e,text){if(e)log(e,text);persist();closeModal(true);dirty=false;render();notice(text);}
 function guard(run){if(!dirty)return run();modal('Discard unsaved changes?', '<p>Your unsaved arrival details will be lost.</p>',()=>{dirty=false;closeModal(true);run();},'Discard changes','Keep editing');}
 function closeModal(force=false){const d=$('#er-dialog');if(!force&&modalDirty){const form=d.querySelector('form');form.hidden=true;const warning=document.createElement('div');warning.className='er-dialog-body';warning.innerHTML='<h2>Discard unsaved changes?</h2><p>The saved encounter remains unchanged.</p><div class="actions"><button data-keep>Keep editing</button><button data-discard>Discard changes</button></div>';d.append(warning);warning.querySelector('[data-keep]').onclick=()=>{warning.remove();form.hidden=false;form.querySelector('input,select,textarea,button')?.focus();};warning.querySelector('[data-discard]').onclick=()=>closeModal(true);warning.querySelector('button').focus();return;}d.close();d.replaceChildren();modalDirty=false;returnFocus?.isConnected&&returnFocus.focus();}
 function modal(title,body,save,submit='Save',cancel='Cancel'){
  const d=$('#er-dialog');returnFocus=document.activeElement;modalDirty=false;
  d.innerHTML=`<form novalidate><div class="er-dialog-head"><h2 id="dialog-title">${esc(title)}</h2><button type="button" aria-label="Close dialog">×</button></div><div class="er-dialog-body"><div class="errors" role="alert"></div>${body}</div><div class="er-dialog-foot"><button type="button" data-cancel>${esc(cancel)}</button>${save?`<button type="submit" class="primary">${esc(submit)}</button>`:''}</div></form>`;
  const form=d.querySelector('form');d.querySelector('[aria-label="Close dialog"]').onclick=d.querySelector('[data-cancel]').onclick=()=>closeModal();
  form.oninput=()=>modalDirty=true;form.onsubmit=ev=>{ev.preventDefault();if(!validate(form))return;save?.(Object.fromEntries(new FormData(form)),form);};if(!d.open)d.showModal();
 }
 function fail(form,message){form.querySelector('.errors').innerHTML=`<div class="error-summary" tabindex="-1">${esc(message)}</div>`;form.querySelector('.error-summary').focus();return false;}
 function validate(form){const invalid=[...form.elements].filter(el=>el.willValidate&&(!el.checkValidity()||(el.required&&el.type!=='checkbox'&&!el.value.trim())));form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));if(invalid.length){invalid.forEach(el=>el.setAttribute('aria-invalid','true'));return fail(form,'Complete the required fields and confirmations.');}form.querySelector('.errors').innerHTML='';return true;}
 $('#er-dialog').addEventListener('cancel',e=>{e.preventDefault();if($('#er-dialog [data-keep]')){$('#er-dialog [data-keep]').click();}else closeModal();});
 const icon=path=>`<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="${path}"/></svg>`;
 $('.brand-mark').innerHTML=icon('M20 5a5 5 0 0 0-8 1 5 5 0 0 0-8-1c-5 5 8 15 8 15S25 10 20 5ZM3 12h5l2-3 3 6 2-3h6');
 const nav=[['board','Emergency board','M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z'],['arrival','Register arrival','M12 3v18M3 12h18'],['observation','Observation','M3 12h4l3-8 4 16 3-8h4'],['handover','Handover worklist','M3 7h18m-5-4 5 4-5 4M21 17H3m5-4-5 4 5 4'],['completed','Completed encounters','M5 3h14v18H5Zm3 9 3 3 5-6']];
 $('#nav-links').innerHTML=nav.map(([id,label,path])=>`<a href="#${id}" data-nav="${id}" title="${label}">${icon(path)}<span class="nav-label">${label}</span></a>`).join('');
 function row(e){return `<article class="er-row priority-${esc(e.priority)}"><div>${a(e.patient.name,`patient/${e.id}/overview`)}<p><small>${esc(e.patient.id)} · ${e.id}</small></p>${e.patient.temporary?badge('Identity unconfirmed','warn'):''}</div><div><strong>${esc(e.reason||'Complaint not yet recorded')}</strong><p>${esc(e.location)}</p><small>${esc(e.doctor)}</small></div><div>${badge(e.priority,'priority-'+e.priority)}<p>${badge(e.status)}</p>${e.escalation?'<p class="error">Escalation · doctor review needed</p>':''}${e.reviewAt&&new Date(e.reviewAt)<new Date()&&!e.closed?'<p class="error">Reassessment overdue</p>':''}<small>Arrived ${new Date(e.arrived).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</small></div><div class="actions">${a('Open encounter',`patient/${e.id}/overview`)}</div></article>`;}
 function board(page){const active=state.encounters.filter(e=>!e.closed);let list=state.encounters.filter(e=>page==='completed'?e.closed:!e.closed&& (page==='observation'?e.status==='Observation':page==='handover'?!!e.disposition:true));const titles={board:'Emergency board',observation:'Observation & reassessment',handover:'Handover worklist',completed:'Completed encounters'};const rank={Immediate:0,'Not triaged':1,Urgent:2,Standard:3};list=list.filter(e=>(priority==='All priorities'||e.priority===priority)&&(status==='All statuses'||e.status===status)&&[e.id,e.patient.id,e.patient.name,e.reason].join(' ').toLowerCase().includes(q.toLowerCase())).sort((x,y)=>(rank[x.priority]-rank[y.priority])||x.arrived-y.arrived);return head(titles[page],page==='board'?'Prioritized by clinician-assigned urgency, then arrival. Untriaged patients remain visible.':'Select an encounter to review care and the next step.',a('Register arrival','arrival'))+(page==='board'?`<div class="stats"><div class="stat"><strong>${active.filter(e=>e.priority==='Immediate').length}</strong><span>Immediate priority</span></div><div class="stat"><strong>${active.filter(e=>e.status==='Awaiting triage').length}</strong><span>Awaiting triage</span></div><div class="stat"><strong>${active.filter(e=>e.status==='Observation').length}</strong><span>In observation</span></div><div class="stat"><strong>${active.filter(e=>e.disposition).length}</strong><span>Awaiting next care</span></div></div>`:'')+`<div class="filters"><label>Search encounters<input id="board-search" type="search" value="${esc(q)}" placeholder="Patient name, patient ID or encounter"></label>${select('priority','Priority',['All priorities','Immediate','Urgent','Standard','Not triaged'],priority,false)}${select('status','Status',['All statuses',...new Set(state.encounters.map(e=>e.status))],status,false)}${b('Clear filters','clear')}</div><div class="er-board">${list.map(row).join('')||empty('No encounters match these filters.')}</div>`;}
 const arrivalPatients=()=>[...new Map([...registry,...state.encounters.filter(e=>!e.patient.temporary).map(e=>e.patient)].map(p=>[p.id,p])).values()];
 function patientPicker(){return '<div class="arrival-picker"><label for="arrival-patient-search">Patient</label><input id="arrival-patient-search" type="search" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="arrival-patient-results" autocomplete="off" placeholder="Search by patient name or ID" required><input type="hidden" name="patient"><div id="arrival-patient-results" role="listbox" aria-label="Matching patients" hidden></div><small id="arrival-search-status" role="status"></small></div>';}
 function bindPatientPicker(form){const input=$('#arrival-patient-search');if(!input)return;const list=$('#arrival-patient-results'),status=$('#arrival-search-status');let found=[],active=-1;
 const close=()=>{list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');};
 const choose=i=>{const p=found[i];if(!p)return;form.elements.patient.value=p.id;input.value=p.name+' · '+p.id;status.textContent=p.age;dirty=true;close();input.focus();};
 const show=()=>{const term=input.value.trim().toLowerCase();found=arrivalPatients().filter(p=>!term||[p.name,p.id].join(' ').toLowerCase().includes(term));active=-1;list.innerHTML=found.map((p,i)=>'<button type="button" role="option" tabindex="-1" aria-selected="false" id="arrival-option-'+i+'"><strong>'+esc(p.name)+'</strong><small>'+esc(p.id)+' · '+esc(p.age)+'</small></button>').join('')||'<p class="arrival-no-match">No matching patients. Try another name or patient ID.</p>';list.hidden=false;input.setAttribute('aria-expanded','true');input.removeAttribute('aria-activedescendant');status.textContent=found.length+' matching patient'+(found.length===1?'':'s');list.querySelectorAll('button').forEach((button,i)=>{button.onmousedown=e=>e.preventDefault();button.onclick=()=>choose(i);});};
 input.oninput=()=>{form.elements.patient.value='';form.querySelector('.errors').innerHTML='';input.removeAttribute('aria-invalid');show();};input.onfocus=()=>{if(!form.elements.patient.value)show();};input.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close();return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(list.hidden)show();if(!found.length)return;active=(active+(e.key==='ArrowDown'?1:-1)+found.length)%found.length;list.querySelectorAll('[role=option]').forEach((el,i)=>el.setAttribute('aria-selected',String(i===active)));input.setAttribute('aria-activedescendant','arrival-option-'+active);$('#arrival-option-'+active).scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&!list.hidden){e.preventDefault();if(found.length)choose(active<0?0:active);}};
 input.onblur=()=>setTimeout(()=>{if(document.activeElement!==input&&!list.contains(document.activeElement))close();},100);
 }
 function newDemographics(){return '<div class="arrival-demographics">'+field('age','Age (if known)','','number',false)+select('ageUnit','Age unit',['Years','Months','Days'],'Years',false)+select('sex','Sex',['Unknown','Female','Male','Other'],'Unknown',false)+'</div><small>Leave age blank or sex unknown when the details are unavailable.</small>';}
 function bindDemographics(form){const age=form.elements.age;if(!age)return;age.step='1';age.min='0';const update=()=>{age.max=({Years:130,Months:1560,Days:47483})[form.elements.ageUnit.value];};const clear=()=>{if(age.checkValidity()){age.removeAttribute('aria-invalid');const errors=form.querySelector('.errors');if(errors.textContent.startsWith('Enter a whole-number age'))errors.innerHTML='';}};age.oninput=clear;form.elements.ageUnit.onchange=()=>{update();clear();};update();}
 function recordedDemographics(f){return (f.age!==''?f.age+' '+f.ageUnit.toLowerCase():'Age not recorded')+' · '+(f.sex==='Unknown'?'Sex not recorded':f.sex);}
 function arrival(){return head('Register emergency arrival','Use a temporary identity if details are unavailable. Registration and payment must not delay urgent care.')+card('Patient identity',`<form id="arrival-form" novalidate><div class="errors" role="alert"></div><div class="fields">${select('identity','Identity available',['Existing patient','New patient','Unidentified patient'])}<div id="arrival-identity">${patientPicker()}</div><div id="arrival-demographics" class="wide" hidden></div>${area('complaint','Presenting complaint / arrival note (optional)','',false)}</div><p class="muted">Encounter number, arrival time and temporary patient ID are generated automatically.</p><div class="actions">${b('Cancel','arrival-cancel')}<button class="primary" type="submit">Create emergency encounter</button></div></form>`);}
 const tabs=[['overview','Overview'],['assessment','Assessment'],['treatment','Treatment & results'],['observations','Observations'],['next','Next care'],['history','History']];
 function summary(e){return details([['Encounter',e.id],['Patient',e.patient.name+' · '+e.patient.id],['Allergies',e.patient.allergy],['Presenting complaint',e.reason],['Assessment',e.assessment],['Impression',e.impression],['Medication events',e.meds.map(m=>`${m.name} · ${m.dose} · ${m.route} · ${m.status}${m.note?' · '+m.note:''}${m.at?' · '+m.at:''}`).join('\n')||'None recorded'],['Investigations',e.orders.map(o=>`${o.name} · ${o.status}${o.result?' · '+o.result:''}`).join('\n')||'None recorded'],['Latest observation',e.observations[0]?.text],['Next-care plan',e.disposition?nextRows(e.disposition).map(([k,v])=>`${k}: ${v}`).join('\n'):e.plan]]);}
 function workspace(){const e=current();if(!e)return head('Encounter not found','Return to the emergency board.',a('Emergency board','board'));const tab=location.hash.split('/')[2]||'overview';let content='';const edit=!e.closed;
  if(tab==='overview')content=`<div class="er-grid">${card('Current care',details([['Presenting complaint',e.reason],['Assessment',e.assessment],['Working impression',e.impression],['Location',e.location],['Responsible doctor',e.doctor],['Observation plan',e.plan],['Next reassessment',e.reviewAt?new Date(e.reviewAt).toLocaleString('en-GB'):'Not scheduled']])+`<div class="actions">${edit&&clinical()?b(e.priority==='Not triaged'?'Record triage':'Update triage / priority','triage',e.id,true):''}${edit&&doctor()?b('Record assessment','assessment',e.id):''}${edit&&e.escalation&&doctor()?b('Review escalation','acknowledge',e.id,true):''}${edit&&e.patient.temporary?b('Resolve patient identity','identity',e.id):''}</div>`)}${card('Outstanding care',`<p>${pending(e).length} investigation(s) awaiting result or review.</p><p>${e.meds.filter(m=>m.status==='Ordered').length} medication order(s) awaiting administration.</p>${e.escalation?'<p class="error">Escalation remains open until a doctor records review.</p>':''}${e.disposition?`<p>Next care: ${esc(e.disposition.type)} · ${esc(e.disposition.status)}</p>${a('Review handover','patient/'+e.id+'/next')}`:a('Plan next care','patient/'+e.id+'/next')}`)}</div>`;
  if(tab==='assessment')content=card('Doctor assessment',details([['Findings',e.assessment],['Working impression',e.impression]])+(edit&&doctor()?b('Record assessment','assessment',e.id,true):'<p class="footnote">Assessment is documented by the Emergency doctor.</p>'));
  if(tab==='treatment')content=`<div class="er-grid">${card('Medication orders & administration',`<div class="actions">${edit&&doctor()?b('Add medication order','medication',e.id,true):''}</div>${e.meds.map(m=>`<div class="list-row"><div><strong>${esc(m.name)}</strong><p>${esc(m.dose)} · ${esc(m.route)}</p><p>${badge(m.status)} ${esc(m.note||'')}</p><small>${esc(m.at||m.orderedAt)}</small></div>${edit&&nurse()&&m.status==='Ordered'?b('Record administration','administer',m.id):''}</div>`).join('')||empty('No medication orders recorded.')}`)}${card('Investigations',`<div class="actions">${edit&&doctor()?b('Request investigation','investigation',e.id,true):''}</div>${e.orders.map(o=>`<div class="list-row"><div><strong>${esc(o.name)}</strong><p>${badge(o.status)}</p><p class="read-text">${esc(o.result||'Result not yet available')}</p></div><div class="actions">${edit&&clinical()&&o.status==='Requested'?b('Add mock result','result',o.id):''}${edit&&doctor()&&o.status==='Result available'?b('Review result','review-result',o.id):''}</div></div>`).join('')||empty('No investigations requested.')}`)}</div>`;
  if(tab==='observations')content=card('Observation & reassessment',details([['Plan',e.plan],['Next review',e.reviewAt?new Date(e.reviewAt).toLocaleString('en-GB'):'Not scheduled']])+`<div class="actions">${edit&&doctor()?b('Set observation plan','observe',e.id,true):''}${edit&&clinical()?b('Record observation','observation',e.id)+b('Escalate deterioration','escalate',e.id):''}${edit&&doctor()&&e.escalation?b('Review escalation','acknowledge',e.id):''}</div>`+`<ul class="timeline">${e.observations.map(o=>`<li><p class="read-text">${esc(o.text)}</p><small>${esc(o.at)} · ${esc(o.actor)}</small></li>`).join('')||'<li>No observations recorded.</li>'}</ul>`);
  if(tab==='next')content=nextCare(e);
  if(tab==='history')content=card('Encounter history',history(e));
  return head('Emergency encounter',e.id+' · '+e.status,a(e.closed?'Completed encounters':'Emergency board',e.closed?'completed':'board'))+`<section class="patient-banner" aria-label="Patient identity"><div><h2>${esc(e.patient.name)}</h2><p>${esc(e.patient.id)} · ${esc(e.patient.age)}</p></div><div><small>ALLERGY STATUS</small><strong>${esc(e.patient.allergy)}</strong></div><div>${badge(e.priority,'priority-'+e.priority)}${e.patient.temporary?badge('Identity unconfirmed','warn'):''}</div></section>`+(e.escalation?'<div class="banner warning">Escalation open · Emergency doctor review required. Disposition cannot be completed until reviewed.</div>':'')+(e.closed?'<div class="banner">Closed encounter · Clinical documentation is read-only.</div>':'')+`<nav class="tabs" aria-label="Emergency encounter sections">${tabs.map(([id,label])=>`<a href="#patient/${e.id}/${id}" class="${id===tab?'active':''}" ${id===tab?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`+content;
 }
 function nextCare(e){const d=e.disposition;if(e.closed)return card('Completed '+(d?.type||'care'),summary(e)+`<div class="actions">${b('View summary','summary',e.id,true)}${d?.type==='Admission'?`<a class="record-link" href="inpatient.html#patient/IPD-${e.id}/overview">Open inpatient admission</a>`:''}</div>`);
  if(!d)return card('Choose the next care setting',`<p>Doctor decision follows assessment. Observation remains available while assessment or results are pending.</p>${!e.assessment?'<p class="banner warning">Record the doctor assessment before planning departure or admission.</p>':''}<div class="actions">${doctor()?b('Plan discharge','discharge',e.id,true,!e.assessment)+b('Request inpatient admission','admit',e.id,false,!e.assessment)+b('Arrange external transfer','transfer',e.id,false,!e.assessment)+b('Set observation plan','observe',e.id):'<p class="footnote">Switch to Emergency doctor to record the next-care decision.</p>'}</div>`);
  let actions='';if(d.type==='Admission'){actions=desk()?b('Assign available bed','bed',e.id,true,d.status!=='Awaiting bed'):'';if(nurse()&&d.status==='Bed assigned')actions+=b('Complete inpatient handover','handover',e.id,true,e.escalation);}
  if(d.type==='Discharge'&&nurse())actions=b('Confirm discharge departure','depart',e.id,true,e.escalation);
  if(d.type==='Transfer'&&nurse()){actions=d.status==='Awaiting acceptance'?b('Record receiving acceptance','accept-transfer',e.id,true):b('Complete transfer handover','depart',e.id,true,e.escalation);}
  return card(d.type+' plan',details(nextRows(d))+`<p class="footnote">${d.type==='Admission'?'A request is not an admission. The patient remains in Emergency until bed assignment and receiving-team handover are confirmed.':d.type==='Transfer'?'Acceptance and physical departure are recorded separately. No transport is dispatched by this demo.':'The patient remains in Emergency until instructions and actual departure are confirmed.'}</p><div class="actions">${actions}${b('View handover summary','summary',e.id)}${doctor()?b('Cancel next-care plan','cancel-plan',e.id):''}</div>`);
 }
 function render(){const route=location.hash.slice(1).split('/')[0]||'board';$('#content').innerHTML=route==='patient'?workspace():route==='arrival'?arrival():board(nav.some(n=>n[0]===route)?route:'board');$('#nav-links').querySelectorAll('a').forEach(el=>{const active=el.dataset.nav===(route==='patient'?(current()?.closed?'completed':'board'):route);el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});dirty=false;bind();}
 function bind(){const search=$('#board-search');if(search)search.oninput=()=>{const start=search.selectionStart;q=search.value;render();$('#board-search').focus();$('#board-search').setSelectionRange?.(start,start);};for(const name of ['priority','status']){const el=$(`[name="${name}"]`);if(el)el.onchange=()=>{if(name==='priority')priority=el.value;else status=el.value;render();};}const form=$('#arrival-form');if(form){form.oninput=()=>dirty=true;form.elements.identity.onchange=()=>{$('#arrival-identity').innerHTML=form.elements.identity.value==='Existing patient'?patientPicker():form.elements.identity.value==='New patient'?field('name','Patient name'): '<p class="banner">A temporary patient ID will be generated. Identity can be resolved after immediate care begins.</p>';const demographics=$('#arrival-demographics');demographics.hidden=form.elements.identity.value!=='New patient';demographics.innerHTML=demographics.hidden?'':newDemographics();bindPatientPicker(form);bindDemographics(form);dirty=true;};bindPatientPicker(form);form.onsubmit=ev=>{ev.preventDefault();const age=form.elements.age;if(age&&age.value&&!age.checkValidity()){age.setAttribute('aria-invalid','true');return fail(form,'Enter a whole-number age between 0 and '+age.max+' '+form.elements.ageUnit.value.toLowerCase()+', or leave age blank if unknown.');}if(!validate(form))return;const f=Object.fromEntries(new FormData(form)),id='ER-'+state.seq;let p=f.identity==='Existing patient'?arrivalPatients().find(x=>x.id===f.patient):f.identity==='New patient'?{id:'PAT-ER-'+state.seq,name:f.name.trim(),age:recordedDemographics(f),ageValue:f.age===''?null:Number(f.age),ageUnit:f.ageUnit,sex:f.sex,allergy:'Unknown'}:{id:'TEMP-'+state.seq,name:'Unidentified patient '+state.seq,temporary:true,age:'Age / sex not recorded',allergy:'Unknown'};if(!p)return fail(form,'Select a patient from the search results.');if(state.encounters.some(e=>!e.closed&&e.patient.id===p.id))return fail(form,'This patient already has an active Emergency encounter. Open it from the board.');state.seq++;const e=encounter(id,p,'Not triaged','Awaiting triage',f.complaint.trim(),0);state.encounters.push(e);log(e,'Arrival registered.');persist();dirty=false;location.hash='patient/'+id+'/overview';notice('Arrival recorded. Continue triage or immediate care.');};}}
 let occupiedBeds=[];
 const bedList=[{id:'A-101-2',unit:'General ward'},{id:'P-202',unit:'General ward'},{id:'P-204',unit:'General ward'}];
 const availableBeds=e=>bedList.filter(b=>!occupiedBeds.includes(b.id)&&b.unit===e.disposition.unit&&!state.encounters.some(x=>x.disposition?.bed===b.id));
 function action(name,id){const e=current(),edit=e&&!e.closed;
  if(name==='clear'){q='';priority='All priorities';status='All statuses';return render();}
  if(name==='arrival-cancel')return guard(()=>location.hash='board');
  if(name==='reset')return modal('Reset Emergency demo?', '<p>Restore the original fictional data across all connected modules? Saved bookings, clinical records and dispensing changes will be cleared.</p>',()=>DemoStore.reset(),'Reset Emergency demo');
  if(name==='summary')return modal('Emergency care summary',summary(e),null,'','Close summary');
  if(!edit)return;
  const patient=`<p><strong>${esc(e.patient.name)}</strong> · ${e.id}</p>`;
  if(name==='identity')return modal('Resolve patient identity',patient+`<div class="fields">${select('match','Existing patient match',[['','No existing match'],...registry.map(p=>[p.id,p.name+' · '+p.id])],'',false)}${field('name','Name if no existing match','','text',false)}</div>`+check('checked','Identity checked against the available patient information'),(f,form)=>{const p=registry.find(p=>p.id===f.match);if(!p&&!f.name.trim())return fail(form,'Enter a name or select an existing patient.');if(p&&state.encounters.some(x=>x!==e&&!x.closed&&x.patient.id===p.id))return fail(form,'That patient already has an active Emergency encounter. Identity was not merged.');const old=e.patient.id;e.patient=p?{...p}:{...e.patient,id:'PAT-'+e.id,name:f.name.trim(),temporary:false};e.patient.previousTemporaryId=old;done(e,'Identity resolved; previous identity '+old+' retained.');},'Confirm identity');
  if(name==='triage'&&clinical())return modal('Record triage / priority',patient+`<div class="fields">${select('priority','Clinician-assigned priority',[['','Select priority'],'Immediate','Urgent','Standard'],e.priority)}${select('location','Care location',['Triage area','Resuscitation bay 1','Treatment bay 2','Observation bay 3'],e.location)}${area('reason','Presenting complaint',e.reason)}${select('allergy','Allergy status',['Unknown','No known allergies (reported)','Known allergy'],['Unknown','Not recorded'].includes(e.patient.allergy)?'Unknown':e.patient.allergy.includes('No known')?'No known allergies (reported)':'Known allergy')}${field('detail','Allergy details if known',e.patient.allergy.includes('No known')||['Unknown','Not recorded'].includes(e.patient.allergy)?'':e.patient.allergy,'text',false)}</div><p class="footnote">Priority is assigned by a clinician using the hospital’s approved protocol. This demo does not calculate a clinical score.</p>`,(f,form)=>{if(f.allergy==='Known allergy'&&!f.detail.trim())return fail(form,'Record the known allergy details.');e.priority=f.priority;e.reason=f.reason.trim();e.location=f.location;e.patient.allergy=f.allergy==='Known allergy'?f.detail.trim():f.allergy;if(e.status==='Awaiting triage')e.status=f.priority==='Immediate'?'In treatment':'Waiting for clinician';done(e,'Triage recorded: '+f.priority+' priority.');},'Save triage');
  if(name==='assessment'&&doctor())return modal('Record doctor assessment',patient+`<div class="fields">${area('findings','Clinical findings',e.assessment)}${area('impression','Working impression',e.impression)}</div>`,f=>{e.assessment=f.findings.trim();e.impression=f.impression.trim();if(['Awaiting triage','Waiting for clinician'].includes(e.status))e.status='In treatment';done(e,'Doctor assessment recorded.');},'Save assessment');
  if(name==='medication'&&doctor())return modal('Add mock medication order',patient+`<div class="fields">${field('name','Medication name')}${field('dose','Dose / instruction')}${select('route','Route',['Oral','Intravenous','Intramuscular','Inhaled','Other'])}</div><p class="footnote">Mock documentation only. No dose or treatment recommendation is generated.</p>`,f=>{e.meds.push({id:'MED-'+Date.now(),name:f.name.trim(),dose:f.dose.trim(),route:f.route,status:'Ordered',orderedAt:stamp()});done(e,'Medication order recorded: '+f.name+'.');},'Save mock order');
  if(name==='administer'&&nurse()){const m=e.meds.find(m=>m.id===id);if(!m||m.status!=='Ordered')return;return modal('Record medication administration',patient+details([['Medication',m.name],['Dose',m.dose],['Route',m.route]])+`<div class="fields">${select('status','Outcome',['Given','Held'])}${area('note','Reason if held / administration note (optional)','',false)}</div>`+check('checked','Patient identity and medication order checked'),(f,form)=>{if(f.status==='Held'&&!f.note.trim())return fail(form,'Record why the medication was held.');Object.assign(m,{status:f.status,note:f.note.trim(),at:stamp(),actor:actor()});done(e,m.name+': '+f.status.toLowerCase()+'.');},'Save administration');}
  if(name==='investigation'&&doctor())return modal('Request investigation',patient+field('name','Investigation name'),f=>{e.orders.push({id:'ORD-'+Date.now(),name:f.name.trim(),status:'Requested',at:stamp()});done(e,'Investigation requested: '+f.name+'.');},'Save request');
  if(name==='result'&&clinical()){const o=e.orders.find(o=>o.id===id);if(!o||o.status!=='Requested')return;return modal('Add mock result',patient+`<p>${esc(o.name)}</p>`+area('result','Mock result text'),f=>{o.result=f.result.trim();o.status='Result available';done(e,'Result available for doctor review: '+o.name+'.');},'Save mock result');}
  if(name==='review-result'&&doctor()){const o=e.orders.find(o=>o.id===id);if(!o||o.status!=='Result available')return;return modal('Review investigation result',patient+details([['Investigation',o.name],['Result',o.result]])+area('plan','Clinical interpretation / action'),f=>{o.status='Reviewed';o.review=f.plan.trim();done(e,'Result reviewed: '+o.name+' — '+f.plan);},'Record review');}
  if(name==='observe'&&doctor())return modal('Set observation plan',patient+`<div class="fields">${area('plan','Observation plan',e.plan)}${field('due','Next reassessment time','','datetime-local')}</div>`,(f,form)=>{if(new Date(f.due)<=new Date())return fail(form,'Choose a future reassessment time.');e.plan=f.plan.trim();e.reviewAt=new Date(f.due).toISOString();if(!e.disposition)e.status='Observation';done(e,'Observation plan and reassessment scheduled.');},'Save observation plan');
  if(name==='observation'&&clinical())return modal('Record observation',patient+`<div class="fields">${field('bp','Blood pressure (mmHg, optional)','','text',false)}${field('pulse','Pulse (bpm, optional)','','number',false)}${field('spo2','SpO₂ (%, optional)','','number',false)}${field('temp','Temperature (°C, optional)','','number',false)}${area('note','Observation note')}</div>`,(f,form)=>{if(f.spo2&&(Number(f.spo2)<0||Number(f.spo2)>100))return fail(form,'SpO₂ must be between 0 and 100.');if(f.pulse&&Number(f.pulse)<=0)return fail(form,'Pulse must be a positive number.');const text=[f.bp?'BP '+f.bp+' mmHg':'',f.pulse?'Pulse '+f.pulse+' bpm':'',f.spo2?'SpO₂ '+f.spo2+'%':'',f.temp?'Temperature '+f.temp+' °C':'',f.note].filter(Boolean).join(' · ');e.observations.unshift({at:stamp(),actor:actor(),text,bp:f.bp,pulse:f.pulse,spo2:f.spo2,temp:f.temp});done(e,'Observation recorded.');},'Save observation');
  if(name==='escalate'&&clinical())return modal('Escalate deterioration',patient+area('reason','Change observed / escalation reason'),f=>{if(e.disposition){log(e,'Next-care plan withdrawn after deterioration: '+nextRows(e.disposition).map(([label,value])=>label+': '+value).join(' · '));e.disposition=null;e.status='In treatment';}e.escalation=true;e.priority='Immediate';e.escalationReason=f.reason.trim();done(e,'Deterioration escalated: '+f.reason+'. Immediate review flagged; contact the duty team directly.');},'Flag immediate review');
  if(name==='acknowledge'&&doctor())return modal('Review escalation',patient+details([['Escalation reason',e.escalationReason]])+area('review','Doctor reassessment and next action'),f=>{e.escalation=false;done(e,'Escalation reviewed: '+f.review);},'Record doctor review');
  if(['admit','discharge','transfer'].includes(name)&&doctor()&&e.assessment&&!e.disposition){if(e.escalation)return notice('Review the open escalation before planning next care.');
   if(name==='admit')return modal('Request inpatient admission',patient+`<div class="fields">${select('unit','Requested care setting',['General ward','ICU'])}${select('doctor','Receiving doctor',['Dr. Priya Sharma','Dr. Amit Joshi'])}${area('reason','Admission reason',e.impression)}</div>`,f=>{e.disposition={type:'Admission',unit:f.unit,doctor:f.doctor,reason:f.reason.trim(),status:'Awaiting bed',requestedAt:stamp()};e.status='Awaiting bed';done(e,'Inpatient admission requested. Emergency care continues while awaiting a bed.');},'Create admission request');
   if(name==='transfer')return modal('Arrange external transfer',patient+`<div class="fields">${field('facility','Receiving hospital')}${area('reason','Transfer reason / required care')}</div>`,f=>{e.disposition={type:'Transfer',facility:f.facility.trim(),reason:f.reason.trim(),status:'Awaiting acceptance',requestedAt:stamp()};e.status='Awaiting acceptance';done(e,'Transfer requested. Receiving acceptance is still pending.');},'Save transfer plan');
   return modal('Review and sign discharge plan',patient+details([['Working impression',e.impression],['Pending investigations',pending(e).map(o=>o.name+' · '+o.status).join(', ')||'None']])+`<div class="fields">${area('diagnosis','Discharge diagnosis / impression',e.impression)}${area('advice','Discharge advice and return precautions')}${area('followup','Follow-up plan')}${pending(e).length?area('pending','Pending-result follow-up: responsible clinician and contact plan'):''}</div>`+check('reviewed','Assessment, medication events, results and discharge plan reviewed'),f=>{e.disposition={type:'Discharge',diagnosis:f.diagnosis.trim(),advice:f.advice.trim(),followup:f.followup.trim(),pendingPlan:f.pending?.trim()||'No pending investigations',signedBy:actor(),signedAt:stamp(),status:'Awaiting departure'};e.status='Awaiting departure';done(e,'Discharge plan signed (mock). Confirm instructions and departure next.');},'Sign mock discharge plan');
  }
  if(name==='bed'&&desk()&&e.disposition?.type==='Admission'&&e.disposition.status==='Awaiting bed'){const beds=availableBeds(e);if(!beds.length)return modal('No bed available',patient+`<p>No ${esc(e.disposition.unit)} bed is available in this demo. The patient remains in Emergency; continue care and escalate capacity through the hospital team.</p><p>The Emergency doctor can cancel this plan and arrange another appropriate destination.</p>`,null,'','Keep awaiting bed');return modal('Assign inpatient bed',patient+select('bed','Available bed',beds.map(b=>b.id)),(f,form)=>{if(!availableBeds(e).some(b=>b.id===f.bed))return fail(form,'This bed is no longer available. Choose another bed.');e.disposition.bed=f.bed;e.disposition.status='Bed assigned';e.status='Awaiting handover';done(e,'Bed '+f.bed+' assigned. Receiving-team handover remains pending.');},'Assign bed');}
  if(name==='handover'&&nurse()&&e.disposition?.type==='Admission'&&e.disposition.status==='Bed assigned'&&!e.escalation)return modal('Complete inpatient handover',patient+summary(e)+field('receiver','Receiving nurse / team')+check('accepted','Receiving team accepted the patient and pending care')+check('moved','Patient physically handed over to the assigned bed'),f=>{e.disposition.receiver=f.receiver.trim();e.disposition.status='Handover completed';e.disposition.completedAt=stamp();e.closed=true;e.status='Admitted to inpatient';done(e,'Inpatient handover completed. The linked admission is available.');},'Complete handover');
  if(name==='accept-transfer'&&nurse()&&e.disposition?.type==='Transfer'&&e.disposition.status==='Awaiting acceptance')return modal('Record receiving acceptance',patient+details([['Receiving hospital',e.disposition.facility]])+`<div class="fields">${field('receiver','Accepting clinician / team')}${area('transport','Confirmed transport and escort plan')}</div>`+check('accepted','Receiving hospital acceptance confirmed'),f=>{Object.assign(e.disposition,{receiver:f.receiver.trim(),transport:f.transport.trim(),status:'Accepted · awaiting departure'});e.status='Awaiting transfer';done(e,'Receiving acceptance recorded. Departure remains pending.');},'Save acceptance');
  if(name==='depart'&&nurse()&&e.disposition&&!e.escalation){const d=e.disposition;if(!['Discharge','Transfer'].includes(d.type)||d.status==='Awaiting acceptance')return;return modal(d.type==='Discharge'?'Confirm discharge departure':'Complete transfer handover',patient+summary(e)+check('explained',d.type==='Discharge'?'Instructions, return precautions and follow-up explained':'Clinical summary, medication events and pending results handed over')+check('left','Patient departure confirmed'),()=>{d.status='Completed';d.completedAt=stamp();e.closed=true;e.status=d.type==='Discharge'?'Discharged':'Transferred';done(e,e.status+' · Emergency encounter closed.');},'Confirm departure');}
  if(name==='cancel-plan'&&doctor()&&e.disposition)return modal('Cancel next-care plan',patient+area('reason','Reason for changing the plan'),f=>{log(e,'Previous next-care plan retained: '+nextRows(e.disposition).map(([label,value])=>label+': '+value).join(' · '));e.disposition=null;e.status='In treatment';done(e,'Next-care plan cancelled: '+f.reason);},'Cancel plan');
 }
 document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(el&&!el.disabled)action(el.dataset.action,el.dataset.id);const link=ev.target.closest('a');if(link&&(link.hash||link.classList.contains('home-link'))&&dirty){ev.preventDefault();guard(()=>{location.href=link.href;});}if(link?.hash)closeNav();});
 document.addEventListener('input',ev=>{if(ev.target.closest('#arrival-form'))dirty=true;});
 window.addEventListener('beforeunload',ev=>{if(dirty||modalDirty){ev.preventDefault();ev.returnValue='';}});
 $('#persona').onchange=ev=>{const next=ev.target.value;ev.target.value=role;guard(()=>{role=next;ev.target.value=role;$('#role-label').textContent=role;render();notice('Previewing '+role+'.');});};
 window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);$('#content h1')?.focus({preventScroll:true});});
 const shell=$('#shell'),mobile=()=>matchMedia('(max-width:700px)').matches;
 function syncNav(){const open=mobile()?shell.classList.contains('drawer'):!shell.classList.contains('collapsed');$('#menu').setAttribute('aria-label',open?'Collapse navigation':'Expand navigation');$('#menu').setAttribute('aria-expanded',String(open));$('main').inert=mobile()&&open;}
 function closeNav(){shell.classList.remove('drawer');syncNav();}
 function toggleNav(){shell.classList.toggle(mobile()?'drawer':'collapsed');syncNav();if(mobile())(shell.classList.contains('drawer')?$('.collapse'):$('#menu')).focus();}
 $('#menu').onclick=$('.collapse').onclick=toggleNav;$('.scrim').onclick=()=>{closeNav();$('#menu').focus();};window.addEventListener('resize',syncNav);document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&shell.classList.contains('drawer')){closeNav();$('#menu').focus();}});
 const res=$('.resizer');let width=212,drag=false;const resize=n=>{width=Math.max(180,Math.min(340,n));document.documentElement.style.setProperty('--nav-width',width+'px');res.setAttribute('aria-valuenow',String(width));};res.onpointerdown=ev=>{if(ev.button!==0)return;drag=true;res.setPointerCapture(ev.pointerId);};res.onpointermove=ev=>{if(drag)resize(ev.clientX);};res.onpointerup=res.onpointercancel=()=>drag=false;res.onkeydown=ev=>{if(['Home','End','ArrowLeft','ArrowRight'].includes(ev.key)){ev.preventDefault();resize(ev.key==='Home'?180:ev.key==='End'?340:width+(ev.key==='ArrowLeft'?-10:10));}};
 persist();DemoStore.attach('emergency',()=>({state,registry,occupiedBeds}),data=>{state=data.state;DemoStore.replace(registry,data.registry);occupiedBeds=data.occupiedBeds||[];});
 render();syncNav();
})();




