/* Standalone UX demo. No API, production storage, real signatures or payments. */
(() => {
 'use strict';
 const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>'₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
 const badge=(s,c='')=>`<span class="badge ${c}">${esc(s)}</span>`;
 const button=(label,action,id='',primary=false,disabled=false)=>`<button ${primary?'class="primary"':''} data-action="${action}" data-id="${esc(id)}" ${disabled?'disabled':''}>${esc(label)}</button>`;
 const link=(label,url)=>`<a class="record-link" href="#${url}">${esc(label)}</a>`;
 const table=(heads,rows)=>`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable data table"><table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map((c,i)=>`<td><span class="mobile-cell-label">${esc(heads[i]||'Action')}</span><div class="cell-value">${c}</div></td>`).join('')}</tr>`).join(''):`<tr class="empty-row"><td colspan="${heads.length}"><div class="empty">No matching records. Try another search or filter.</div></td></tr>`}</tbody></table></div>`;
 const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}><span class="error" id="error-${name}"></span></label>`;
 const area=(name,label,value='',required=true)=>`<label class="wide">${label}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea><span class="error" id="error-${name}"></span></label>`;
 const select=(name,label,opts,current='',required=true)=>`<label>${label}<select name="${name}" ${required?'required':''}>${opts.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`;}).join('')}</select><span class="error" id="error-${name}"></span></label>`;
 const card=(title,html)=>`<section class="card"><h2>${title}</h2>${html}</section>`;
 const patients=[{id:'PAT-1042',name:'Ravi Kumar',age:'45Y · Male',allergy:'Penicillin — rash'},{id:'PAT-1089',name:'Meera Devi',age:'62Y · Female',allergy:'No known allergies (recorded)'},{id:'PAT-1120',name:'Lakshmi Iyer',age:'58Y · Female',allergy:'Not recorded'},{id:'PAT-1103',name:'Arjun Patel',age:'34Y · Male',allergy:'Not recorded'},{id:'PAT-1195',name:'Sana Ali',age:'29Y · Female',allergy:'No known allergies (recorded)'}];
 const doctors=['Dr. Priya Sharma','Dr. Amit Joshi'];
 const beds=[{id:'A-101-1',ward:'General ward A',room:'101',status:'Occupied'},{id:'A-101-2',ward:'General ward A',room:'101',status:'Available'},{id:'A-102-1',ward:'General ward A',room:'102',status:'Occupied'},{id:'A-102-2',ward:'General ward A',room:'102',status:'Turnover'},{id:'P-201',ward:'Private ward',room:'201',status:'Occupied'},{id:'P-202',ward:'Private ward',room:'202',status:'Available'},{id:'P-203',ward:'Private ward',room:'203',status:'Maintenance'},{id:'P-204',ward:'Private ward',room:'204',status:'Available'}];
 function admission(id,patient,bed,doctor,reason,date){return {id,patient,bed,doctor,reason,date,status:'Active',notes:[],vitals:[],orders:[],meds:[],events:[],charges:[{description:'Room and board — posted stay charges',qty:1,rate:6000},{description:'Consultation — posted visit',qty:1,rate:1000}],payments:[{amount:2000,method:'Cash',reference:'DEP-1001'}],insurance:null,summary:{diagnosis:'',course:'',treatment:'',advice:'',followup:''},signed:false,handover:false,dischargePlanned:false};}
 const admissions=[admission('IPD-2026-0041','PAT-1042','A-101-1',doctors[0],'Observation and continued inpatient care','15 Sep 2026, 14:20'),admission('IPD-2026-0042','PAT-1089','A-102-1',doctors[1],'Post-procedure recovery','16 Sep 2026, 10:15'),admission('IPD-2026-0043','PAT-1120','P-201',doctors[0],'Planned discharge review','14 Sep 2026, 09:00')];
 admissions.forEach(a=>{a.events.push({at:a.date,actor:'Admissions desk',text:`Admitted to ${a.bed}`});a.vitals.push({at:'17 Sep 2026, 08:00',bp:'124/78',pulse:'76',spo2:'98',temp:'36.8',note:'Routine observation',actor:'Ward nurse'});a.notes.push({at:'17 Sep 2026, 08:15',actor:'Ward nurse',kind:'Handover',text:'Morning handover completed. Continue the documented care plan.'});});
 admissions[0].orders=[{id:'ORD-101',name:'CBC',type:'Investigation',status:'Result available',detail:'Sample report attached for UX preview.',reviewed:false},{id:'ORD-102',name:'Physiotherapy assessment',type:'Referral',status:'Requested',detail:'Review requested by treating team.'}];
 admissions[0].meds=[{id:'MED-101',name:'Paracetamol',dose:'500 mg',route:'Oral',frequency:'As ordered',time:'17 Sep, 12:00',status:'Due',instruction:'Fictional existing medication order. Verify against the signed chart.'}];
 admissions[1].insurance={insurer:'Example Health Insurance',policy:'MOCK-20041',requested:25000,approved:0,preauth:'Submitted',claim:'Not started',notes:'Awaiting insurer response (mock)'};
 admissions[2].summary={diagnosis:'Recorded diagnosis — demonstration only',course:'Observation completed; treating team has documented readiness.',treatment:'See reconciled medication plan in the discharge record.',advice:'Written discharge instructions reviewed with the patient.',followup:'Review with the treating team as documented.'};admissions[2].signed=true;admissions[2].signedAt='17 Sep 2026, 09:00';admissions[2].dischargePlanned=true;
 // Import completed session-local Emergency handovers. Ordinary seeded charts are unchanged.
 const emergencyImportIssues=[];
 try {
  const emergency=JSON.parse(sessionStorage.getItem('hospitall-emergency-ux-v1')||'null');
  if(emergency?.version===1&&Array.isArray(emergency.encounters))for(const e of emergency.encounters){
   const d=e.disposition;if(!e.closed||d?.type!=='Admission'||d.status!=='Handover completed')continue;
   if(!e.patient?.id||!e.patient?.name||!Array.isArray(e.meds)||!Array.isArray(e.orders)||!Array.isArray(e.observations))continue;
   const id='IPD-'+e.id;if(admissions.some(a=>a.id===id))continue;
   const bed=beds.find(b=>b.id===d.bed);
   if(!bed||bed.status!=='Available'||admissions.some(a=>a.patient===e.patient.id&&a.status==='Active')){emergencyImportIssues.push(e.id+': handover could not be imported because the bed or patient already has an active admission.');continue;}
   let p=patients.find(p=>p.id===e.patient.id);if(!p){p={id:e.patient.id,name:e.patient.name,age:e.patient.age||'Not recorded',allergy:e.patient.allergy||'Unknown'};patients.push(p);}else p.allergy=e.patient.allergy||p.allergy;
   const a=admission(id,p.id,bed.id,d.doctor,d.reason,d.completedAt);a.charges=[];a.payments=[];a.emergencySource=e.id;
   a.notes=[{at:d.completedAt,actor:d.receiver,kind:'Emergency handover',text:['Emergency encounter: '+e.id,'Previous temporary identity: '+(e.patient.previousTemporaryId||'None'),'Complaint: '+e.reason,'Assessment: '+e.assessment,'Impression: '+e.impression,'Allergies: '+e.patient.allergy,'Medication events: '+(e.meds.map(m=>`${m.name} · ${m.dose} · ${m.route} · ${m.status}${m.note?' · '+m.note:''}`).join('; ')||'None recorded'),'Pending results: '+(e.orders.filter(o=>o.status!=='Reviewed').map(o=>o.name+' · '+o.status).join('; ')||'None'),'Receiving team: '+d.receiver].join('\n')}];
   a.vitals=e.observations.map(o=>({at:o.at,actor:o.actor,bp:o.bp||'',pulse:o.pulse||'',spo2:o.spo2||'',temp:o.temp||'',note:o.text}));
   a.orders=e.orders.map(o=>({id:'ER-'+o.id,name:o.name,type:'Investigation',status:o.status==='Reviewed'?'Result available':o.status,detail:[o.result,o.review].filter(Boolean).join('\n')||'Result pending from Emergency.',reviewed:o.status==='Reviewed'}));
   a.meds=e.meds.filter(m=>m.status==='Given'||m.status==='Held').map(m=>({id:'ER-'+m.id,name:m.name,dose:m.dose,route:m.route,frequency:'Emergency event — historical',time:m.at,status:m.status,instruction:m.note||'Recorded in Emergency; not a new inpatient dose.'}));
   a.events=[{at:d.completedAt,actor:d.receiver,text:'Received from '+e.id+' after physical handover to '+bed.id+'.'},...e.events];admissions.push(a);bed.status='Occupied';
  }
 }catch(_){emergencyImportIssues.push('Emergency handover data could not be read. Existing Inpatient demo records remain available.');}
 let role='Admissions desk', seq=44, activeScreen='dashboard', patientTab='overview', currentId=admissions[0].id, draft={step:1,patient:'',doctor:doctors[0],reason:'',bed:''}, filters={search:'',ward:'All wards',status:'Active'}, bedFilter={ward:'All wards',status:'All statuses'}, formDirty=false, routeBefore='', dialogReturn=null;
 const activity=[{at:'17 Sep 2026, 09:00',actor:'Treating doctor',text:'IPD-2026-0043: discharge summary signed (mock).'}];
 const person=a=>patients.find(p=>p.id===a.patient), current=()=>admissions.find(a=>a.id===currentId), live=a=>a.status==='Active';
 const can=r=>role===r, clinical=()=>['Treating doctor','Ward nurse'].includes(role), desk=()=>can('Admissions desk'), billing=()=>can('Billing desk');
 const when=()=>`17 Sep 2026, ${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`;
 function log(a,text){const e={at:when(),actor:role,text};if(a)a.events.unshift(e);activity.unshift({...e,text:a?`${a.id}: ${text}`:text});}
 function tell(text){$('#notice').textContent=text;}
 function total(a){const charges=a.charges.reduce((n,c)=>n+c.qty*c.rate,0),paid=a.payments.reduce((n,p)=>n+p.amount,0);return {charges,paid,balance:charges-paid};}
 function heading(title,sub,actions=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;}
 function timeline(events){return `<ul class="timeline">${events.map(e=>`<li><p class="read-text">${esc(e.text)}</p><small>${esc(e.at)} · ${esc(e.actor)}</small></li>`).join('')||'<li>No activity yet.</li>'}</ul>`;}
 const wardOptions=['All wards',...new Set(beds.map(b=>b.ward))];
 const svg=p=>`<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${p}"/></svg>`;
 const nav=[['dashboard','Overview','M3 10 12 3l9 7v11h-6v-7H9v7H3Z'],['beds','Bed board','M3 18V6m0 8h18v6m-18-3h18M6 14V9h6v5m0-5h6a3 3 0 0 1 3 3v2'],['admissions','Admissions','M8 3h8v4H8ZM6 5H4v16h16V5h-2M8 11h8m-8 5h5'],['discharges','Discharge worklist','M4 3h12v18H4Zm6 9h12m-4-4 4 4-4 4'],['billing','Billing & insurance','M3 5h18v14H3ZM3 10h18m-5 5h3'],['activity','Activity','M3 12h4l3-8 4 16 3-8h4']];
 $('#nav-links').innerHTML=nav.map(([id,label,path])=>`<a href="#${id}" title="${label}" data-nav="${id}">${svg(path)}<span class="nav-label">${label}</span></a>`).join('');
 function attentionItems(active){const items=[];for(const a of active){let task='';let tab='overview';if(desk()){if(a.signed&&a.handover){task='Doctor signoff and nursing handover complete · discharge can be completed';tab='discharge';}else if(a.signed){task='Discharge awaiting nursing handover';tab='discharge';}}else if(can('Ward nurse')){if(a.signed&&!a.handover){task='Signed summary · nursing handover pending';tab='discharge';}else if(a.meds.some(m=>m.status==='Due')){task='Medication outcome due';tab='medications';}}else if(can('Treating doctor')){if(a.orders.some(o=>o.status==='Result available'&&!o.reviewed)){task='Result available · doctor review pending';tab='orders';}else if(a.dischargePlanned&&!a.signed){task='Discharge summary draft awaiting signoff';tab='discharge';}}else if(billing()){if(a.insurance&&['Submitted','Query'].includes(a.insurance.preauth)){task='Insurance preauthorization follow-up';tab='billing';}else if(total(a).balance>0){task='Outstanding balance '+money(total(a).balance);tab='billing';}}if(task)items.push({title:person(a).name,task,url:`patient/${a.id}/${tab}`});}if(desk())for(const b of beds.filter(b=>b.status==='Turnover'))items.push({title:b.id,task:'Bed turnover · readiness confirmation pending',url:'beds'});return items;}
 function dashboard(){const active=admissions.filter(live),available=beds.filter(b=>b.status==='Available').length,tasks=attentionItems(active);return heading('Inpatient overview','CityCare Hospital · A shared view of admissions, beds and care handoffs.',desk()?button('New admission','admit','',true):'')+`<div class="stats"><div class="stat"><strong>${active.length}</strong><span>Active admissions</span></div><div class="stat"><strong>${available}</strong><span>Available beds</span></div><div class="stat"><strong>${active.filter(a=>a.dischargePlanned).length}</strong><span>Discharge planned</span></div><div class="stat"><strong>${beds.filter(b=>b.status==='Turnover').length}</strong><span>Beds in turnover</span></div></div><div class="grid">${card('Needs attention',tasks.map(t=>`<div class="list-row"><div><strong>${esc(t.title)}</strong><p class="muted">${esc(t.task)}</p></div>${link(t.url==='beds'?'Open bed board':'Open admission',t.url)}</div>`).join('')||'<p>No tasks requiring attention for this preview role.</p>')}${card('Ward occupancy',wardOptions.slice(1).map(w=>{const wb=beds.filter(b=>b.ward===w);return `<div class="list-row"><div><strong>${w}</strong><p class="muted">${wb.filter(b=>b.status==='Occupied').length} occupied of ${wb.length} beds</p></div>${badge(wb.filter(b=>b.status==='Available').length+' available','good')}</div>`;}).join('')+'<p class="footnote">Turnover and maintenance beds cannot be assigned.</p>')}</div>`;}
 function bedBoard(){const list=beds.filter(b=>(bedFilter.ward==='All wards'||b.ward===bedFilter.ward)&&(bedFilter.status==='All statuses'||b.status===bedFilter.status));return heading('Bed board','Assign only available beds. Transfer and discharge send the previous bed to turnover.',desk()?button('New admission','admit','',true):'')+`<div class="filters">${select('bedward','Ward',wardOptions,bedFilter.ward,false)}${select('bedstatus','Bed status',['All statuses','Available','Occupied','Turnover','Maintenance'],bedFilter.status,false)}</div><div class="beds">${list.map(b=>{const a=admissions.find(a=>live(a)&&a.bed===b.id);return `<section class="card bed ${b.status.toLowerCase()}"><div class="actions"><h2>${b.id}</h2>${badge(b.status,b.status==='Available'?'good':b.status==='Occupied'?'':'warn')}</div><p class="muted">${b.ward} · Room ${b.room}</p><p><strong>${a?esc(person(a).name):b.status==='Available'?'Ready for admission':b.status==='Turnover'?'Cleaning / readiness check pending':'Unavailable for assignment'}</strong></p><div class="actions">${a?link('Open admission',`patient/${a.id}/overview`):desk()?b.status==='Available'?button('Assign bed','admit',b.id)+button('Mark maintenance','bed-maintenance',b.id):button('Mark ready','bed-ready',b.id):'<small>Admissions desk manages readiness.</small>'}</div></section>`;}).join('')||'<div class="empty">No beds match these filters.</div>'}</div>`;}
 function admissionRows(list,actionTab='overview'){return list.map(a=>{const p=person(a);return [link(p.name,`patient/${a.id}/${actionTab}`)+`<small>${p.id} · ${p.age}</small>`,`${a.id}<small>${a.date}</small>`,`${a.bed}<small>${beds.find(b=>b.id===a.bed)?.ward||''}</small>`,esc(a.doctor),badge(a.status,a.status==='Discharged'?'good':''),link('Open',`patient/${a.id}/${actionTab}`)];});}
 function admissionsPage(){const q=filters.search.toLowerCase();const list=admissions.filter(a=>(filters.status==='All statuses'||a.status===filters.status)&&(filters.ward==='All wards'||beds.find(b=>b.id===a.bed)?.ward===filters.ward)&&[person(a).name,a.patient,a.id,a.bed].join(' ').toLowerCase().includes(q));return heading('Admissions','Find a patient by name, patient ID, admission number or bed.',desk()?button('New admission','admit','',true):'')+`<div class="filters"><label class="search">Search admissions<input name="admissionSearch" value="${esc(filters.search)}" placeholder="Name, patient ID, admission or bed"></label>${select('ward','Ward',wardOptions,filters.ward,false)}${select('status','Status',['All statuses','Active','Discharged'],filters.status,false)}</div>`+table(['Patient','Admission','Bed','Treating doctor','Status',''],admissionRows(list));}
 function newAdmission(){if(!desk())return heading('New admission','Switch the preview persona to Admissions desk to admit a patient.');const p=patients.find(p=>p.id===draft.patient);const options=patients.filter(p=>!admissions.some(a=>live(a)&&a.patient===p.id));return heading('New admission','Select an existing patient, document the admission and confirm an available bed.',button('Cancel','cancel-admission'))+`<div class="steps"><span class="${draft.step===1?'active':''}">1 · Patient & details</span><span class="${draft.step===2?'active':''}">2 · Bed assignment</span><span class="${draft.step===3?'active':''}">3 · Review & admit</span></div>`+card(draft.step===1?'Patient & admission details':draft.step===2?'Choose an available bed':'Review admission',`<form id="admit-form" novalidate><div class="errors"></div>${draft.step===1?`<label>Find patient<input name="patientSearch" placeholder="Search name or patient ID"></label><div class="fields">${select('patient','Patient *',[['','Select a patient'],...options.map(p=>[p.id,`${p.name} · ${p.id} · ${p.age}`])],draft.patient)}${select('doctor','Treating doctor *',doctors,draft.doctor)}${area('reason','Admission reason *',draft.reason)}</div><p class="muted">Patients with an active admission are excluded. New patient registration belongs to Reception.</p>`:draft.step===2?`<div class="banner"><strong>${esc(p?.name)}</strong> · ${esc(draft.patient)} · ${esc(draft.doctor)}</div><div class="fields">${select('bed','Available bed *',[['','Select a bed'],...beds.filter(b=>b.status==='Available').map(b=>[b.id,`${b.id} · ${b.ward} · Room ${b.room}`])],draft.bed)}</div><p class="muted">Occupancy is checked again on confirmation.</p>`:`<div class="summary-row"><span>Patient</span><strong>${esc(p?.name)} · ${esc(p?.id)}</strong></div><div class="summary-row"><span>Treating doctor</span><strong>${esc(draft.doctor)}</strong></div><div class="summary-row"><span>Bed</span><strong>${esc(draft.bed)}</strong></div><div class="summary-row"><span>Admission reason</span><span class="read-text">${esc(draft.reason)}</span></div><label class="check"><input type="checkbox" name="identity" required>Patient identity and admission details checked *</label>`}<div class="actions" style="margin-top:24px">${draft.step>1?'<button type="button" data-action="admit-back">Back</button>':''}<button class="primary" type="submit">${draft.step===3?'Confirm admission':'Continue'}</button></div></form>`);}
 const tabs=[['overview','Overview'],['observations','Observations'],['notes','Notes'],['orders','Orders & reports'],['medications','Medication chart'],['billing','Billing & insurance'],['discharge','Discharge'],['history','History']];
 function patientPage(){const a=current();if(!a)return heading('Admission not found','Return to Admissions to choose a record.');const p=person(a);return heading('Admission workspace',`${a.id} · Admitted ${a.date}`,`${link('All admissions','admissions')}${desk()&&live(a)?button('Transfer bed','transfer',a.id):''}`)+`<section class="patient-banner" aria-label="Patient identity"><div><h2>${esc(p.name)}</h2><p>${p.id} · ${p.age}</p></div><div><small>LOCATION & TEAM</small><p><strong>${a.bed}</strong> · ${esc(a.doctor)}</p></div><div><small>ALLERGIES</small><p><strong>${esc(p.allergy)}</strong></p></div><div>${badge(a.status,live(a)?'':'good')}</div></section>${!live(a)?'<div class="banner">Discharged admission · The clinical chart is read-only. Billing and insurance follow-up remain available to the Billing desk.</div>':''}<nav class="tabs" aria-label="Admission sections">${tabs.map(([id,label])=>`<a href="#patient/${a.id}/${id}" class="${patientTab===id?'active':''}" ${patientTab===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${a.emergencySource?card('Emergency handover',`<p>Received from ${esc(a.emergencySource)}. Emergency medication events are historical; new inpatient doses require a separate order.</p><p><a href="emergency.html#patient/${encodeURIComponent(a.emergencySource)}/next">View closed emergency encounter</a></p>`):''}${patientContent(a)}`;}
 function patientContent(a){const edit=live(a);switch(patientTab){case'overview':return `<div class="grid">${card('Admission context',`<p class="read-text">${esc(a.reason)}</p><div class="summary-row"><span>Treating doctor</span><strong>${esc(a.doctor)}</strong></div><div class="summary-row"><span>Discharge summary</span>${badge(a.signed?'Signed':'Not signed',a.signed?'good':'warn')}</div><div class="summary-row"><span>Nursing handover</span>${badge(a.handover?'Complete':'Pending',a.handover?'good':'warn')}</div>`)}${card('Latest observations',a.vitals.length?`<p><strong>BP ${esc(a.vitals[0].bp)} mmHg · Pulse ${esc(a.vitals[0].pulse)}/min</strong></p><p>SpO₂ ${esc(a.vitals[0].spo2)}% · Temperature ${esc(a.vitals[0].temp)}°C</p><p class="muted">${a.vitals[0].at} · ${a.vitals[0].actor}</p><p class="footnote">Measurements shown as recorded; no automated clinical interpretation.</p>`:'<p>No observations recorded for this admission.</p>')}${card('Care activity',`<div class="summary-row"><span>Orders</span>${a.orders.length}</div><div class="summary-row"><span>Medication entries</span>${a.meds.length}</div><div class="summary-row"><span>Unreviewed reports</span>${a.orders.filter(o=>o.status==='Result available'&&!o.reviewed).length}</div>`)}${card('Recent history',timeline(a.events.slice(0,3)))}</div>`;
 case'observations':return card('Observation sheet',`<div class="actions">${clinical()&&edit?button('Record observations','vitals',a.id,true):'<p class="muted">Ward nurse or treating doctor records observations.</p>'}</div><br>`+table(['Recorded','BP · mmHg','Pulse /min','SpO₂ %','Temp °C','Note'],a.vitals.map(v=>[`${esc(v.at)}<small>${esc(v.actor)}</small>`,esc(v.bp),esc(v.pulse),esc(v.spo2),esc(v.temp),esc(v.note)])));
 case'notes':return card('Clinical & nursing notes',`<div class="actions">${clinical()&&edit?button('Add note','note',a.id,true):'<p class="muted">Clinical notes are recorded by the care team.</p>'}</div>`+timeline(a.notes.map(n=>({...n,text:`${n.kind}: ${n.text}`}))));
 case'orders':return card('Orders & reports',`<div class="actions">${can('Treating doctor')&&edit?button('Add order','order',a.id,true):'<p class="muted">Treating doctor places orders; the care team can view attached reports.</p>'}</div><br>`+table(['Order','Type','Status','Details','Action'],a.orders.map(o=>[esc(o.name),esc(o.type),badge(o.reviewed?'Reviewed':o.status,o.reviewed?'good':''),esc(o.detail),o.status==='Result available'?button('View report','report',o.id):edit&&clinical()?button('Update status','order-status',o.id):'—'])));
 case'medications':return card('Medication administration record',`<p class="toolbar-note">Fictional orders for workflow review. No dosing recommendations or automated scheduling. Recorded outcomes cannot be overwritten in this prototype.</p><div class="actions">${can('Treating doctor')&&edit?button('Add medication order','med-order',a.id,true):''}</div><br>`+table(['Medication / instruction','Ordered dose','Scheduled','Outcome','Action'],a.meds.map(m=>[`${esc(m.name)}<small>${esc(m.instruction)}</small>`,`${esc(m.dose)}<small>${esc(m.route)} · ${esc(m.frequency)}</small>`,esc(m.time),badge(m.status,m.status==='Given'?'good':m.status==='Due'?'warn':'')+(m.reason?`<small>${esc(m.reason)}</small>`:'')+(m.recorded?`<small>${esc(m.recorded)} · Ward nurse</small>`:''),m.status==='Due'&&can('Ward nurse')&&edit?button('Record outcome','mar',m.id):'—'])));
 case'billing':return billContent(a);
 case'discharge':return dischargeContent(a);
 case'history':return card('Admission history',timeline(a.events));default:return ''}}
 function billContent(a){const t=total(a);return `<div class="grid">${card('Billing summary',`<div class="summary-row"><span>Posted charges</span><strong>${money(t.charges)}</strong></div><div class="summary-row"><span>Payments received</span><strong>${money(t.paid)}</strong></div><div class="summary-row total"><span>Outstanding</span><span>${money(t.balance)}</span></div><p class="footnote">Insurance authorization is not a received payment. No automatic bed-day calculation in this demo.</p><div class="actions" style="margin-top:16px">${billing()?button('Add charge','charge',a.id)+button('Record payment','payment',a.id,true,t.balance<=0):'<small>Billing desk manages charges and payments.</small>'}</div>`)}${card('Insurance case',a.insurance?`<p><strong>${esc(a.insurance.insurer)}</strong></p><p class="muted">Policy ${esc(a.insurance.policy)}</p><div class="summary-row"><span>Preauthorization</span>${badge(a.insurance.preauth)}</div><div class="summary-row"><span>Requested / approved</span><span>${money(a.insurance.requested)} / ${money(a.insurance.approved)}</span></div><div class="summary-row"><span>Claim</span>${badge(a.insurance.claim)}</div><p class="read-text muted">${esc(a.insurance.notes)}</p><div class="actions" style="margin-top:16px">${billing()?button('Update insurance','insurance',a.id):''}</div>`:`<p>Self-pay · No insurance case recorded.</p><div class="actions" style="margin-top:16px">${billing()?button('Add insurance case','insurance',a.id):''}</div>`)}</div><br>${card('Itemized charges',table(['Description','Quantity','Unit amount','Amount'],a.charges.map(c=>[esc(c.description),c.qty,money(c.rate),money(c.qty*c.rate)])))}${card('Payment history',table(['Receipt/reference','Method','Amount'],a.payments.map(p=>[esc(p.reference),esc(p.method),money(p.amount)])))}`;}
 function dischargeContent(a){const t=total(a);return `<div class="banner">Clinical signoff, nursing handover and administrative completion are separate steps. All signatures and confirmations here are simulated.</div><div class="grid">${card('Discharge readiness',`<div class="summary-row"><span>1 · Doctor summary</span>${badge(a.signed?'Signed':'Pending',a.signed?'good':'warn')}</div><div class="summary-row"><span>2 · Nursing handover</span>${badge(a.handover?'Complete':'Pending',a.handover?'good':'warn')}</div><div class="summary-row"><span>3 · Administration</span>${badge(live(a)?'Not completed':'Completed',live(a)?'warn':'good')}</div><div class="summary-row"><span>Financial balance</span><strong>${money(t.balance)}</strong></div><div class="actions" style="margin-top:18px">${live(a)&&can('Treating doctor')?a.signed?button('Reopen signoff','revoke',a.id):button('Edit summary','summary',a.id)+button('Review & sign','sign',a.id,true):''}${live(a)&&can('Ward nurse')&&!a.handover?button('Complete handover','handover',a.id,true,!a.signed):''}${live(a)&&desk()?button('Complete discharge','discharge',a.id,true,!a.signed||!a.handover):''}${!live(a)?button('Print summary','print'):''}</div>${(desk()||can('Ward nurse'))&&live(a)&&(!a.signed||!a.handover)?'<p class="footnote">Nursing handover unlocks after doctor signoff. Administrative completion follows nursing handover. Preview those roles to complete the sample flow.</p>':''}`)}${card('Discharge summary',Object.entries({diagnosis:'Diagnosis',course:'Clinical course',treatment:'Treatment / medication reconciliation',advice:'Discharge advice',followup:'Follow-up'}).map(([k,label])=>`<h3>${label}</h3><p class="read-text" style="margin-bottom:16px">${esc(a.summary[k]||'Not documented')}</p>`).join('')+`<small>${a.signed?'Signed (mock) by '+esc(a.doctor)+' · '+a.signedAt:'Draft · Not signed'}</small>`)}</div>`;}
 function discharges(){return heading('Discharge worklist','Track clinical signoff, nursing handover and completion independently.')+table(['Patient','Bed','Summary','Nursing handover','Status','Action'],admissions.map(a=>[link(person(a).name,`patient/${a.id}/discharge`),a.bed,badge(a.signed?'Signed':'Pending',a.signed?'good':'warn'),badge(a.handover?'Complete':'Pending',a.handover?'good':'warn'),badge(a.status),link('Review discharge',`patient/${a.id}/discharge`)]));}
 function billingPage(){return heading('Billing & insurance','Posted charges, recorded receipts and insurer status for each stay.')+table(['Patient / admission','Charges','Received','Outstanding','Insurance','Action'],admissions.map(a=>{const t=total(a);return [link(person(a).name,`patient/${a.id}/billing`)+`<small>${a.id}</small>`,money(t.charges),money(t.paid),money(t.balance),a.insurance?badge(a.insurance.preauth):'Self-pay',link('Open account',`patient/${a.id}/billing`)];}));}
 function render(focus=true){const pieces=location.hash.slice(1).split('/');activeScreen=pieces[0]||'dashboard';if(activeScreen==='patient'){currentId=pieces[1];patientTab=tabs.some(t=>t[0]===pieces[2])?pieces[2]:'overview';}const screens={dashboard,beds:bedBoard,admissions:admissionsPage,admit:newAdmission,patient:patientPage,discharges,billing:billingPage,activity:()=>heading('Activity','A local audit trail for this demo session.')+card('Recent actions',timeline(activity))};if(!screens[activeScreen]){location.hash='dashboard';return;}$('#content').innerHTML=screens[activeScreen]();document.querySelectorAll('[data-nav]').forEach(n=>{const match=n.dataset.nav===(['patient','admit'].includes(activeScreen)?'admissions':activeScreen);n.classList.toggle('active',match);if(match)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});formDirty=false;if(focus){$('#content').focus({preventScroll:true});window.scrollTo(0,0);}routeBefore=location.hash;}
 const admissionDirty=()=>activeScreen==='admit'&&(formDirty||!!draft.patient||!!draft.reason);
 function closeDialog(){const d=$('#dialog');d.close();d.innerHTML='';formDirty=false;dialogReturn?.focus?.();}
 function modal(title,body,onSubmit,submit='Save',warning=''){dialogReturn=document.activeElement;const d=$('#dialog');d.innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">${title}</h2><button type="button" data-action="close" aria-label="Close dialog">×</button></div>${warning?`<div class="banner warning">${warning}</div>`:''}<form id="modal-form" novalidate><div class="errors"></div>${body}<div class="actions"><button type="button" data-action="close">Cancel</button>${onSubmit?`<button type="submit" class="primary">${submit}</button>`:''}</div></form>`;d.showModal();formDirty=false;$('#modal-form').onsubmit=e=>{e.preventDefault();if(validate(e.target))onSubmit(new FormData(e.target),e.target);};}
 function errors(form,list){form.querySelector('.errors').innerHTML=list.length?`<div class="error-summary" role="alert" tabindex="-1">${list.map(e=>`<p data-error-name="${esc(e.name||'')}">${esc(e.text)}</p>`).join('')}</div>`:'';form.querySelectorAll('[aria-invalid]').forEach(e=>e.removeAttribute('aria-invalid'));form.querySelectorAll('.error').forEach(e=>e.textContent='');list.forEach(e=>{const el=form.elements[e.name];if(el){el.setAttribute('aria-invalid','true');const msg=form.querySelector('#error-'+e.name);if(msg){msg.textContent=e.text;el.setAttribute('aria-describedby',msg.id);}}});if(list.length)form.querySelector('.error-summary').focus();return !list.length;}
 function validate(form){const list=[];for(const e of form.elements){if(!e.name)continue;const label=e.closest('label')?.childNodes[0]?.textContent.trim().replace('*','')||e.name;if(e.required&&(e.type==='checkbox'?!e.checked:!e.value.trim()))list.push({name:e.name,text:`${label} is required.`});else if(e.type==='number'&&e.value&&(!Number.isFinite(+e.value)||!e.validity.valid))list.push({name:e.name,text:`Enter a valid ${label.toLowerCase()}${e.min&&e.max?' (between '+e.min+' and '+e.max+')':e.min?' (minimum '+e.min+')':''}.`});}return errors(form,list);}
 function saveDone(a,text){log(a,text);closeDialog();render(false);tell(text+' · Saved in this demo.');}
 function availableBeds(){return beds.filter(b=>b.status==='Available').map(b=>[b.id,`${b.id} · ${b.ward}`]);}
 function openAction(action,id){const a=current(), edit=a&&live(a);const findOrder=()=>a.orders.find(o=>o.id===id);switch(action){
 case'reset':modal('Reset demo?', '<p>All changes in this Inpatient demo will be cleared. Other modules are unaffected.</p>',()=>location.reload(),'Reset demo');break;
 case'close':if(formDirty){if(!confirm('Discard unsaved changes in this form?'))return;}closeDialog();break;
 case'admit':if(!desk())return;draft={step:1,patient:'',doctor:doctors[0],reason:'',bed:id||''};location.hash='admit';break;
 case'cancel-admission':if((draft.patient||draft.reason||formDirty)&&!confirm('Discard this unsaved admission?'))return;formDirty=false;draft={step:1};location.hash='admissions';break;
 case'admit-back':{const f=$('#admit-form');if(draft.step===2)draft.bed=f.elements.bed.value;draft.step--;render();break;}
 case'bed-ready':case'bed-maintenance':{if(!desk())return;const b=beds.find(b=>b.id===id);if(!b||b.status==='Occupied')return;const ready=action==='bed-ready';modal(ready?'Mark bed ready':'Mark bed unavailable',`<p><strong>${b.id}</strong> · ${b.ward}</p><div class="fields">${area('reason',ready?'Readiness / cleaning confirmation *':'Maintenance reason *')}</div>`,f=>{b.status=ready?'Available':'Maintenance';saveDone(null,`${b.id}: ${b.status} — ${f.get('reason')}`);},ready?'Confirm ready':'Mark maintenance');break;}
 case'transfer':if(!desk()||!edit)return;modal('Transfer bed',`<p>${esc(person(a).name)} · ${a.id}<br>Current bed: <strong>${a.bed}</strong></p><div class="fields">${select('bed','Destination bed *',[['','Select available bed'],...availableBeds()])}${area('reason','Transfer reason *')}</div>`,(f,form)=>{const b=beds.find(b=>b.id===f.get('bed'));if(!b||b.status!=='Available')return errors(form,[{name:'bed',text:'Choose an available bed.'}]);const old=a.bed;beds.find(b=>b.id===old).status='Turnover';b.status='Occupied';a.bed=b.id;saveDone(a,`Transferred ${old} → ${b.id}: ${f.get('reason')}`);},'Confirm transfer','The previous bed goes to turnover until readiness is confirmed.');break;
 case'vitals':if(!clinical()||!edit)return;modal('Record observations',`<p>${esc(person(a).name)} · ${a.id}</p><div class="fields">${field('sys','Systolic BP · mmHg *','','number','required min="1" max="400"')}${field('dia','Diastolic BP · mmHg *','','number','required min="1" max="300"')}${field('pulse','Pulse · /min *','','number','required min="1" max="400"')}${field('spo2','SpO₂ · % *','','number','required min="1" max="100"')}${field('temp','Temperature · °C *','','number','required min="1" max="60" step="0.1"')}${field('time','Observed at *','2026-09-17T10:00','datetime-local','required')}${area('note','Observation note','',false)}</div>`,f=>{a.vitals.unshift({at:f.get('time').replace('T',' '),bp:f.get('sys')+'/'+f.get('dia'),pulse:f.get('pulse'),spo2:f.get('spo2'),temp:f.get('temp'),note:f.get('note'),actor:role});saveDone(a,'Observations recorded');});break;
 case'note':if(!clinical()||!edit)return;modal('Add care note',`<p>${esc(person(a).name)} · ${a.id}</p><div class="fields">${select('kind','Note type',['Progress','Handover','Procedure'])}${area('text','Note *')}</div>`,f=>{a.notes.unshift({at:when(),actor:role,kind:f.get('kind'),text:f.get('text')});saveDone(a,f.get('kind')+' note recorded');});break;
 case'order':if(!can('Treating doctor')||!edit)return;modal('Add inpatient order',`<div class="fields">${select('type','Order type',['Investigation','Referral','Procedure'])}${field('name','Order name *','','text','required')}${area('detail','Instructions *')}</div>`,f=>{a.orders.unshift({id:'ORD-'+Date.now(),name:f.get('name'),type:f.get('type'),status:'Requested',detail:f.get('detail')});saveDone(a,'Order requested: '+f.get('name'));},'Place mock order');break;
 case'order-status':{if(!clinical()||!edit)return;const o=findOrder();if(!o)return;modal('Update order',`<p>${esc(o.name)} · ${esc(person(a).name)}</p><div class="fields">${select('status','Status',['Requested','In progress','Result available','Cancelled'],o.status)}${area('note','Update reason / report reference *')}</div>`,f=>{o.status=f.get('status');o.detail=f.get('note');o.reviewed=false;saveDone(a,'Order '+o.name+': '+o.status);},'Save update','“Result available” attaches a labelled sample report in this demo. No real report is uploaded.');break;}
 case'report':{const o=findOrder();if(!o)return;modal('Report preview',`<div class="banner">Sample report · UX illustration only · No clinical interpretation</div><p><strong>${esc(person(a).name)}</strong> · ${a.patient}</p><p>${a.id} · ${esc(o.name)}</p><div class="card" style="margin-top:16px"><h3>Attached report</h3><p class="read-text">${esc(o.detail)}</p><p class="footnote">Sample document preview. Clinical findings intentionally omitted.</p></div><p>${o.reviewed?'Reviewed by '+esc(a.doctor):'Treating doctor review pending.'}</p>`,can('Treating doctor')&&edit&&!o.reviewed?()=>{o.reviewed=true;saveDone(a,'Report reviewed: '+o.name);}:null,'Mark reviewed');break;}
 case'med-order':if(!can('Treating doctor')||!edit)return;modal('Medication order',`<div class="banner">Manual mock order. No clinical decision support.</div><div class="fields">${field('name','Medication name *','','text','required')}${field('dose','Ordered dose and unit *','','text','required')}${select('route','Route',['Oral','IV','Topical','Other'])}${field('frequency','Frequency / schedule *','','text','required')}${field('time','Dose due at *','2026-09-17T12:00','datetime-local','required')}${area('instruction','Instructions *')}</div>`,f=>{a.meds.push({id:'MED-'+Date.now(),name:f.get('name'),dose:f.get('dose'),route:f.get('route'),frequency:f.get('frequency'),time:f.get('time').replace('T',' '),instruction:f.get('instruction'),status:'Due'});saveDone(a,'Medication order added: '+f.get('name'));},'Save mock order');break;
 case'mar':{if(!can('Ward nurse')||!edit)return;const m=a.meds.find(m=>m.id===id);if(!m||m.status!=='Due')return;modal('Record medication outcome',`<p><strong>${esc(person(a).name)}</strong> · ${a.patient}</p><p>${esc(m.name)} · ${esc(m.dose)} · ${esc(m.route)}</p><div class="fields">${select('outcome','Outcome',['Given','Held','Refused','Not available'])}${area('reason','Actual dose / outcome details *')}</div><label class="check"><input type="checkbox" name="checked" required>Patient identity and original medication order checked *</label>`,f=>{m.status=f.get('outcome');m.reason=f.get('reason');m.recorded=when();saveDone(a,`${m.name}: ${m.status} — ${m.reason}`);},'Confirm outcome');break;}
 case'charge':if(!billing()||!a)return;modal('Add posted charge',`<div class="fields">${field('description','Description *','','text','required')}${field('qty','Quantity *','1','number','required min="1" max="999"')}${field('rate','Unit amount · INR *','','number','required min="0.01" max="1000000" step="0.01"')}</div>`,f=>{a.charges.push({description:f.get('description'),qty:+f.get('qty'),rate:+f.get('rate')});saveDone(a,'Charge posted: '+f.get('description'));});break;
 case'payment':if(!billing()||!a)return;modal('Record payment',`<p>Outstanding: <strong>${money(total(a).balance)}</strong></p><div class="fields">${field('amount','Amount · INR *','','number',`required min="0.01" max="${total(a).balance}" step="0.01"`)}${select('method','Method',['Cash','UPI','Card','Bank transfer'])}${field('reference','Receipt / transaction reference *','','text','required')}</div>`,(f,form)=>{if(a.payments.some(p=>p.reference===f.get('reference')))return errors(form,[{name:'reference',text:'This receipt reference already exists.'}]);a.payments.push({amount:+f.get('amount'),method:f.get('method'),reference:f.get('reference')});saveDone(a,'Payment recorded: '+money(+f.get('amount')));},'Record mock payment','No payment is collected or processed.');break;
 case'insurance':{if(!billing()||!a)return;const i=a.insurance||{};modal('Insurance case',`<div class="fields">${field('insurer','Insurer / TPA *',i.insurer||'','text','required')}${field('policy','Policy reference *',i.policy||'','text','required')}${field('requested','Requested amount · INR *',i.requested||'','number','required min="1" max="10000000"')}${select('preauth','Preauthorization',['Draft','Submitted','Query','Approved','Partially approved','Rejected','Closed'],i.preauth||'Draft')}${field('approved','Approved amount · INR *',i.approved||0,'number','required min="0" max="10000000"')}${select('claim','Claim status',['Not started','Draft','Submitted','Query','Approved','Partially approved','Rejected','Settled','Closed'],i.claim||'Not started')}${area('notes','Response / reference notes *',i.notes||'')}</div>`,(f,form)=>{const v=Object.fromEntries(f);v.requested=+v.requested;v.approved=+v.approved;if(v.approved>v.requested)return errors(form,[{name:'approved',text:'Approved amount cannot exceed requested amount in this sample case.'}]);if(['Approved','Partially approved'].includes(v.preauth)&&!v.approved)return errors(form,[{name:'approved',text:'Enter the approved amount for this response.'}]);a.insurance=v;saveDone(a,'Insurance case updated: '+v.preauth);},'Save mock status','Status is a manually recorded sample insurer response. Nothing is submitted to an insurer.');break;}
 case'summary':if(!can('Treating doctor')||!edit||a.signed)return;modal('Discharge summary draft',`<div class="fields">${area('diagnosis','Diagnosis *',a.summary.diagnosis)}${area('course','Clinical course *',a.summary.course)}${area('treatment','Treatment / medication reconciliation *',a.summary.treatment)}${area('advice','Discharge advice *',a.summary.advice)}${area('followup','Follow-up *',a.summary.followup)}</div>`,f=>{a.summary=Object.fromEntries(f);a.handover=false;a.dischargePlanned=true;saveDone(a,'Discharge summary draft saved');},'Save draft');break;
 case'sign':if(!can('Treating doctor')||!edit||a.signed)return;if(Object.values(a.summary).some(v=>!v.trim())){tell('Complete all discharge summary sections before signing.');return openAction('summary',a.id);}modal('Sign discharge summary',`<p>${esc(person(a).name)} · ${a.id}</p><p>Signing as ${esc(a.doctor)} (preview).</p><div class="fields">${Object.entries(a.summary).map(([k,v])=>`<div class="wide"><h3>${esc({diagnosis:'Diagnosis',course:'Clinical course',treatment:'Treatment / medication reconciliation',advice:'Discharge advice',followup:'Follow-up'}[k]||k)}</h3><p class="read-text">${esc(v)}</p></div>`).join('')}</div><label class="check"><input type="checkbox" name="checked" required>Summary, medication reconciliation and follow-up reviewed *</label>`,()=>{a.signed=true;a.signedAt=when();a.dischargePlanned=true;saveDone(a,'Discharge summary signed (mock)');},'Sign mock summary');break;
 case'revoke':if(!can('Treating doctor')||!edit||!a.signed)return;modal('Reopen clinical signoff',`<p>The signed snapshot will be retained in history. A new review and nursing handover will be required before discharge.</p><div class="fields">${area('reason','Reason *')}</div>`,f=>{a.events.unshift({at:a.signedAt,actor:a.doctor,text:'Prior signed summary: '+Object.values(a.summary).join(' | ')});a.signed=false;a.handover=false;saveDone(a,'Signoff reopened: '+f.get('reason'));},'Reopen signoff');break;
 case'handover':if(!can('Ward nurse')||!edit||a.handover||!a.signed)return;modal('Complete nursing handover',`<p>${esc(person(a).name)} · ${a.id}</p><label class="check"><input name="advice" type="checkbox" required>Discharge instructions and medication plan explained *</label><label class="check"><input name="belongings" type="checkbox" required>Patient handover and belongings checked *</label><div class="fields">${area('note','Handover note *')}</div>`,f=>{a.handover=true;saveDone(a,'Nursing handover completed: '+f.get('note'));},'Complete handover');break;
 case'discharge':if(!desk()||!edit||!a.signed||!a.handover)return;modal('Complete discharge',`<p><strong>${esc(person(a).name)}</strong> · ${a.id}</p><p>Doctor summary signed · Nursing handover complete</p><p>Outstanding: <strong>${money(total(a).balance)}</strong></p><div class="fields">${area('note',total(a).balance>0?'Pending balance arrangement / billing handoff *':'Completion note *')}</div><label class="check"><input name="confirm" type="checkbox" required>Patient departure and handoff details confirmed *</label>`,f=>{a.status='Discharged';a.dischargedAt=when();beds.find(b=>b.id===a.bed).status='Turnover';saveDone(a,'Discharged; bed sent to turnover. '+f.get('note'));},'Confirm discharge','This closes the stay and makes its clinical chart read-only. The bed remains unavailable until turnover is completed.');break;
 case'print':window.print();break;
 }}
 document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)openAction(el.dataset.action,el.dataset.id);const anchor=e.target.closest('a[href^="#"]');if(anchor&&(formDirty||admissionDirty())){if(!confirm('Discard unsaved form changes?')){e.preventDefault();return;}formDirty=false;draft={step:1};}if(anchor)closeDrawer();});
 document.addEventListener('input',e=>{const form=e.target.closest('form');if(form){formDirty=true;if(e.target.getAttribute('aria-invalid')==='true'&&e.target.validity.valid&&(e.target.type==='checkbox'?e.target.checked:e.target.value.trim())){e.target.removeAttribute('aria-invalid');const msg=form.querySelector('#error-'+e.target.name);if(msg)msg.textContent='';form.querySelectorAll('[data-error-name]').forEach(row=>{if(row.dataset.errorName===e.target.name)row.remove();});const summary=form.querySelector('.error-summary');if(summary&&!summary.children.length)summary.remove();}}if(e.target.name==='patientSearch'){const q=e.target.value.toLowerCase();$('#admit-form').elements.patient.querySelectorAll('option').forEach(o=>{o.hidden=!!o.value&&!o.textContent.toLowerCase().includes(q);});}if(e.target.name==='admissionSearch'){const pos=e.target.selectionStart;filters.search=e.target.value;render(false);const input=$('[name=admissionSearch]');input.focus();input.setSelectionRange(pos,pos);}});
 document.addEventListener('change',e=>{const n=e.target.name;if(['ward','status'].includes(n)){filters[n]=e.target.value;render(false);}if(n==='bedward'||n==='bedstatus'){bedFilter[n==='bedward'?'ward':'status']=e.target.value;render(false);}});
 document.addEventListener('submit',e=>{if(e.target.id!=='admit-form')return;e.preventDefault();const f=e.target;if(!validate(f))return;const data=new FormData(f);if(draft.step===1){draft.patient=data.get('patient');draft.doctor=data.get('doctor');draft.reason=data.get('reason');}if(draft.step===2)draft.bed=data.get('bed');if(draft.step<3){draft.step++;render();return;}const b=beds.find(b=>b.id===draft.bed);if(!b||b.status!=='Available'||admissions.some(a=>live(a)&&a.patient===draft.patient))return errors(f,[{text:'Patient already admitted or bed unavailable. Go back and choose again.'}]);const a=admission('IPD-2026-00'+seq++,draft.patient,draft.bed,draft.doctor,draft.reason,when());a.charges=[];a.payments=[];admissions.unshift(a);b.status='Occupied';log(a,'Admission confirmed; bed '+b.id+' assigned');formDirty=false;draft={step:1};location.hash=`patient/${a.id}/overview`;tell('Admission confirmed. The patient and bed board are updated in this demo.');});
 $('#persona').addEventListener('change',e=>{if((formDirty||admissionDirty())&&!confirm('Discard unsaved form changes and switch preview role?')){e.target.value=role;return;}role=e.target.value;formDirty=false;if(activeScreen==='admit'){draft={step:1};location.hash='admissions';}render(false);tell('Preview role: '+role+'. Demo data is shared across these personas.');});
 $('#dialog').addEventListener('cancel',e=>{e.preventDefault();openAction('close');});
 window.addEventListener('hashchange',()=>{if(formDirty||admissionDirty()){if(!confirm('Discard unsaved form changes?')){history.replaceState(null,'',routeBefore);return;}formDirty=false;draft={step:1};}render();});
 window.addEventListener('beforeunload',e=>{if(formDirty||admissionDirty()){e.preventDefault();e.returnValue='';}});
 const shell=$('#shell'), mobile=()=>matchMedia('(max-width:700px)').matches;
 function syncNav(){const expanded=mobile()?shell.classList.contains('drawer'):!shell.classList.contains('collapsed');$('#menu').setAttribute('aria-expanded',String(expanded));$('#menu').setAttribute('aria-label',expanded?'Collapse navigation':'Expand navigation');$('main').inert=mobile()&&expanded;}
 function closeDrawer(){shell.classList.remove('drawer');syncNav();}
 function toggleNav(){if(mobile())shell.classList.toggle('drawer');else shell.classList.toggle('collapsed');syncNav();if(mobile())(shell.classList.contains('drawer')?$('.collapse'):$('#menu')).focus();}
 $('#menu').onclick=toggleNav;$('.collapse').onclick=toggleNav;$('.scrim').onclick=()=>{closeDrawer();$('#menu').focus();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&shell.classList.contains('drawer')){closeDrawer();$('#menu').focus();}});window.addEventListener('resize',syncNav);
 let width=212;try{width=Math.min(340,Math.max(180,Number(localStorage.getItem('inpatient-nav-width'))||212));}catch(_){}const res=$('.resizer');function resize(n){width=Math.min(340,Math.max(180,Math.round(n)));document.documentElement.style.setProperty('--nav-width',width+'px');res.setAttribute('aria-valuenow',width);try{localStorage.setItem('inpatient-nav-width',width);}catch(_){}}resize(width);let dragging=false;res.onpointerdown=e=>{if(e.button!==0)return;dragging=true;shell.classList.remove('collapsed');syncNav();res.setPointerCapture(e.pointerId);};res.onpointermove=e=>{if(dragging)resize(e.clientX);};res.onpointerup=res.onpointercancel=()=>dragging=false;res.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();shell.classList.remove('collapsed');syncNav();resize(e.key==='Home'?180:e.key==='End'?340:width+(e.key==='ArrowLeft'?-10:10));}};
 render(false);syncNav();if(emergencyImportIssues.length)tell(emergencyImportIssues.join(' '));
})();
