/* Nurse-only mock workflow. No Doctor state, integrations or production clinical rules. */
(() => {
  'use strict';
  const db=window.createRoleMockStore(), root=document.getElementById('screen-content'), dialog=document.getElementById('nurse-dialog');
  const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const full=p=>`${p.first} ${p.last}`, patient=id=>db.patients.find(p=>p.id===id), doctor=id=>db.doctors.find(d=>d.id===id), visit=id=>db.visits.find(v=>v.id===id);
  const stamp=()=>`04 Aug 2026 · ${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})} · Nurse Anita`;
  db.doctors.push({id:'duty',name:'Dr. S. Rao',specialty:'General Medicine',unavailable:true});
  db.visits.forEach(v=>Object.assign(v,{intake:'Not started',assessment:{},audit:[],consultation:v.status==='CANCELED'?'Cancelled':'Pending'}));
  visit('APT-1042').arrived=true;visit('APT-1089').arrived=true;
  Object.assign(visit('APT-1103'),{consultation:'In progress',intake:'Ready',assessment:{notes:'Patient-reported observations recorded for online visit.',allergy:'Unable to confirm'}});
  Object.assign(visit('APT-1120'),{intake:'In progress',assessment:{temperature:'36.8',pulse:'78',notes:'Draft from earlier intake.'}});
  const admissions=[{id:'ADM-201',patient:'PAT-0812',bed:'General / R3 / A',name:'Vikram Singh',vitals:[],notes:[]},{id:'ADM-198',patient:'IPD-0198',bed:'ICU / R1 / B',name:'Kamala Nair',vitals:[],notes:[]}];
  const meds=[{id:'M1',admission:'ADM-201',time:'08:00',drug:'Amoxicillin 500mg',dose:'1 capsule',route:'Oral',state:'Given'},{id:'M2',admission:'ADM-201',time:'08:00',drug:'Pantoprazole 40mg',dose:'1 tablet',route:'Oral',state:'Given'},{id:'M3',admission:'ADM-201',time:'14:00',drug:'Amoxicillin 500mg',dose:'1 capsule',route:'Oral',state:'Due'},{id:'M4',admission:'ADM-198',time:'14:00',drug:'Furosemide 40mg',dose:'1 tablet',route:'Oral',state:'Due'},{id:'M5',admission:'ADM-201',time:'As needed',drug:'Salbutamol Neb 2.5mg',dose:'1 dose',route:'Inhalation',state:'As needed'}];
  const reports=[{id:'REP-1',patient:'PAT-1042',title:'Complete blood count',date:'2026-08-03',source:'City Health Lab',body:'Complete blood count\nSpecimen: Blood\nHaemoglobin: 13.5 g/dL\nWhite blood cells: 7,500 /µL\nPlatelets: 250,000 /µL\n\nSample report for UX review. No clinical interpretation is generated.'},{id:'REP-2',patient:'PAT-1089',title:'Previous visit report',date:'2026-08-01',source:'Patient supplied',body:'Previous visit document\nFollow-up notes attached for the treating doctor.\n\nSample document for UX review.'}];
  const tasks=[{id:'T1',visit:'APT-1042',title:'Confirm patient brought previous reports',done:false},{id:'T2',visit:'APT-1089',title:'Prepare follow-up records for consultation',done:false}];
  const fields=[['temperature','Temperature (°C)'],['pulse','Pulse (beats/min)'],['spo2','SpO2 (%)'],['respiratory','Respiratory rate (breaths/min)'],['systolic','BP systolic (mmHg)'],['diastolic','BP diastolic (mmHg)'],['weight','Weight (kg)'],['height','Height (cm)'],['pain','Pain score (0–10)']];
  let ui={page:'dashboard',id:null,tab:'assessment',query:'',filter:'All',draft:null,dirty:false,origin:'vitals-queue',admission:'',ipdType:'',reportPatient:''},timer,returnFocus,expansion;
  const names={dashboard:'Dashboard','vitals-queue':'Vitals Queue',assessment:'Nursing Assessment',appointments:'Appointments',reports:'Reports',tasks:'Nursing Tasks','ipd-mar':'MAR (Medication Admin)','ipd-vitals':'IPD Vitals','ipd-notes':'Admission Notes',escalations:'Escalations',handoffs:'Shift Handoffs',triage:'Emergency Triage'};
  const btn=(label,action,id='',style='ghost')=>`<button type="button" class="btn btn-${style}" data-action="${action}" data-id="${e(id)}">${e(label)}</button>`;
  const badge=s=>`<span class="badge badge-${['Ready','Given','Completed'].includes(s)?'green':['In progress','Due','Not started'].includes(s)?'yellow':'blue'}">${e(s)}</span>`;
  const head=(title,sub='',actions='')=>`<div class="page-header"><div><h1 tabindex="-1">${e(title)}</h1>${sub?`<p class="muted">${e(sub)}</p>`:''}</div><div class="actions">${actions}</div></div>`;
  const detail=rows=>`<dl class="details">${rows.map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${e(v||'Not recorded')}</dd></div>`).join('')}</dl>`;
  const table=(heads,rows)=>rows.length?`<table><thead><tr>${heads.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<td data-label="${e(heads[i])}"><div>${v}</div></td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty">No matching records. Change the filter or clear your search.</div>';
  const field=(id,label,value='',type='text',extra='')=>`<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><input id="${id}" name="${id}" class="form-control" type="${type}" value="${e(value)}" ${type==='number'?'step="any"':''} ${extra}><div class="field-error" id="${id}-error"></div></div>`;
  const select=(id,label,options,value='')=>`<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><select id="${id}" name="${id}" class="form-control">${options.map(o=>{const [v,l,disabled]=Array.isArray(o)?o:[o,o];return `<option value="${e(v)}" ${v===value?'selected':''} ${disabled?'disabled':''}>${e(l)}</option>`;}).join('')}</select><div class="field-error" id="${id}-error"></div></div>`;
  const area=(id,label,value='')=>`<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><textarea id="${id}" name="${id}" class="form-control">${e(value)}</textarea><div class="field-error" id="${id}-error"></div></div>`;
  const errorsBox=()=>'<div class="error-summary" id="errors" tabindex="-1" role="alert"></div>';
  function errors(items,scope=root){scope.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));scope.querySelectorAll('.field-error').forEach(x=>x.textContent='');const box=scope.querySelector('#errors');box.innerHTML=items.map(([id,msg])=>`<a href="#${id}">${e(msg)}</a>`).join('');items.forEach(([id,msg])=>{const input=scope.querySelector('#'+id);if(input){input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby',id+'-error');}const hint=scope.querySelector('#'+id+'-error');if(hint)hint.textContent=msg;});if(items.length){box.focus();box.scrollIntoView({block:'nearest'});return true;}return false;}
  function clearToast(){clearTimeout(timer);document.getElementById('feedback').textContent='';}
  function toast(message){clearToast();document.getElementById('feedback').textContent=message;timer=setTimeout(clearToast,4500);}
  function close(){dialog.close();if(returnFocus?.isConnected)returnFocus.focus();}
  function modal(title,body,actions=[]){clearToast();returnFocus=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${e(title)}</h2><button type="button" class="btn btn-ghost" data-close>Close</button></div><div class="dialog-body">${body}</div><div class="dialog-foot">${actions.map((a,i)=>`<button type="button" class="btn btn-${a.style||'ghost'}" data-modal="${i}">${e(a.label)}</button>`).join('')}</div>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.querySelector('[data-close]').onclick=close;actions.forEach((a,i)=>dialog.querySelector(`[data-modal="${i}"]`).onclick=()=>{const content=dialog.firstChild;if(a.run?.()===false)return;if(dialog.firstChild===content)close();});if(!dialog.open)dialog.showModal();}
  dialog.addEventListener('cancel',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
  function guarded(run){if(ui.dirty)modal('Discard unsaved changes?','Your saved assessment will be kept. Only the current unsaved edits will be discarded.',[{label:'Keep editing'},{label:'Discard changes',style:'danger',run:()=>{ui.draft=ui.page==='assessment'?{...visit(ui.id).assessment}:{};ui.dirty=false;render();run();}}]);else run();}
  function go(page,id=null){guarded(()=>{ui.page=page;ui.id=id;ui.dirty=false;ui.draft=null;ui.tab='assessment';ui.admission='';render();});}
  function openAssessment(id){guarded(()=>{ui.origin='vitals-queue';ui.page='assessment';ui.id=id;ui.tab='assessment';ui.draft={...visit(id).assessment};ui.dirty=false;render();});}
  const matches=v=>`${full(patient(v.patient))} ${v.patient} ${v.id}`.toLowerCase().includes(ui.query.toLowerCase());
  const editable=v=>v.arrived&&v.channel==='IN_PERSON'&&v.consultation==='Pending';
  const available=()=>db.visits.filter(v=>v.consultation!=='Cancelled');
  function rows(list){return expansion.rows(list);}
  function filters(){return `<div class="filterbar">${field('queue-search','Search patient or visit',ui.query,'search')}${select('queue-filter','Assessment status',['All','Pending intake','Not started','In progress','Ready'],ui.filter)}${btn('Clear filters','clear-filters')}</div>`;}
  function queue(){return head('Vitals Queue','Select the intended patient and visit before entering an assessment.')+`<section class="card">${filters()}<div id="queue-rows">${rows(available().filter(v=>matches(v)&&(ui.filter==='All'||v.intake===ui.filter||(ui.filter==='Pending intake'&&editable(v)&&v.intake!=='Ready'))))}</div></section>`;}
  function dashboard(){return head('Nursing Dashboard','Today · 04 Aug 2026 · City Health Clinic')+`<div class="stat-grid">${[[available().filter(v=>editable(v)&&v.intake!=='Ready').length,'Intake pending','pending'],[available().filter(v=>v.intake==='Ready').length,'Ready for doctor','ready-list'],[tasks.filter(t=>!t.done).length,'Nursing tasks','tasks'],[meds.filter(m=>m.state==='Due').length,'MAR slots due','ipd-mar']].map(([count,label,action])=>`<button class="stat-card" data-action="${action}"><div class="stat-value">${count}</div><div class="stat-label">${label}</div></button>`).join('')}</div><div class="workspace"><section class="card"><h2>OPD Vitals Queue (Today)</h2>${rows(available())}</section><aside><section class="card"><h2>Shift overview</h2><p><b>Nurse Anita</b><br><span class="muted">Morning shift · OPD & IPD</span></p>${detail([['Inpatients',`${admissions.length} active admissions`],['Workflow','Save assessment, then mark ready']])}</section><section class="card"><h2>Pending nursing work</h2>${tasks.filter(t=>!t.done).map(t=>`<div class="history"><b>${e(full(patient(visit(t.visit).patient)))}</b><p>${e(t.title)}</p>${btn('Open task','tasks')}</div>`).join('')||'<p>No pending tasks.</p>'}</section></aside></div>`;}
  function identity(v){return `<section class="card identity"><div><h2>${e(full(patient(v.patient)))}</h2><p>${e(v.patient)} · ${e(patient(v.patient).gender)} · ${e(v.id)}</p></div><div><b>${e(doctor(v.doctor).name)}</b><p>04 Aug 2026 · ${e(v.time)} · ${e(v.channel==='ONLINE'?'Online':'In person')}</p></div>${badge(v.intake)}</section>`;}
  function vitalFields(a){return `<div class="form-row-4">${fields.map(([id,label])=>field(id,label,a[id]??'','number')).join('')}${field('bmi','BMI (auto-calculated)',a.weight&&a.height?(Number(a.weight)/(Number(a.height)/100)**2).toFixed(1):'','text','readonly')}</div>`;}
  function assessment(){const v=visit(ui.id),a=ui.draft;return head('Nursing Assessment',v.reason,btn('Back to '+(names[ui.origin]||'Vitals Queue'),'back'))+identity(v)+`<div class="tabs">${[['assessment','Assessment'],['reports','Reports'],['history','Activity']].map(([key,label])=>`<button class="btn btn-ghost" data-action="tab" data-id="${key}" aria-pressed="${ui.tab===key}">${label}${key==='reports'?` (${reports.filter(r=>r.patient===v.patient).length})`:''}</button>`).join('')}</div>`+(ui.tab==='reports'?reportList(v.patient):ui.tab==='history'?`<section class="card"><h2>Visit activity</h2>${history(v.audit)}</section>`:`<div class="workspace"><section class="card">${!editable(v)?`<p class="notice">${v.consultation!=='Pending'?'This consultation is '+e(v.consultation.toLowerCase())+'. Nursing assessment is read-only.':v.channel==='ONLINE'?'Online visit: no in-person intake.':'Patient has not arrived. Assessment is available after check-in.'}</p>${assessmentSummary(v.assessment)}`:`<form id="assessment-form" novalidate>${errorsBox()}<h2>Vital signs</h2><p class="muted">Save any measurements as a draft. Missing measurements remain unrecorded.</p>${vitalFields(a)}<div class="form-row">${field('device','Measured device',a.device)}${field('measured','Measured at',a.measured||'2026-08-04T09:28','datetime-local')}</div><h2>Patient assessment</h2>${select('allergy','Allergy status',[['','Select status'],'No known allergies','Known allergies','Unable to confirm'],a.allergy||'')}${field('allergyDetails','Allergy details / reaction',a.allergyDetails)}${area('notes','Nursing notes / patient concerns',a.notes)}<details ${a.exception?'open':''}><summary>Unable to obtain some measurements?</summary>${area('exception','Measurement exception',a.exception)}</details><div class="actions form-footer"><button class="btn btn-primary" type="submit">Save Vitals</button>${btn('Cancel','back')}</div><p class="muted" id="draft-status">${ui.dirty?'Unsaved changes':v.saved?'Last saved: '+e(v.saved):'Not saved yet'}</p></form>`}</section><aside><section class="card"><h2>Consultation preparation</h2>${detail([['Consultation',v.consultation],['Arrival',v.arrived?'Checked in':v.channel==='ONLINE'?'Online visit':'Not arrived'],['Assessment',v.intake]])}<div class="form-footer">${editable(v)&&v.intake!=='Ready'?btn('Mark Ready for Doctor','ready',v.id,'success'):v.intake==='Ready'?'<p class="notice">Assessment ready for doctor.</p>':''}</div><p class="muted">Readiness records preparation; it does not start or sign a consultation.</p></section><section class="card"><h2>Assigned doctor</h2><p><b>${e(doctor(v.doctor).name)}</b><br>${e(doctor(v.doctor).specialty)}</p>${v.consultation==='Pending'?btn('Reassign Consultation','reassign',v.id):'<p class="muted">Reassignment is available for pending consultations only.</p>'}</section><section class="card"><h2>Saved activity</h2>${history(v.audit.slice(-3))}</section></aside></div>`);}
  function assessmentSummary(a){return detail([...fields.map(([id,label])=>[label,a[id]]),['Allergy status',a.allergy],['Allergy details',a.allergyDetails],['Nursing notes',a.notes],['Measurement exception',a.exception]]);}
  function history(items){return items.length?items.slice().reverse().map(x=>`<div class="history"><b>${e(x.title)}</b><p>${e(x.detail)}</p><small>${e(x.at)}</small></div>`).join(''):'<p class="muted">No activity recorded yet.</p>';}
  function validateVitals(a){const items=[];for(const [id,label] of fields){const n=Number(a[id]);if(a[id]!==undefined&&a[id]!==''&&(!Number.isFinite(n)||n<0||(id!=='pain'&&n===0)||(id==='spo2'&&n>100)||(id==='pain'&&n>10)))items.push([id,`Check ${label.toLowerCase()}: enter ${id==='pain'?'0 to 10':id==='spo2'?'above 0 and up to 100':'a positive number'}.`]);}if(a.systolic&&a.diastolic&&Number(a.systolic)<=Number(a.diastolic))items.push(['systolic','Systolic must be above diastolic. Check the recorded values.']);if(a.measured&&a.measured.slice(0,10)>db.date)items.push(['measured','Measurement cannot be after the scenario date.']);if(a.allergy==='Known allergies'&&!a.allergyDetails?.trim())items.push(['allergyDetails','Record the known allergy and any known reaction.']);return items;}
  function saveAssessment(){const v=visit(ui.id);if(ui.page!=='assessment'||!editable(v))return;const a=ui.draft;if(errors(validateVitals(a)))return;if(!Object.values(a).some(x=>String(x).trim())){errors([['temperature','Record a measurement or assessment detail before saving.']]);return;}v.assessment={...a,measured:a.measured||'2026-08-04T09:28'};v.intake='In progress';v.saved=stamp();v.audit.push({title:'Assessment saved',detail:'Nursing measurements and notes saved. Readiness awaits confirmation.',at:v.saved});ui.dirty=false;render();toast('Assessment saved for '+full(patient(v.patient))+'.');}
  function ready(id){const v=visit(id);if(!editable(v)||v.intake==='Ready')return;if(ui.dirty){modal('Save assessment first','Save your current changes before marking this visit ready.',[{label:'Return to assessment'}]);return;}const a=v.assessment,missing=['temperature','pulse','spo2','systolic','diastolic'].filter(k=>!a[k]);if(!v.saved||(!a.exception?.trim()&&missing.length)||!a.allergy){modal('Assessment needs attention',`<p>Save the assessment with core measurements (temperature, pulse, SpO2 and blood pressure), or document why measurements could not be obtained. Select an allergy status, including “Unable to confirm” when appropriate.</p><p class="muted">This is the prototype preparation checklist; hospital policy is to be confirmed during review.</p>`,[{label:'Return to assessment'}]);return;}modal('Mark Ready for Doctor',identity(v)+`<p>The saved assessment will be marked ready for ${e(doctor(v.doctor).name)}.</p>${a.exception?`<p class="notice">Measurement exception: ${e(a.exception)}</p>`:''}`,[{label:'Cancel'},{label:'Confirm Ready',style:'success',run:()=>{if(v.intake==='Ready')return;v.intake='Ready';v.audit.push({title:'Ready for doctor',detail:doctor(v.doctor).name,at:stamp()});render();toast('Ready for doctor: '+full(patient(v.patient))+'.');}}]);}
  function reassign(id){guarded(()=>{const v=visit(id);if(v.consultation!=='Pending')return;modal('Reassign Consultation',identity(v)+errorsBox()+select('receiving','Receiving doctor',[['','Select receiving doctor'],...db.doctors.filter(d=>d.id!==v.doctor).map(d=>[d.id,`${d.name} · ${d.specialty}${d.unavailable?' · Unavailable':''}`,d.unavailable])])+`<p class="notice">The visit, saved assessment and reports stay with this patient. The receiving doctor's specialty is shown for your selection.</p>`,[{label:'Cancel'},{label:'Confirm Reassignment',style:'primary',run:()=>{const id=dialog.querySelector('#receiving').value,d=doctor(id);if(!d||d.unavailable)return !errors([['receiving','Select an available receiving doctor.']],dialog);const previous=doctor(v.doctor).name;v.doctor=id;v.audit.push({title:'Consultation reassigned',detail:previous+' → '+d.name,at:stamp()});ui.draft={...v.assessment};render();toast('Consultation reassigned to '+d.name+'.');}}]);});}
  function reportList(pid){const list=reports.filter(r=>r.patient===pid);return `<section class="card"><div class="page-header"><div><h2>Patient reports</h2><p class="muted">${e(full(patient(pid)))} · ${e(pid)}</p></div>${btn('Upload Report','upload',pid,'primary')}</div><p class="muted">Available to hospital doctors through the patient record. Opening a report does not mark it clinically reviewed.</p><div class="record-list">${list.map(r=>`<article><div class="actions"><div><h3>${e(r.title)}</h3><small>${e(r.date)} · ${e(r.source)} · ${e(r.id)}</small></div>${btn('View Report','report',r.id)}</div></article>`).join('')||'<p class="empty">No reports on record for this patient.</p>'}</div></section>`;}
  function reportPage(){return head('Reports','Find a patient, then view or attach documents.')+`<section class="card">${select('report-patient','Patient',[['','Select patient'],...db.patients.map(p=>[p.id,full(p)+' · '+p.id])],ui.reportPatient)}</section>`+(ui.reportPatient?reportList(ui.reportPatient):'<div class="card empty">Select a patient to see their reports.</div>');}
  function upload(pid){modal('Upload Report',`<p><b>${e(full(patient(pid)))} · ${e(pid)}</b></p>${errorsBox()}${select('sample','Report document',[['','Select mock document'],['blood','Sample blood report.pdf'],['visit','Sample visit report.pdf']])}<div class="attachment-choice">Choose a sample document to simulate an upload. No personal file is sent.</div>${field('report-date','Report date',db.date,'date')}`,[{label:'Cancel'},{label:'Add Report',style:'primary',run:()=>{const kind=dialog.querySelector('#sample').value,date=dialog.querySelector('#report-date').value;const errs=[];if(!kind)errs.push(['sample','Select a sample document.']);if(!date||date>db.date)errs.push(['report-date','Choose a report date on or before the scenario date.']);if(errors(errs,dialog))return false;reports.push({id:'REP-'+(reports.length+1),patient:pid,title:kind==='blood'?'Sample blood report':'Sample visit report',date,source:'Uploaded by Nurse Anita',body:'Sample document attached by Nurse Anita.\n\nFor UX review only. This is not an actual patient report.'});render();toast('Report added to '+full(patient(pid))+'.');}}]);}
  function viewReport(id){const r=reports.find(x=>x.id===id);modal(r.title,`<p><b>${e(full(patient(r.patient)))} · ${e(r.patient)}</b><br>${e(r.date)} · ${e(r.id)} · ${e(r.source)}</p><div class="report-body">${e(r.body)}</div>`,[{label:'Close Report'}]);}
  function taskPage(){return expansion.tasks();}
  function ipdPage(){const type=ui.page;return head(names[type],type==='ipd-mar'?'Medication orders shown as mock records. Select the actual outcome for the selected patient.':'Select an admission before entering clinical observations.')+(type==='ipd-mar'?`<section class="card">${table(['Time','Patient / Admission','Medication / Route','Ordered dose','Status','Action'],meds.map(m=>{const a=admissions.find(a=>a.id===m.admission);return [e(m.time),`<b>${e(a.name)}</b><br><small>${e(a.id)} · ${e(a.bed)}</small>`,`${e(m.drug)}<br><small>${e(m.route)}</small>`,e(m.dose),badge(m.state),['Due','As needed'].includes(m.state)?`<div class="actions">${btn(m.state==='As needed'?'Administer PRN':'Given','mar',m.id+'|Given','success')}${btn('Held','mar',m.id+'|Held')}${btn('Refused','mar',m.id+'|Refused')}</div>`:`<small>${e(m.at||'04 Aug 2026 · 08:00')}<br>${e(m.note||'Recorded')}</small>`];}))}</section>`:`<section class="card">${select('admission','Patient / Admission',[['','Select admission'],...admissions.map(a=>[a.id,`${a.name} · ${a.id} · ${a.bed}`])],ui.admission)}</section>`+(ui.admission?ipdForm(type):'<section class="card empty">Select an admission to continue.</section>'));}
  function ipdForm(type){const a=admissions.find(a=>a.id===ui.admission),d=ui.draft||{};return `<section class="card"><h2>${e(a.name)} · ${e(a.id)}</h2><p class="muted">${e(a.bed)}</p><form id="ipd-form" novalidate>${errorsBox()}${type==='ipd-vitals'?vitalFields(d):select('noteType','Note type',['Nursing','Progress','Observation','Handover'],d.noteType||'Nursing')+field('title','Title',d.title)+area('note','Details',d.note)}${field('eventTime','Event time',d.eventTime||'2026-08-04T09:28','datetime-local')}<div class="actions form-footer"><button type="submit" class="btn btn-primary">${type==='ipd-vitals'?'Save IPD Vitals':'Save Note'}</button>${btn('Cancel','ipd-cancel')}</div></form></section><section class="card"><h2>Saved ${type==='ipd-vitals'?'observations':'notes'}</h2>${history(type==='ipd-vitals'?a.vitals:a.notes)}</section>`;}
  function mar(id){const [key,state]=id.split('|'),m=meds.find(m=>m.id===key),a=admissions.find(a=>a.id===m.admission);if(!['Due','As needed'].includes(m.state))return;const previous=meds.find(x=>x.id!==m.id&&x.admission===m.admission&&x.drug===m.drug&&x.state==='Given');modal('Record Medication Outcome',detail([['Patient',a.name+' · '+a.id],['Ward / Bed',a.bed],['Medication',m.drug],['Ordered dose',m.dose],['Route',m.route],['Outcome',state],['Order status','Active mock order'],['Scheduled time',m.time],['Last recorded dose',previous?previous.time+' · '+(previous.at||'04 Aug 2026'):'None in mock record'],['Allergy status','Not recorded in mock admission']])+`<p class="notice">Check the active order, allergy record and bedside identity before recording. No safety check is automated in this prototype.</p>`+errorsBox()+`<div class="form-group"><label for="bedside-check"><input id="bedside-check" type="checkbox"> I checked the patient identity and medication order at the bedside</label><div class="field-error" id="bedside-check-error"></div></div>`+area('mar-note',state==='Given'?'Administration note (optional)':'Reason', '')+`<p class="muted">Record the outcome after the actual bedside action. This prototype records no real medication administration.</p>`,[{label:'Cancel'},{label:'Confirm '+state,style:state==='Given'?'success':'primary',run:()=>{if(!['Due','As needed'].includes(m.state))return;const note=dialog.querySelector('#mar-note').value.trim(),err=[];if(!dialog.querySelector('#bedside-check').checked)err.push(['bedside-check','Confirm the bedside identity and order check.']);if(state!=='Given'&&!note)err.push(['mar-note','Record the reason for this outcome.']);if(errors(err,dialog))return false;m.state=state;m.note=note;m.at=stamp();render();toast(state+' recorded for '+a.name+'.');}}]);}
  function render(){clearToast();const pages={dashboard,assessment,'vitals-queue':queue,appointments:expansion.appointments,reports:reportPage,tasks:taskPage,'ipd-mar':ipdPage,'ipd-vitals':ipdPage,'ipd-notes':ipdPage,escalations:expansion.escalations,handoffs:expansion.handoffs,triage:expansion.triage};root.innerHTML=pages[ui.page]();if(ui.page==='appointments'){root.insertAdjacentHTML('beforeend',WalkinUI.slot());WalkinUI.mount({role:'nurse',render});}document.getElementById('page-title').textContent=names[ui.page];document.querySelectorAll('[data-screen]').forEach(n=>{const active=n.dataset.screen===(ui.page==='assessment'?'vitals-queue':ui.page);n.classList.toggle('active',active);n.setAttribute('aria-current',active?'page':'false');});expansion.decorate();root.querySelector('h1')?.focus({preventScroll:true});window.scrollTo(0,0);bind();}
  function bind(){root.querySelector('#queue-search')?.addEventListener('input',ev=>{ui.query=ev.target.value;root.querySelector('#queue-rows').innerHTML=rows(available().filter(v=>matches(v)&&(ui.filter==='All'||v.intake===ui.filter||(ui.filter==='Pending intake'&&editable(v)&&v.intake!=='Ready'))));});root.querySelector('#queue-filter')?.addEventListener('change',ev=>{ui.filter=ev.target.value;render();});root.querySelector('#report-patient')?.addEventListener('change',ev=>{ui.reportPatient=ev.target.value;render();});const form=root.querySelector('#assessment-form')||root.querySelector('#ipd-form');form?.addEventListener('input',ev=>{if(!ev.target.name)return;ui.draft[ev.target.name]=ev.target.value;ui.dirty=true;if(ev.target.name==='weight'||ev.target.name==='height'){const a=ui.draft;root.querySelector('#bmi').value=a.weight>0&&a.height>0?(a.weight/(a.height/100)**2).toFixed(1):'';}const status=root.querySelector('#draft-status');if(status)status.textContent='Unsaved changes';});form?.addEventListener('submit',ev=>{ev.preventDefault();if(ui.page==='assessment')saveAssessment();else saveIPD();});root.querySelector('#admission')?.addEventListener('change',ev=>{const id=ev.target.value;ev.target.value=ui.admission;guarded(()=>{ui.admission=id;ui.draft={};ui.dirty=false;render();});});expansion.bind();}
  function saveIPD(){const a=admissions.find(a=>a.id===ui.admission);if(!a)return;const d=ui.draft,errs=ui.page==='ipd-vitals'?validateVitals(d):[];if(ui.page==='ipd-vitals'&&!fields.some(([id])=>d[id]))errs.push(['temperature','Enter at least one measurement.']);if(ui.page==='ipd-notes'&&!d.note?.trim())errs.push(['note','Enter the nursing note details.']);if(d.eventTime&&d.eventTime.slice(0,10)>db.date)errs.push(['eventTime','Event time cannot be after the scenario date.']);if(errors(errs))return;const item={measurements:{...d},title:ui.page==='ipd-vitals'?'Vitals recorded':d.title||d.noteType||'Nursing note',detail:ui.page==='ipd-vitals'?fields.filter(([id])=>d[id]).map(([id,label])=>label+': '+d[id]).join(' · '):d.note,at:(d.eventTime||'2026-08-04T09:28')+' · Nurse Anita'};(ui.page==='ipd-vitals'?a.vitals:a.notes).push(item);ui.draft={};ui.dirty=false;render();toast('Saved for '+a.name+' · '+a.id+'.');}
  root.addEventListener('click',ev=>{const b=ev.target.closest('[data-action]');if(!b)return;const {action,id}=b.dataset;if(expansion.handle(action,id))return;if(action==='assessment')return openAssessment(id);if(action==='back')return go(ui.origin);if(action==='tab')return guarded(()=>{ui.draft={...visit(ui.id).assessment};ui.tab=id;render();});if(action==='ready')return ready(id);if(action==='reassign')return reassign(id);if(action==='report')return viewReport(id);if(action==='upload')return upload(id);if(action==='mar')return mar(id);if(action==='task'){const t=tasks.find(t=>t.id===id),v=visit(t.visit);return modal('Complete Nursing Task',`<p><b>${e(full(patient(v.patient)))} · ${e(v.id)}</b></p><p>${e(t.title)}</p>`,[{label:'Cancel'},{label:'Confirm Completion',style:'success',run:()=>{t.done=true;t.at=stamp();render();toast('Task completed.');}}]);}if(action==='pending'||action==='ready-list'){ui.filter=action==='pending'?'Pending intake':'Ready';return go('vitals-queue');}if(action==='clear-filters'){ui.query='';ui.filter='All';return render();}if(action==='ipd-cancel')return go(ui.page);if(['tasks','ipd-mar'].includes(action))return go(action);});
  document.querySelectorAll('[data-screen]').forEach(n=>n.addEventListener('click',()=>go(n.dataset.screen)));
  document.getElementById('global-search').addEventListener('submit',ev=>{ev.preventDefault();const q=document.getElementById('global-query').value.trim().toLowerCase();const found=q?available().filter(v=>`${full(patient(v.patient))} ${v.patient} ${v.id}`.toLowerCase().includes(q)):[];modal('Patient search',found.length?found.map(v=>`<p>${btn(full(patient(v.patient))+' · '+v.id,'search-result',v.id,'primary')}</p>`).join(''):'<p>No matching visits. Search by patient name, patient ID or appointment ID.</p>',[{label:'Close Search'}]);dialog.querySelectorAll('[data-action="search-result"]').forEach(b=>b.onclick=()=>{close();openAssessment(b.dataset.id);});});
  document.getElementById('notifications').onclick=()=>modal('Nursing alerts',`<p>${tasks.filter(t=>!t.done).length} pending nursing tasks.</p><p>${meds.filter(m=>m.state==='Due').length} medication slots due in the mock schedule.</p>`,[{label:'Close Alerts'},{label:'View Nursing Tasks',style:'primary',run:()=>go('tasks')}]);
  window.addEventListener('beforeunload',ev=>{if(ui.dirty){ev.preventDefault();ev.returnValue='';}});
  expansion=window.createNurseExpansion({db,root,dialog,ui,admissions,meds,tasks,e,full,patient,doctor,visit,stamp,btn,badge,head,table,field,select,area,errorsBox,errors,modal,toast,render,go,openAssessment,guarded,editable});
  DemoStore.attach('nurse',()=>({db,admissions,meds,reports,tasks,extra:expansion.snapshot()}),data=>{for(const [key,target] of Object.entries({db,admissions,meds,reports,tasks}))if(data[key])DemoStore.replace(target,data[key]);expansion.restore(data.extra);});
  render();
})();
