(() => {
 'use strict';
 const root=document.getElementById('screen-content'),dialog=document.getElementById('patient-dialog'),feedback=document.getElementById('patient-feedback');
 const today='2026-08-04';
 const people={ravi:{name:'Ravi Kumar',id:'PAT-1042',relation:'Self',phone:'9876543210',email:'ravi@example.test',dob:'1988-05-14'},anaya:{name:'Anaya Kumar',id:'PAT-2042',relation:'Daughter',phone:'9876543210',email:'',dob:'2016-02-20'}};
 const doctors=[{id:'priya',name:'Dr. Priya Sharma',specialty:'General Medicine',qualification:'MBBS, MD',experience:'12 years',fee:500,types:['In person','Online'],initials:'PS'},{id:'amit',name:'Dr. Amit Joshi',specialty:'Cardiology',qualification:'MBBS, DM',experience:'15 years',fee:800,types:['In person','Online'],initials:'AJ'},{id:'neha',name:'Dr. Neha Rao',specialty:'Pediatrics',qualification:'MBBS, MD',experience:'9 years',fee:600,types:['In person'],initials:'NR'},{id:'sara',name:'Dr. Sara Ali',specialty:'Dermatology',qualification:'MBBS, MD',experience:'8 years',fee:650,types:[],initials:'SA'}];
 // Discovery tags are mock catalogue data, never inferred diagnoses.
 const hospitals={city:{name:'City Health Clinic',address:'City Health Clinic, MG Road, Bengaluru'},lakeside:{name:'Lakeside Hospital',address:'Lakeside Hospital, Whitefield, Bengaluru'}};
 const conditions={priya:['Fever','Diabetes','Hypertension'],amit:['Hypertension','Heart disease'],neha:['Childhood fever','Asthma'],sara:['Eczema','Acne']};
 doctors.forEach(d=>{d.hospital='city';d.conditions=conditions[d.id];});
 doctors.push({id:'meera',name:'Dr. Meera Nair',specialty:'General Medicine',qualification:'MBBS, MD',experience:'10 years',fee:550,types:['In person','Online'],initials:'MN',hospital:'lakeside',conditions:['Diabetes','Fever','Hypertension']});
 doctors.push({id:'dental-demo',name:'Dr. Anjali Desai',specialty:'Dentistry',qualification:'BDS, MDS',experience:'8 years',fee:600,types:['In person'],initials:'AD',hospital:'city',conditions:['Dental care']},{id:'vision-demo',name:'Dr. Vikram Shah',specialty:'Ophthalmology',qualification:'MBBS, MS',experience:'11 years',fee:700,types:['In person'],initials:'VS',hospital:'lakeside',conditions:['Eye care']});
 const facility=d=>hospitals[d.hospital];
 const appointments=[{id:'APT-1042',person:'ravi',doctor:'priya',date:'2026-08-04',time:'09:30',type:'In person',status:'Completed',payment:'Paid',reason:'Fever review',fee:500,summary:'Symptoms and previous reports reviewed. Follow the signed prescription and follow-up plan.',rx:'RX-1042'},{id:'APT-1043',person:'ravi',doctor:'priya',date:'2026-08-11',time:'09:30',type:'In person',status:'Scheduled',payment:'Paid',reason:'Follow-up visit',fee:500},{id:'APT-1044',person:'ravi',doctor:'amit',date:'2026-08-18',time:'14:00',type:'Online',status:'Scheduled',payment:'Pending',reason:'Review previous reports',fee:800},{id:'APT-1045',person:'ravi',doctor:'amit',date:'2026-07-28',time:'10:00',type:'In person',status:'Cancelled',payment:'Not charged',reason:'Previous booking',fee:800}];
 const reports=[{id:'DOC-1',person:'ravi',consultation:'APT-1042',title:'Complete blood count',date:'2026-08-04',category:'Lab report',body:'Sample laboratory report. Hemoglobin: 13.8 g/dL. This is fixture content for document-viewing UX.',source:'City Diagnostics'},{id:'DOC-2',person:'ravi',title:'Chest X-Ray',date:'2026-07-28',category:'Imaging',body:'Sample imaging report attached to the patient record.',source:'City Health Clinic'}];
 const prescriptions=[{id:'RX-1042',person:'ravi',date:'2026-08-04',doctor:'priya',consultation:'APT-1042',body:'Paracetamol 500 mg — as recorded in the sample signed prescription.\nUse the instructions issued by your treating doctor. This document is a UX fixture.'}];
 // Additional fictional prescription history; each document has its own completed encounter.
 for(let i=1;i<=50;i++){
  const day=new Date(today+'T12:00:00Z');day.setUTCDate(day.getUTCDate()-i*3);
  const date=day.toISOString().slice(0,10),doctor=['priya','amit','meera'][(i-1)%3],rx='RX-MOCK-'+String(i).padStart(3,'0'),id='APT-RX-MOCK-'+String(i).padStart(3,'0');
  prescriptions.push({id:rx,person:'ravi',date,doctor,consultation:id,body:`Fictional prescription ${i} of 50.\nSample medicine entry ${i} — demonstration content only.\nThis mock record does not provide medicine or dosing instructions.`});
  appointments.push({id,person:'ravi',doctor,date,time:i%2?'09:30':'14:00',type:'In person',status:'Completed',payment:'Paid',reason:'Sample historical consultation '+i,fee:doctors.find(d=>d.id===doctor).fee,summary:'Fictional completed consultation '+i+'. The linked signed prescription is a read-only UX sample.',rx});
 }
 const followups=[{id:'FU-1',person:'ravi',doctor:'priya',due:'2026-08-11',reason:'Follow-up visit',appointment:'APT-1043'},{id:'FU-2',person:'ravi',doctor:'amit',due:'2026-08-25',reason:'Bring previous reports for review',appointment:null}];
 const health={ravi:{Allergies:[['Penicillin','Rash reported · patient-reported']],Medications:[['Amlodipine 5 mg','Listed in historical record; verify with treating doctor']], 'Family history':[['Father','Type 2 diabetes']],Vaccines:[['Influenza','01 Oct 2025 · patient-reported']], 'Substance use':[['Tobacco','Never · patient-reported']]},anaya:{Allergies:[],Medications:[],'Family history':[],Vaccines:[],'Substance use':[]}};
 const labs=[{id:'LAB-1',person:'ravi',title:'Complete blood count',status:'Completed',date:'2026-08-04',fee:350,report:'DOC-1'},{id:'LAB-2',person:'ravi',title:'HbA1c',status:'Ordered',date:'2026-08-05',fee:450}];
 const tickets=[],requests=[];
 const ui={page:'dashboard',person:'ravi',id:null,tab:'Upcoming',healthTab:'Overview',booking:null,dirty:false,origin:'appointments'};
 const titles={service:'Patient services',dashboard:'Dashboard',doctors:'Find a Doctor',doctor:'Doctor profile',appointments:'My Appointments',appointment:'Appointment details',booking:'Book appointment',success:'Booking confirmed',records:'My Records',prescriptions:'Prescriptions',followups:'Follow-ups',health:'Health Profile',profile:'Profile & Family',labs:'Lab Orders',claim:'Claim Records',emergency:'Emergency',support:'Support',room:'Online waiting room'};
 const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const portraitPaths={priya:'assets/doctors/priya-sharma.png',amit:'assets/doctors/amit-joshi.png'};
 const doctorPortrait=d=>portraitPaths[d.id]?`<button type="button" class="doctor-avatar doctor-photo doctor-photo-button" data-action="doctor-photo" data-id="${e(d.id)}" aria-label="View photo of ${e(d.name)}"><img src="${portraitPaths[d.id]}" alt="" width="52" height="52" loading="lazy"></button>`:`<div class="doctor-avatar" aria-hidden="true">${e(d.initials)}</div>`;
 const person=()=>people[ui.person],doctor=id=>doctors.find(d=>d.id===id),appt=id=>appointments.find(a=>a.id===id&&a.person===ui.person);
 const timeLabel=value=>{if(!value)return '';if(!/^\d{2}:\d{2}$/.test(value))return String(value);const [hour,minute]=value.split(':');const h=Number(hour);return `${h%12||12}:${minute} ${h>=12?'PM':'AM'}`;};
 const own=items=>items.filter(a=>a.person===ui.person),date=v=>new Date(v+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),money=v=>'₹'+v;
 const btn=(label,action,id='',style='ghost')=>`<button type="button" class="btn btn-${style}" data-action="${action}" data-id="${e(id)}">${e(label)}</button>`;
 const badge=s=>`<span class="badge badge-${['Completed','Paid','Signed','Confirmed'].includes(s)?'green':['Pending','Scheduled','Ordered'].includes(s)?'yellow':'blue'}">${e(s)}</span>`;
 const field=(id,label,value='',type='text',extra='')=>`<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><input class="form-control" id="${id}" name="${id}" type="${type}" value="${e(value)}" ${extra}></div>`;
 const area=(id,label,value='')=>`<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><textarea class="form-control" id="${id}" name="${id}">${e(value)}</textarea></div>`;
 const select=(id,label,values,value='')=>`<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><select class="form-control" id="${id}" name="${id}">${values.map(v=>{const [key,text]=Array.isArray(v)?v:[v,v];return `<option value="${e(key)}" ${key===value?'selected':''}>${e(text)}</option>`;}).join('')}</select></div>`;
 const details=items=>`<dl class="details">${items.map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${e(v||'Not recorded')}</dd></div>`).join('')}</dl>`;
 const identity=()=>`<div class="identity"><b>${e(person().name)}</b><p>${person().id} · ${person().relation}</p></div>`;
 const head=(title,sub='',actions='')=>`<div class="page-header"><div><h1 tabindex="-1">${e(title)}</h1><p class="muted">${e(sub)}</p></div><div class="actions">${actions}</div></div>`;
 const empty=(text,action='')=>`<div class="empty"><p>${e(text)}</p>${action}</div>`;
 const errorBox=()=>'<div class="error-summary" role="alert" tabindex="-1"></div>';
 let timer,returnFocus;
 function toast(text){clearTimeout(timer);feedback.textContent=text;timer=setTimeout(()=>feedback.textContent='',4500);}
 function close(){dialog.close();if(returnFocus?.isConnected)returnFocus.focus();}
 function modal(title,body,actions=[]){feedback.textContent='';returnFocus=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${e(title)}</h2><button class="btn btn-ghost" data-close>Close</button></div><div class="dialog-body">${body}</div><div class="dialog-foot">${actions.map((a,i)=>`<button class="btn btn-${a.style||'ghost'}" data-modal="${i}">${e(a.label)}</button>`).join('')}</div>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.querySelector('[data-close]').onclick=close;actions.forEach((a,i)=>dialog.querySelector(`[data-modal="${i}"]`).onclick=()=>{const first=dialog.firstChild;if(a.run?.()===false)return;if(dialog.firstChild===first)close();});if(!dialog.open)dialog.showModal();}
 function errors(items,scope=root){scope.querySelectorAll('.field-error').forEach(n=>n.remove());scope.querySelectorAll('[aria-invalid]').forEach(n=>{n.removeAttribute('aria-invalid');n.removeAttribute('aria-describedby');});const box=scope.querySelector('.error-summary');if(!box)return items.length>0;box.innerHTML=items.map(([id,msg])=>`<a href="#${id}">${e(msg)}</a>`).join('');for(const [id,msg] of items){const f=scope.querySelector('#'+id);if(f){f.setAttribute('aria-invalid','true');f.setAttribute('aria-describedby',id+'-error');f.insertAdjacentHTML('afterend',`<span class="field-error" id="${id}-error">${e(msg)}</span>`);}}box.querySelectorAll('a').forEach(a=>a.onclick=ev=>{ev.preventDefault();scope.querySelector(a.getAttribute('href'))?.focus();});if(items.length)box.focus();return items.length>0;}
 const val=id=>dialog.querySelector('#'+id)?.value.trim()||'';
 function guarded(run){if(ui.dirty)modal('Leave this booking?','The appointment has not been booked. Your current booking choices will be discarded.',[{label:'Keep booking'},{label:'Discard booking',style:'danger',run:()=>{ui.dirty=false;ui.booking=null;run();}}]);else run();}
 function go(page,id=null){guarded(()=>{ui.page=page;ui.id=id;if(page!=='appointment')ui.hcReturn=null;render();});}
 function apptCard(a){return `<article class="list-item"><h3>${date(a.date)} · ${e(timeLabel(a.time))}</h3><p>${e(doctor(a.doctor).name)} · ${e(a.type)}</p><p>${badge(a.status)} ${badge(a.payment)} <small>${a.id}</small></p><div class="actions">${btn('View appointment','appointment',a.id)}</div></article>`;}
 function dashboard(){
  const upcoming=own(appointments).filter(a=>a.status==='Scheduled').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
  const shortcuts=[['My Appointments','upcoming','',upcoming.length+' upcoming','<rect x="4" y="5" width="16" height="16" rx="2"/><path d="M8 3v4m8-4v4M4 11h16"/>'],['Prescriptions','prescriptions','',own(prescriptions).length+' signed prescriptions','<path d="M6 3h9l4 4v14H6zM14 3v5h5M9 12h7m-7 4h5"/>'],['My Records','records','',own(reports).length+' documents','<path d="M3 7h7l2 2h9v11H3zM3 7V4h7l2 3"/>'],['Medications','hc-tab','Medications','Morning, afternoon & night','<path d="M9 4a5 5 0 0 1 7 7l-5 5a5 5 0 0 1-7-7zM7 6l7 7"/>']];
  return '<div class="patient-dashboard dashboard-priority">'+head('Hello, '+person().name.split(' ')[0],'Your appointments and health records in one place.',patientServices.cards('booking'))+`<div id="dashboard-walkin" aria-live="polite"><p class="muted">Checking today’s Walk-ins…</p></div><section class="card dashboard-next" aria-labelledby="next-appointment-title">${upcoming.length?`<div class="dashboard-calendar" aria-hidden="true"><small>${date(upcoming[0].date).split(' ')[1]}</small><strong>${date(upcoming[0].date).split(' ')[0]}</strong></div>`:''}<div class="dashboard-next-copy"><h2 id="next-appointment-title">${upcoming.length?'Your next appointment':'Plan your next visit'}</h2>${upcoming.length?`<p class="dashboard-date">${date(upcoming[0].date)} at ${timeLabel(upcoming[0].time)}</p><p>${e(doctor(upcoming[0].doctor).name)} · ${e(upcoming[0].type)}</p>`:'<p>No upcoming scheduled appointment. Choose a consultation to book your next visit.</p>'}</div>${upcoming.length?btn('View next appointment','appointment',upcoming[0].id):''}</section><nav class="dashboard-shortcuts" aria-label="Your care shortcuts">${shortcuts.map(([label,action,id,hint,path])=>`<button class="dashboard-shortcut" data-action="${action}" data-id="${id}"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${path}</svg><span><strong>${label}</strong><small>${hint}</small></span><span aria-hidden="true">→</span></button>`).join('')}</nav><div class="grid dashboard-records"><section class="card"><h2>Follow-up reminders</h2>${followupList()}</section><section class="card"><h2>Recent health records</h2>${own(reports).slice(0,2).map(r=>`<article class="list-item"><h3>${e(r.title)}</h3><p>${date(r.date)} · ${e(r.source)}</p>${btn('View report','report',r.id)}</article>`).join('')||empty('No documents yet.',btn('Go to My Records','records'))}</section></div>${patientServices.cards('other')}</div>`;
 }
 const discovery=createPatientDiscovery({doctors,hospitals,e,btn,head,render,root,doctorPortrait});
 function doctorPage(){const d=doctor(ui.id);return head('Doctor profile','',btn('Back to doctors','doctors'))+`<section class="card">${doctorPortrait(d)}<h2>${d.name}</h2><p>${d.specialty}</p>${details([['Qualifications',d.qualification],['Experience',d.experience],['Clinic',facility(d).address],['Consultation fee',money(d.fee)],['Languages','English, Hindi'],['Visit types',d.types.join(', ')||'Currently unavailable']])}${d.types.length?btn('Book appointment','start',d.id,'primary'):empty('No slots available for this doctor.')}</section>`;}
 function start(id,existing=null,followup=null,preferredType=null){guarded(()=>{const d=doctor(id);if(!d.types.length)return;ui.booking={doctor:id,person:ui.person,type:existing?.type||(d.types.includes(preferredType)?preferredType:d.types[0]),date:existing?.date||followup?.due||'2026-08-05',time:'',reason:existing?.reason||followup?.reason||'',step:1,existing:existing?.id,followup:followup?.id};ui.page='booking';ui.dirty=true;render();});}
 function availableSlot(time){const b=ui.booking;return time!=='10:30'&&!appointments.some(a=>a.id!==b.existing&&a.status==='Scheduled'&&a.date===b.date&&a.time===time&&(a.doctor===b.doctor||a.person===ui.person));}
 function booking(){const b=ui.booking,d=doctor(b.doctor);return head(b.existing?'Reschedule appointment':'Book appointment',d.name+' · '+d.specialty,btn('Cancel booking','cancel-booking'))+identity()+`<ol class="steps"><li aria-current="${b.step===1?'step':'false'}">1. Choose visit</li><li aria-current="${b.step===2?'step':'false'}">2. Review</li><li>3. Confirmation</li></ol><div class="split"><section class="card">${errorBox()}${b.step===1?`<form id="booking-form" novalidate>${b.existing?`<p class="notice">Rescheduling ${e(b.existing)} keeps the doctor, visit type and payment status.</p>`:''}<div class="form-row">${select('visit-type','Visit type',b.existing?[b.type]:d.types,b.type)}${field('visit-date','Appointment date',b.date,'date',`min="${today}" max="2026-09-04"`)}</div><h2>Available times</h2><p class="muted">Clinic time · IST. Grey slots are unavailable.</p><div class="slots">${['09:30','10:00','10:30','11:00','14:00','15:00'].map(t=>`<button type="button" class="btn btn-ghost" data-action="slot" data-id="${t}" aria-pressed="${b.time===t}" ${availableSlot(t)?'':'disabled'}>${timeLabel(t)}</button>`).join('')}</div>${field('chosen-time','Selected time',timeLabel(b.time),'text','readonly')}${area('reason','Reason for visit (optional)',b.reason)}<div class="actions"><button class="btn btn-primary">Review appointment</button></div></form>`:`<h2>Review appointment</h2>${details([['Patient',person().name+' · '+person().id],['Doctor',d.name],['Hospital',facility(d).name],['Visit type',b.type],['Date',date(b.date)],['Time',timeLabel(b.time)+' IST'],['Reason',b.reason||'Not provided'],['Consultation fee',money(d.fee)],['Payment',b.existing?appt(b.existing).payment:'Pay after booking (mock)']])}<p class="notice">${b.type==='Online'?'Join information will appear in appointment details.':e(facility(d).address)+'. Check in at reception on arrival.'}</p><div class="actions">${btn('Back to choices','booking-back')}${btn(b.existing?'Confirm reschedule':'Confirm booking','confirm-booking','','primary')}</div>`}</section><aside class="card"><h2>Booking details</h2><p>${d.name}<br>${d.specialty}</p><p><b>${money(d.fee)}</b> consultation fee</p><p class="muted">Availability and fees shown are sample values. No real appointment or payment is created.</p></aside></div>`;}
 function confirmBooking(){const b=ui.booking;if(ui.page!=='booking'||!b||b.step!==2)return;if(!availableSlot(b.time)){b.step=1;render();errors([['chosen-time','This time is no longer available. Choose another time.']]);return;}let a;if(b.existing){a=appt(b.existing);a.previous=a.date+' '+a.time;a.date=b.date;a.time=b.time;a.reason=b.reason;}else{a={id:'APT-'+(2000+appointments.length),person:ui.person,doctor:b.doctor,date:b.date,time:b.time,type:b.type,status:'Scheduled',payment:'Pending',reason:b.reason,fee:doctor(b.doctor).fee,hospital:doctor(b.doctor).hospital};appointments.push(a);if(b.followup)followups.find(f=>f.id===b.followup).appointment=a.id;}ui.dirty=false;ui.booking=null;ui.id=a.id;ui.page='success';render();}
 function appointmentDetails(success=false){const a=appt(ui.id);if(!a)return head('Appointment not found')+btn('Back to appointments','appointments');return head(a.status==='Cancelled'?'Appointment cancelled':success?(a.previous?'Appointment rescheduled':'Booking confirmed'):'Appointment details',a.id,btn('Back to appointments','appointments')+healthCenter.returnButton())+identity()+`<section class="card"><h2>${doctor(a.doctor).name}</h2><p>${badge(a.status)} ${badge(a.payment)}</p>${details([['Date and time',date(a.date)+' · '+timeLabel(a.time)+' IST'],['Visit type',a.type],['Location',a.type==='Online'?'Online consultation · '+facility(doctor(a.doctor)).name:facility(doctor(a.doctor)).address],['Reason',a.reason],['Fee',money(a.fee)]])}${a.previous?`<p>Previous time: ${e(a.previous.slice(0,11)+timeLabel(a.previous.slice(11)))}</p>`:''}${a.status==='Scheduled'?`<div class="actions">${a.payment==='Pending'?btn('Pay now (mock)','payment',a.id,'primary'):''}${btn('Reschedule','reschedule',a.id)}${btn('Cancel appointment','cancel-appointment',a.id,'danger')}${a.type==='Online'?btn('View joining instructions','join-info',a.id):''}</div><div class="notice"><p>Demo progression only: preview records that would become available after the clinician completes this visit.</p>${btn('Simulate completed visit','complete-visit',a.id)}</div>`:a.status==='Completed'?`<h2>Consultation summary</h2><p>${e(a.summary)}</p><div class="actions">${btn('View signed prescription','rx',a.rx)}${btn('View patient reports','records')}${own(reports).filter(r=>r.consultation===a.id).map(r=>btn('View consultation report','report',r.id)).join('')}</div>`:'<p class="notice">This appointment is cancelled. Any paid amount is subject to the clinic’s refund review; no refund is simulated automatically.</p>'}</section>`;}
 function completeVisit(id){
  const a=appt(id);if(!a||a.status!=='Scheduled')return;
  modal('Simulate completed visit',identity()+details([['Appointment',a.id],['Doctor',doctor(a.doctor).name],['Hospital',facility(doctor(a.doctor)).name],['Visit',date(a.date)+' · '+timeLabel(a.time)+' IST']])+'<p>This advances only this sample visit to its post-consultation state. A sample summary, prescription and report will appear for this patient. No clinical assessment or signing is performed by the patient. Payment status stays unchanged.</p>',[
   {label:'Keep scheduled'},
   {label:'Confirm simulated completion',style:'primary',run:()=>{
    if(a.status!=='Scheduled')return;
    a.status='Completed';a.summary='Simulated completed consultation. Sample history and reports reviewed; consultation documents are available below. This is fictional demonstration content, not a medical assessment.';
    a.rx='RX-'+a.id;a.completedAt=new Date().toISOString();
    prescriptions.push({id:a.rx,person:a.person,date:a.date,doctor:a.doctor,consultation:a.id,body:'Sample signed prescription for this simulated encounter. No medication is prescribed in this demonstration. In the real workflow, only clinician-issued instructions appear here.'});
    reports.push({id:'DOC-'+(reports.length+1),person:a.person,consultation:a.id,title:'Consultation report · '+a.id,date:a.date,category:'Consultation report',source:facility(doctor(a.doctor)).name,body:'Fictional consultation report for '+a.id+'. The visit was completed in the demonstration. No diagnostic result or clinical advice is generated.'});
    ui.page='appointment';ui.id=a.id;render();toast('Simulated visit completed. Consultation documents are available.');
   }}
  ]);
 }
 function pay(id){const a=appt(id);if(!a||a.payment==='Paid'||a.status!=='Scheduled')return;modal('Mock payment',identity()+details([['Appointment',a.id],['Doctor',doctor(a.doctor).name],['Amount',money(a.fee)]])+'<p>No money is charged. Choose a test outcome.</p>',[{label:'Cancel'},{label:'Simulate failure',run:()=>modal('Payment unsuccessful','No charge was made. Your appointment remains scheduled with payment pending.',[{label:'Close'},{label:'Retry payment',run:()=>pay(id)}])},{label:'Simulate successful payment',style:'primary',run:()=>{if(a.payment==='Paid')return;a.payment='Paid';render();toast('Mock payment recorded for '+a.id+'.');}}]);}
 function cancelAppointment(id){const a=appt(id);modal('Cancel this appointment?',identity()+details([['Appointment',a.id],['Doctor',doctor(a.doctor).name],['Time',date(a.date)+' · '+timeLabel(a.time)]])+'<p>Your other appointments will stay unchanged. Paid bookings require clinic refund review.</p>',[{label:'Keep appointment'},{label:'Confirm cancellation',style:'danger',run:()=>{if(a.status!=='Scheduled')return;a.status='Cancelled';ui.page='appointment';render();toast('Appointment '+a.id+' cancelled.');}}]);}
 function followupList(){return own(followups).map(f=>{const a=f.appointment&&appt(f.appointment),booked=a?.status==='Scheduled';return `<article class="list-item"><h3>${date(f.due)} · ${doctor(f.doctor).name}</h3><p>${e(f.reason)}</p>${a?.status==='Completed'?badge('Completed')+' '+btn('View completed follow-up','appointment',a.id):booked?btn('View booked follow-up','appointment',a.id):btn('Book follow-up','followup-book',f.id,'primary')}</article>`;}).join('')||empty('No follow-up reminders for this family member.');}
 function recordsPage(){return head('My Records','Documents belong to '+person().name,btn('Upload document (mock)','upload','','primary'))+identity()+`<section class="card"><p class="notice">Hospital doctors can access reports through your patient record. Viewing here does not mark a report clinically reviewed.</p>${own(reports).map(r=>`<article class="list-item"><h2>${e(r.title)}</h2><p>${date(r.date)} · ${e(r.category)} · ${e(r.source)}</p><div class="actions">${btn('View document','report',r.id)}${btn('Print preview','report-print',r.id)}${r.consultation?btn('View consultation','appointment',r.consultation):''}</div></article>`).join('')||empty('No documents on record.',btn('Add a sample document','upload'))}</section>`;}
 function preview(id,rx=false){const r=(rx?prescriptions:reports).find(x=>x.id===id&&x.person===ui.person);if(!r)return;modal(rx?'Signed prescription':r.title,`<div class="paper">${identity()}<h2>${rx?r.id:e(r.title)}</h2>${details([['Issued',date(r.date)],['Source',rx?doctor(r.doctor).name:r.source],['Reference',r.id],...(r.consultation?[['Consultation',r.consultation]]:[])])}${rx?'<p><b>Signed · Read-only</b></p>':''}<p style="white-space:pre-wrap">${e(r.body)}</p><p class="muted">Sample document for UX review.</p></div>`,[{label:'Close preview'},{label:'Print',style:'primary',run:()=>{window.print();return false;}}]);}
 function upload(){modal('Upload document (mock)',identity()+errorBox()+select('sample','Sample document',[['','Choose document'],['blood','Sample blood report.pdf'],['visit','Sample visit report.pdf']])+field('document-date','Document date',today,'date')+'<p>No personal file is uploaded. Choose a sample to test this flow.</p>',[{label:'Cancel'},{label:'Add document',style:'primary',run:()=>{const sample=val('sample'),day=val('document-date'),errs=[];if(!sample)errs.push(['sample','Choose a sample document.']);if(!day||day>today)errs.push(['document-date','Choose a date on or before 04 Aug 2026.']);if(errors(errs,dialog))return false;reports.push({id:'DOC-'+(reports.length+1),person:ui.person,title:sample==='blood'?'Sample blood report':'Sample visit report',date:day,category:'Patient uploaded',source:'Patient upload (mock)',body:'Sample document added for UX review.'});render();toast('Document added for '+person().name+'.');}}]);}
 const healthAddLabels={Allergies:'Add allergy',Medications:'Add medication','Family history':'Add family history',Vaccines:'Add vaccination','Substance use':'Add substance use information'};
 function healthPage(){const tabs=Object.keys(health[ui.person]);return head('Health Profile','Patient-reported context; signed prescriptions stay read-only.')+identity()+`<div class="tabs">${tabs.map(t=>`<button class="btn btn-ghost" data-action="health-tab" data-id="${t}" aria-pressed="${ui.healthTab===t}">${e(t)}</button>`).join('')}</div><section class="card"><h2>${ui.healthTab}</h2>${health[ui.person][ui.healthTab].map(([a,b])=>`<article class="list-item"><h3>${e(a)}</h3><p>${e(b)}</p></article>`).join('')||empty('No entries recorded. This does not mean none exist.')} ${btn(healthAddLabels[ui.healthTab],'health-add','','primary')}</section>`;}
 function healthAdd(){const tab=ui.healthTab;modal(healthAddLabels[tab],identity()+errorBox()+field('entry-title',({Allergies:'Allergen',Medications:'Medication name','Family history':'Condition or family history',Vaccines:'Vaccine name','Substance use':'Substance or habit'})[tab])+area('entry-notes','Details (optional)')+'<p>Saved as patient-reported information for discussion with your doctor.</p>',[{label:'Cancel'},{label:'Save entry',style:'primary',run:()=>{if(errors(val('entry-title')?[]:[['entry-title','Enter a name for this entry.']],dialog))return false;health[ui.person][tab].push([val('entry-title'),val('entry-notes')+' · patient-reported']);render();toast('Health entry saved.');}}]);}
 function ageLabel(dob){
  if(!dob)return 'Not recorded';const [year,month,day]=dob.split('-').map(Number),[nowYear,nowMonth,nowDay]=today.split('-').map(Number);
  const years=nowYear-year-(nowMonth<month||(nowMonth===month&&nowDay<day)?1:0);
  if(years>=2)return years+' years';const months=(nowYear-year)*12+nowMonth-month-(nowDay<day?1:0);
  if(months>=1)return months+(months===1?' month':' months');const days=Math.max(0,Math.floor((Date.parse(today+'T12:00:00Z')-Date.parse(dob+'T12:00:00Z'))/86400000));return days+(days===1?' day':' days');
 }
 const bloodGroups=['Unknown','A+','A-','B+','B-','AB+','AB-','O+','O-'];
 function editBloodGroup(){modal('Edit blood group',identity()+select('blood-group','Blood group (optional)',bloodGroups,person().bloodGroup||'Unknown')+'<p>Choose Unknown if you do not know. Entries are saved as patient-reported, not laboratory-verified.</p>',[{label:'Cancel'},{label:'Save blood group',style:'primary',run:()=>{const value=val('blood-group');if(!bloodGroups.includes(value))return false;person().bloodGroup=value;render();toast('Blood group saved for '+person().name+'.');}}]);}
 function profile(){return head('Profile & Family','Manage your mock family profiles and choose whose care to view.',btn('Add family member','add-family','','primary'))+identity()+`<section class="card"><h2>Contact details</h2>${details([['Full name',person().name],['Patient ID',person().id],['Date of birth',date(person().dob)],['Age',ageLabel(person().dob)],['Blood group',!person().bloodGroup||person().bloodGroup==='Unknown'?'Unknown':person().bloodGroup+' · Patient-reported'],['Phone',person().phone],['Email',person().email]])}<div class="actions">${btn('Edit contact details','edit-profile','','primary')}${btn('Edit blood group','edit-blood-group')}</div></section><section class="card"><h2>Linked family</h2>${Object.entries(people).map(([id,p])=>`<article class="list-item"><h3>${e(p.name)}</h3><p>${e(p.id)} · ${e(p.relation)}</p>${id===ui.person?badge('Currently viewing'):btn('View care for '+p.name,'member',id)}</article>`).join('')}</section>`;}
 function addFamily(){
  const relations=['Daughter','Son','Spouse','Mother','Father','Sibling','Other'];
  modal('Add family member',errorBox()+field('family-name','Full name','','text','maxlength="100" autocomplete="off"')+select('family-relation','Relationship',[['','Choose relationship'],...relations])+field('family-dob','Date of birth','','date',`max="${today}"`)+'<p>Use fictional details. This creates a separate mock profile, not access to another person’s real records. Contact details can be added later.</p>',[
   {label:'Cancel'},
   {label:'Add family member',style:'primary',run:()=>{
    const name=val('family-name'),relation=val('family-relation'),dob=val('family-dob'),errs=[];
    if(!name||name.length>100)errs.push(['family-name','Enter a full name of up to 100 characters.']);
    if(!relations.includes(relation))errs.push(['family-relation','Choose a relationship.']);
    if(!/^\d{4}-\d{2}-\d{2}$/.test(dob)||dob<'1900-01-01'||dob>today)errs.push(['family-dob','Enter a date of birth from 01 Jan 1900 to 04 Aug 2026.']);
    if(Object.values(people).some(p=>p.name.toLowerCase()===name.toLowerCase()&&p.dob===dob))errs.push(['family-name','This family member is already listed. Select their existing profile.']);
    if(errors(errs,dialog))return false;
    const number=3000+Object.keys(people).length,id='family-'+number;
    people[id]={name,relation,dob,id:'PAT-'+number,phone:'',email:'',createdAt:new Date().toISOString()};
    health[id]={Allergies:[],Medications:[],'Family history':[],Vaccines:[],'Substance use':[]};
    const option=document.createElement('option');option.value=id;option.textContent=name+' ('+relation+')';document.getElementById('member').append(option);
    render();toast('Family member added. Choose View care for '+name+' to continue.');
   }}
  ]);
 }
 function editProfile(){modal('Edit contact details',identity()+errorBox()+field('phone','Mobile number',person().phone,'tel')+field('email','Email (optional)',person().email,'email'),[{label:'Cancel'},{label:'Save contact details',style:'primary',run:()=>{const errs=[];if(!/^\d{10}$/.test(val('phone')))errs.push(['phone','Enter a 10-digit mobile number.']);if(val('email')&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val('email')))errs.push(['email','Enter a valid email address.']);if(errors(errs,dialog))return false;person().phone=val('phone');person().email=val('email');render();toast('Contact details saved for '+person().name+'.');}}]);}
 function labPage(){return head('Lab Orders','Sample diagnostic orders for '+person().name,btn('Order lab tests (mock)','lab-order','','primary'))+identity()+`<section class="card">${own(labs).map(l=>`<article class="list-item"><h2>${e(l.title)}</h2><p>${l.id} · ${date(l.date)} · City Diagnostics</p><p>${badge(l.status)} · ${money(l.fee)}</p>${l.report?btn('View lab report','report',l.report):btn('View order','lab-detail',l.id)}</article>`).join('')||empty('No lab orders for this family member.')}</section>`;}
 function labOrder(){modal('Order lab tests (mock)',identity()+errorBox()+select('lab-test','Test',[['','Choose a test'],['cbc','Complete blood count — ₹350'],['hba1c','HbA1c — ₹450']])+field('lab-date','Collection date','2026-08-05','date')+'<p>City Diagnostics · In-centre collection. Payment is simulated at confirmation. This catalogue is a UX fixture.</p>',[{label:'Cancel'},{label:'Review lab order',style:'primary',run:()=>{const test=val('lab-test'),day=val('lab-date'),errs=[];if(!test)errs.push(['lab-test','Choose a test.']);if(!day||day<today)errs.push(['lab-date','Choose today or a future date.']);if(errors(errs,dialog))return false;const title=test==='cbc'?'Complete blood count':'HbA1c',fee=test==='cbc'?350:450;modal('Confirm mock lab order',identity()+details([['Test',title],['Collection',date(day)],['Centre','City Diagnostics'],['Total',money(fee)]])+'<p>No money is charged.</p>',[{label:'Cancel'},{label:'Confirm mock order',style:'primary',run:()=>{labs.push({id:'LAB-'+(labs.length+1),person:ui.person,title,date:day,fee,status:'Ordered'});render();toast('Mock lab order confirmed.');}}]);}}]);}
 function claim(){return head('Claim Records','Link a sample historical record to the selected family member.')+identity()+`<section class="card"><h2>Verify your details</h2><p>Identity verification is simulated. No OTP is sent and no real records are accessed.</p>${btn('Start mock verification','claim-start','','primary')}</section>`;}
 function claimStart(){modal('Mock identity verification',identity()+errorBox()+field('otp','Demo verification code')+'<p>Enter <b>123456</b> to continue the sample flow.</p>',[{label:'Cancel'},{label:'Verify code',style:'primary',run:()=>{if(errors(val('otp')==='123456'?[]:[['otp','Enter the demo code 123456.']],dialog))return false;modal('Review matching record',identity()+'<p>Sample historic visit · City Health Clinic · 01 Jul 2026</p><p>Confirm only if this is the intended patient. No real record is linked.</p>',[{label:'Not my record'},{label:'Link sample record',style:'primary',run:()=>{if(!own(reports).some(r=>r.claimed))reports.push({id:'DOC-'+(reports.length+1),person:ui.person,title:'Claimed sample visit',date:'2026-07-01',source:'City Health Clinic',category:'Historic visit',body:'Mock linked record.',claimed:true});ui.page='records';render();toast('Sample record linked.');}}]);}}]);}
 function support(){return head('Support','Appointment, billing or account help.')+`<section class="card"><h2>Contact support</h2><p>This demo saves a ticket locally; no message is sent.</p>${btn('Create support ticket','support-new','','primary')}</section><section class="card"><h2>Your tickets</h2>${own(tickets).map(t=>`<article class="list-item"><h3>${e(t.subject)}</h3><p>${t.id} · ${e(t.category)} · Open</p><p>${e(t.message)}</p></article>`).join('')||empty('No support tickets yet.')}</section>`;}
 function supportNew(){modal('Create support ticket',identity()+errorBox()+select('category','Category',['Appointment','Billing','Account','Technical'])+field('subject','Subject')+area('message','Message'),[{label:'Cancel'},{label:'Save mock ticket',style:'primary',run:()=>{const errs=[];if(!val('subject'))errs.push(['subject','Enter a subject.']);if(!val('message'))errs.push(['message','Enter a message.']);if(errors(errs,dialog))return false;tickets.push({id:'TKT-'+(tickets.length+1),person:ui.person,subject:val('subject'),message:val('message'),category:val('category')});render();toast('Mock support ticket saved. No message sent.');}}]);}
 function emergency(){return head('Emergency','This prototype cannot provide emergency assistance.')+`<section class="card"><p class="notice">For an actual emergency, contact local emergency services directly. Do not wait for a response from this demo.</p><h2>Ambulance request demonstration</h2><p>Explore a sample request without dispatching an ambulance or using your location.</p>${btn('Try request simulation','emergency-new','','primary')}</section><section class="card"><h2>Demo requests</h2>${own(requests).map(r=>`<p>${r.id} · ${e(r.location)} · Simulated request only</p>`).join('')||empty('No simulated requests.')}</section>`;}
 function emergencyNew(){modal('Simulate ambulance request',identity()+errorBox()+field('location','Pickup location')+area('context','Additional information (optional)')+'<p>No ambulance will be dispatched.</p>',[{label:'Cancel'},{label:'Save simulated request',style:'primary',run:()=>{if(errors(val('location')?[]:[['location','Enter a sample pickup location.']],dialog))return false;requests.push({id:'DEMO-'+(requests.length+1),person:ui.person,location:val('location')});render();toast('Simulation saved. No ambulance dispatched.');}}]);}
 function member(id){guarded(()=>{ui.person=id;ui.page='dashboard';ui.id=null;ui.booking=null;ui.tab='Upcoming';ui.healthTab='Overview';healthCenter.reset();document.getElementById('member').value=id;render();toast('Now viewing care for '+person().name+'.');});}
 const healthCenter=createPatientHealthCenter({ui,health,prescriptions,doctor,own,e,btn,head,identity,date,timeLabel,today,root,dialog,modal,field,select,errorBox,errors,val,render,go,toast,originalHealth:healthPage});
 const patientServices=createPatientServices({ui,discovery,doctors,own,prescriptions,doctor,person,e,btn,head,identity,details,select,errorBox,errors,val,dialog,modal,go,start,render,date});
 DemoStore.attach('patient',()=>({people,doctors,appointments,reports,prescriptions,followups,health,labs,tickets,requests,healthExtra:healthCenter.snapshot(),serviceExtra:patientServices.snapshot()}),data=>{for(const [key,target] of Object.entries({people,doctors,appointments,reports,prescriptions,followups,health,labs,tickets,requests}))if(data[key])DemoStore.replace(target,data[key]);healthCenter.restore(data.healthExtra);patientServices.restore(data.serviceExtra);});
 function render(){clearTimeout(timer);feedback.textContent='';const pages={service:patientServices.page,dashboard,doctors:discovery.page,doctor:doctorPage,booking,success:()=>appointmentDetails(true),appointment:()=>appointmentDetails(),appointments:()=>head('My Appointments','Appointments for '+person().name,btn('Book appointment','doctors','','primary'))+`<div class="tabs">${['Upcoming','Past','Cancelled'].map(t=>`<button class="btn btn-ghost" data-action="appt-tab" data-id="${t}" aria-pressed="${ui.tab===t}">${t}</button>`).join('')}</div><section class="card">${own(appointments).filter(a=>ui.tab==='Upcoming'?a.status==='Scheduled':ui.tab==='Past'?a.status==='Completed':a.status==='Cancelled').map(apptCard).join('')||empty('No '+ui.tab.toLowerCase()+' scheduled appointments.',btn('Find a Doctor','doctors'))}</section>`,records:recordsPage,prescriptions:healthCenter.rxPage,followups:()=>head('Follow-ups','Reminders from previous visits.')+identity()+`<section class="card">${followupList()}</section>`,health:healthCenter.healthPage,profile,labs:labPage,claim,support,emergency,room:()=>head('Online waiting room','Simulation only',btn('Leave waiting room','appointment',ui.id))+identity()+`<section class="card"><h2>${doctor(appt(ui.id).doctor).name}</h2><p>Appointment ${ui.id}</p><p class="notice">Previewing the waiting-room experience. No camera, microphone or connection is active.</p>${btn('Simulate doctor joining','room-connected','','primary')}</section>`};root.innerHTML=pages[ui.page]();if(ui.page==='dashboard')WalkinUI.mount({role:'patient',patient:person().id,summary:true,render});if(ui.page==='appointments'){root.insertAdjacentHTML('beforeend',WalkinUI.slot());WalkinUI.mount({role:'patient',patient:person().id,tab:ui.tab,render});}document.getElementById('page-title').textContent=titles[ui.page];document.querySelectorAll('[data-screen]').forEach(n=>{const active=n.dataset.screen===ui.page;n.classList.toggle('active',active);n.setAttribute('aria-current',active?'page':'false');});window.scrollTo(0,0);root.querySelector('h1')?.focus({preventScroll:true});bind();}
 function bind(){if(ui.page==='booking'&&ui.booking.step===1&&!ui.booking.existing){const b=ui.booking;WalkinUI.attach({role:'patient',patient:person().id,lockPatient:true,lockDoctor:true,onStage:stage=>root.querySelectorAll('.steps li').forEach((li,i)=>li.setAttribute('aria-current',i===stage-1?'step':'false')),doctorName:doctor(b.doctor).name,nodes:[root.querySelector('#booking-form')],context:()=>({patient:person().id,doctor:b.doctor,facility:doctor(b.doctor).hospital,reason:b.reason}),onScheduled:d=>{b.reason=d?.reason??b.reason;root.querySelector('#reason').value=b.reason;},onSaved:()=>{ui.dirty=false;ui.booking=null;ui.page='appointments';ui.tab='Upcoming';render();},render});}discovery.bind();healthCenter.bind();const form=root.querySelector('#booking-form');form?.addEventListener('input',ev=>{const b=ui.booking;if(ev.target.id==='reason')b.reason=ev.target.value;});form?.querySelector('#visit-type')?.addEventListener('change',ev=>{ui.booking.type=ev.target.value;ui.booking.time='';render();});form?.querySelector('#visit-date')?.addEventListener('change',ev=>{ui.booking.date=ev.target.value;ui.booking.time='';render();});form?.addEventListener('submit',ev=>{ev.preventDefault();const b=ui.booking,errs=[];if(!b.date||b.date<today||b.date>'2026-09-04')errs.push(['visit-date','Choose a date from 04 Aug to 04 Sep 2026.']);if(!b.time)errs.push(['chosen-time','Choose an available time.']);if(errors(errs))return;b.step=2;render();});}
 root.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(!el)return;const {action,id}=el.dataset;if(action==='doctor-photo'){const d=doctor(id),src=portraitPaths[id];if(src)modal(d.name+' — Photo',`<img class="doctor-photo-preview" src="${src}" alt="Portrait of ${e(d.name)}">`);return;}if(patientServices.action(action,id)||discovery.action(action)||healthCenter.action(action,id))return;if(action==='upcoming'){ui.tab='Upcoming';return go('appointments');}if(action==='add-family')return addFamily();if(action==='complete-visit')return completeVisit(id);if(action==='start')return start(id);if(action==='slot'){ui.booking.time=id;root.querySelector('#chosen-time').value=timeLabel(id);root.querySelectorAll('.slots button').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.id===id)));return;}if(action==='booking-back'){ui.booking.step=1;return render();}if(action==='confirm-booking')return confirmBooking();if(action==='cancel-booking')return go('doctors');if(action==='clear-search')return discovery.clear();if(action==='appt-tab'){ui.tab=id;return render();}if(action==='reschedule')return start(appt(id).doctor,appt(id));if(action==='cancel-appointment')return cancelAppointment(id);if(action==='payment')return pay(id);if(action==='report'||action==='report-print')return preview(id);if(action==='rx')return preview(id,true);if(action==='upload')return upload();if(action==='health-tab'){ui.healthTab=id;return render();}if(action==='health-add')return healthAdd();if(action==='edit-profile')return editProfile();if(action==='edit-blood-group')return editBloodGroup();if(action==='member')return member(id);if(action==='followup-book'){const f=followups.find(f=>f.id===id);return start(f.doctor,null,f);}if(action==='lab-order')return labOrder();if(action==='lab-detail'){const l=own(labs).find(l=>l.id===id);return modal('Lab order details',identity()+details([['Order',l.id],['Test',l.title],['Collection date',date(l.date)],['Status',l.status],['Centre','City Diagnostics']])+'<p>Visit the centre at the arranged time. Preparation instructions must come from the lab.</p>',[{label:'Close details'}]);}if(action==='claim-start')return claimStart();if(action==='support-new')return supportNew();if(action==='emergency-new')return emergencyNew();if(action==='join-info'){const a=appt(id);return modal('Online joining instructions',identity()+details([['Doctor',doctor(a.doctor).name],['Appointment',date(a.date)+' · '+timeLabel(a.time)+' IST']])+'<p>The visit is scheduled for a future date. Live joining is not available in this prototype. You can preview the waiting room.</p>',[{label:'Close instructions'},{label:'Preview waiting room',run:()=>go('room',id)}]);}if(action==='room-connected')return modal('Call experience preview','The doctor would appear here when connected. No real audio or video is transmitted.',[{label:'Back to waiting room'}]);if(titles[action])return go(action,id);});
 document.querySelectorAll('[data-screen]').forEach(n=>n.onclick=()=>go(n.dataset.screen));document.getElementById('member').onchange=ev=>{const id=ev.target.value;ev.target.value=ui.person;member(id);};document.getElementById('alerts').onclick=()=>modal('Follow-up reminders',identity()+`<p>${own(followups).length} follow-up reminder(s) for this family member.</p>`,[{label:'Close reminders'},{label:'View follow-ups',style:'primary',run:()=>go('followups')}]);document.querySelector('.switch-role').addEventListener('click',ev=>{if(ui.dirty){ev.preventDefault();guarded(()=>location.href='index.html');}});window.addEventListener('beforeunload',ev=>{if(ui.dirty){ev.preventDefault();ev.returnValue='';}});render();
})();
