(() => {
  'use strict';
  const db = window.createRoleMockStore();
  const root = document.getElementById('screen-content');
  const names = {dashboard:'Dashboard',doctors:'Doctors',appointments:'Appointments','book-appointment':'Book Appointment',checkin:'Check-in Queue',patients:'Patient Registry','register-patient':'Register New Patient',payments:'Payments','patient-detail':'Patient Details','appointment-detail':'Appointment Details','payment-success':'Payment Success','checkin-success':'Check-in Success'};
  let doctorQuery = '', bookingFromDoctors = false;
  const appointmentTimes = ['09:00','09:15','09:30','09:45','10:00','10:15','10:30','10:45','11:00','11:15','11:30','14:00'];
  const ui = {page:'dashboard',id:null,dirty:false,registryQuery:'',dateFilter:'Today',statusFilter:'All Statuses',booking:null,registration:null,origin:null,payment:null,receipt:null};
  const e = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const patient = id => db.patients.find(p=>p.id===id);
  const doctor = id => db.doctors.find(d=>d.id===id);
  const visit = id => db.visits.find(v=>v.id===id);
  const full = p => p ? `${p.first} ${p.last}` : 'Select patient';
  const dateText = d => d ? new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}) : 'Not recorded';
  const money = n => `INR ${Number(n).toFixed(2)}`;
  const age = p => Math.floor((new Date(db.date)-new Date(p.dob))/31557600000);
  const live = v => !['CANCELED','NO_SHOW','COMPLETED'].includes(v.status);
  const paymentState = v => v.refunded?'REFUNDED':v.paid>=v.fee?'PAID':v.paid>0?'PARTIALLY PAID':'PENDING';
  const badge = s => `<span class="badge badge-${['PAID','CONFIRMED','CHECKED IN','COMPLETED'].includes(s)?'green':['PENDING','PARTIALLY PAID','SCHEDULED'].includes(s)?'yellow':'gray'}">${e(s)}</span>`;
  const btn = (label,action,id='',style='ghost') => `<button type="button" class="btn btn-${style}" data-action="${action}" data-id="${e(id)}">${e(label)}</button>`;
  const head = (title,actions='') => `<div class="page-header"><h1 class="page-title-lg" tabindex="-1">${e(title)}</h1><div class="header-spacer"></div>${actions}</div>`;
  const table = (headers,rows) => `<div class="rec-table-wrap"><table class="rec-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map((cell,i)=>`<td data-label="${e(headers[i])}"><div>${cell}</div></td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}"><div class="rec-empty">No matching records.</div></td></tr>`}</tbody></table></div>`;
  const identity = v => `<b>${e(full(patient(v.patient)))}</b><br><span class="rec-muted">${e(v.patient)}</span>`;
  const details = pairs => `<div class="rec-summary">${pairs.map(([k,v])=>`<div><strong>${e(k)}</strong>${e(v)}</div>`).join('')}</div>`;
  const select = (id,label,options,value) => `<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><select class="form-control" id="${id}" name="${id}">${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${e(v)}" ${v===value?'selected':''}>${e(l)}</option>`;}).join('')}</select><div class="rec-error" id="${id}-error"></div></div>`;
  const field = (id,label,value='',type='text',placeholder='') => `<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><input class="form-control" id="${id}" name="${id}" type="${type}" value="${e(value)}" placeholder="${e(placeholder)}"><div class="rec-error" id="${id}-error"></div></div>`;
  const summaryErrors = () => '<div id="form-errors" class="rec-errors" tabindex="-1" role="alert"></div>';
  const matches = (p,q) => `${full(p)} ${p.id} ${p.phone}`.toLowerCase().includes(q.trim().toLowerCase());
  let toastTimer, dialogReturnFocus;
  function toast(text) {document.querySelector('.rec-toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='rec-toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);toastTimer=setTimeout(()=>el.remove(),4500);}
  const dialog = document.createElement('dialog');dialog.className='rec-dialog';document.body.append(dialog);
  function closeDialog(){dialog.close();if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus();}
  function modal(title,body,actions=[]){dialogReturnFocus=document.activeElement;dialog.innerHTML=`<div class="rec-dialog-header"><h2 id="dialog-title">${e(title)}</h2><button class="btn btn-ghost" data-close>Close</button></div><div class="rec-dialog-body">${body}</div><div class="rec-dialog-footer">${actions.map((a,i)=>`<button class="btn btn-${a.style||'ghost'}" data-modal="${i}">${e(a.label)}</button>`).join('')}</div>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.querySelector('[data-close]').onclick=closeDialog;dialog.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>{const action=actions[Number(b.dataset.modal)];closeDialog();action.run?.();});if(!dialog.open)dialog.showModal();}
  dialog.addEventListener('cancel',()=>{if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus();});
  function guarded(run){if(ui.dirty)modal('Discard unsaved changes?','Your changes have not been saved. Stay to continue editing, or discard them to leave.',[{label:'Keep editing'},{label:'Discard changes',style:'danger',run:()=>{ui.dirty=false;run();}}]);else run();}
  function go(page,id=null){guarded(()=>{ui.page=page;ui.id=id;ui.dirty=false;if(page==='book-appointment')bookingFromDoctors=false;if(page==='book-appointment')ui.booking={patient:id||'',doctor:'priya',date:db.date,time:'',type:'CONSULTATION',channel:'IN_PERSON',reason:'',notes:''};if(page==='register-patient'){ui.origin={page:'patients'};ui.registration={};}if(page==='payments'){ui.payment={id:id||db.visits.find(v=>live(v)&&v.paid<v.fee)?.id||'',method:'UPI',amount:'',reference:''};}render();});}
  function render(){
    root.innerHTML=pages[ui.page]();
    if(ui.page==='book-appointment'&&bookingFromDoctors){const notice=document.createElement('p');notice.className='rec-notice';notice.id='selected-doctor-notice';notice.textContent='Booking with '+doctor(ui.booking.doctor).name+' · '+doctor(ui.booking.doctor).specialty+'. Select or register the patient below.';root.querySelector('.page-header').after(notice);}
    document.getElementById('page-title').textContent=names[ui.page]||ui.page;
    document.querySelectorAll('.nav-item').forEach(n=>{n.classList.toggle('active',n.dataset.screen===ui.page);n.setAttribute('aria-current',n.dataset.screen===ui.page?'page':'false');});
    document.querySelector('.nav-badge').textContent=db.visits.filter(v=>v.date===db.date).length;
    const notificationBadge=document.querySelector('[title="Notifications"] div');
    if(notificationBadge)notificationBadge.textContent=db.visits.filter(v=>live(v)&&v.paid<v.fee).length;
    bindPage();root.querySelector('h1')?.focus({preventScroll:true});window.scrollTo({top:0});
  }
  function arrivalAction(v){if(!live(v))return badge(v.status);if(v.channel==='ONLINE')return '<span class="rec-muted">Online - No check-in</span>';if(v.arrived)return badge('CHECKED IN');if(v.date!==db.date)return '<span class="rec-muted">Check-in is available on the appointment date.</span>';return v.paid<v.fee?btn('Collect Payment','payment',v.id,'primary'):btn('Check In','checkin',v.id,'success');}
  function appointmentActions(v){return `<div class="rec-actions">${btn('View','appointment',v.id)}${live(v)?btn('Reschedule','reschedule',v.id)+(v.paid<v.fee?btn('Collect','payment',v.id,'primary'):'')+btn('Cancel','cancel-visit',v.id):''}</div>`;}
  function filteredVisits(){return db.visits.filter(v=>(ui.dateFilter==='All'||(ui.dateFilter==='Today'?v.date===db.date:v.date>=db.date&&v.date<='2026-08-10'))&&(ui.statusFilter==='All Statuses'||v.status===ui.statusFilter));}
  const pages = {
    doctors(){return head('Doctors')+'<p class="rec-notice">Find a doctor by name or specialty, then book an appointment for your patient.</p><div class="rec-actions">'+field('doctor-search','Search doctors',doctorQuery,'search','Search by doctor name or specialty')+btn('Clear search','clear-doctor-search')+'</div><div id="doctor-results">'+doctorRows()+'</div>';},
    dashboard(){const todays=db.visits.filter(v=>v.date===db.date);return `<div class="stat-grid">${[[todays.length,"Today's Appointments",'appointments'],[todays.filter(v=>v.arrived).length,'Checked In','checkin'],[todays.filter(v=>live(v)&&!v.arrived&&v.channel==='IN_PERSON').length,'Waiting','checkin'],[todays.filter(v=>live(v)&&v.paid<v.fee).length,'Pending Payment','payments']].map(([n,l,a])=>`<button class="stat-card" data-action="nav" data-id="${a}"><div class="stat-value">${n}</div><div class="stat-label">${l}</div></button>`).join('')}</div><div class="card"><h1 class="card-title" tabindex="-1">Today's Queue</h1>${table(['Time','Patient','Doctor','Type','Status','Payment','Actions'],todays.map(v=>[e(v.time),identity(v),e(doctor(v.doctor).name),v.channel==='ONLINE'?'Online':e(v.reason==='Follow-up'?'Follow-up':'Consultation'),badge(v.arrived?'CHECKED IN':v.status),badge(paymentState(v)),arrivalAction(v)]).concat([['11:00','<b>New Patient</b>','Dr. Amit Joshi','Walk-in','—','—',btn('Book Now','book','','ghost')]]))}</div>`;},
    appointments(){return head('All Appointments',`<div class="rec-actions">${select('date-filter','Date',['Today','This Week','All'],ui.dateFilter)}${select('status-filter','Status',['All Statuses','SCHEDULED','CONFIRMED','COMPLETED','CANCELED','NO_SHOW','RESCHEDULED'],ui.statusFilter)}${btn('New Appointment','book','','primary')}</div>`)+table(['Date/Time','Patient','Doctor','Type/Channel','Status','Payment','Actions'],filteredVisits().map(v=>[`${dateText(v.date)}<br>${e(v.time)}`,identity(v),e(doctor(v.doctor).name),e(v.type+' / '+v.channel),badge(v.arrived?'CHECKED IN':v.status),badge(paymentState(v)),appointmentActions(v)]));},
    checkin(){return head('Check-in Queue')+'<p class="rec-notice">Confirm arrival for in-person appointments after payment. Online appointments do not require physical check-in.</p>'+table(['Time','Patient','Doctor','Status','Payment','Actions'],db.visits.filter(v=>v.date===db.date).map(v=>[e(v.time),identity(v),e(doctor(v.doctor).name),badge(v.arrived?'CHECKED IN':v.status),badge(paymentState(v)),v.channel==='ONLINE'||!live(v)||v.arrived?arrivalAction(v):`<div class="rec-actions">${v.paid<v.fee?btn('Collect Payment First','payment',v.id,'primary'):btn('Confirm Check-in','checkin',v.id,'success')}${btn('No Show','no-show',v.id)}</div>`]));},
    patients(){return head('Patient Registry',btn('Register New Patient','register','','primary'))+field('registry-search','Search patients',ui.registryQuery,'search','Search by name, phone, or PAT ID...')+`<div id="registry-results">${registryRows()}</div>`;},
    'patient-detail'(){const p=patient(ui.id);return head(full(p),`<div class="rec-actions">${btn('Back to Patient Registry','nav','patients')}${btn('Edit','edit',p.id)}${btn('Book','book',p.id,'primary')}</div>`)+`<div class="card">${details([['Patient ID',p.id],['Name',full(p)],['Phone',p.phone],['Gender/Age',`${p.gender}, ${age(p)}y`],['Blood Group',p.blood||'Not recorded'],['Date of Birth',dateText(p.dob)],['Email',p.email||'Not recorded'],['Address',p.address||'Not recorded']])}</div><div class="card"><h2 class="card-title">Appointment History</h2>${table(['Date/Time','Doctor','Status','Payment','Actions'],db.visits.filter(v=>v.patient===p.id).map(v=>[dateText(v.date)+' '+e(v.time),e(doctor(v.doctor).name),badge(v.status),badge(paymentState(v)),btn('View','appointment',v.id)]))}</div>`;},
    'appointment-detail'(){const v=visit(ui.id);return head('Appointment Details',btn('Back to Appointments','nav','appointments'))+`<div class="card">${visitSummary(v)}<div class="rec-actions rec-form-footer">${live(v)?btn('Reschedule','reschedule',v.id)+btn('Cancel','cancel-visit',v.id):''}${live(v)&&v.paid<v.fee?btn('Collect Payment','payment',v.id,'primary'):arrivalAction(v)}${btn('View Bill','bill',v.id)}</div></div>`;},
    'register-patient'(){const p=ui.registration;return head(p.id?'Edit Patient':'Register New Patient')+'<div class="wizard-steps"><div class="wizard-step active">1. Basic Info</div><div class="wizard-step">2. Contact</div><div class="wizard-step">3. Medical</div></div>'+`<form id="patient-form" novalidate><div class="card"><h2 class="card-title">Basic Information</h2>${summaryErrors()}<div class="form-row-3">${field('first','First Name *',p.first,'text','First name')}${field('last','Last Name *',p.last,'text','Last name')}${select('gender','Gender *',[['','Select'],'MALE','FEMALE','OTHER'],p.gender||'')}</div><div class="form-row-3">${field('dob','Date of Birth *',p.dob,'date')}${select('blood','Blood Group',[['','Select'],'A+','A-','B+','B-','AB+','AB-','O+','O-'],p.blood||'')}${select('marital','Marital Status',[['','Select'],'Single','Married','Divorced','Widowed'],p.marital||'')}</div><div class="form-row">${field('phone','Contact Phone *',p.phone,'tel','10-digit mobile')}${field('email','Email',p.email,'email','Optional email')}</div><div class="form-row">${field('aadhar','Aadhar Number',p.aadhar,'text','12-digit Aadhar (optional)')}${field('emergencyPhone','Emergency Contact Phone',p.emergencyPhone,'tel','Emergency contact')}</div>${field('address','Address',p.address,'text','Full address')}<div class="form-row">${select('category','Patient Category',['General','Senior Citizen','Child','Staff','VIP'],p.category||'General')}${field('insurance','Insurance ID',p.insurance,'text','If insured')}</div><div class="rec-actions rec-form-footer"><button class="btn btn-primary" type="submit">Save and Continue</button>${btn('Cancel','registration-cancel')}</div></div></form>`;},
    'book-appointment'(){const b=ui.booking;return head(b.id?'Reschedule Appointment':'Book New Appointment')+`<div class="wizard-steps">${['Select Patient','Select Doctor','Pick Date/Slot','Confirm and Pay'].map((s,i)=>`<a class="wizard-step ${i===0?'active':''}" href="#booking-step-${i}">${i+1}. ${s}</a>`).join('')}</div><form id="booking-form" novalidate>${summaryErrors()}<section class="card" id="booking-step-0"><h2 class="card-title">Step 1: Patient Selection</h2><div class="form-row">${field('booking-search','Search Patient (Name or Phone)','','search','Type name, phone number or PAT ID...')}<div><label class="form-label">Or Register New</label>${btn('Register New Patient','register-booking')}</div></div><div id="booking-patients">${bookingPatients('')}</div><div class="rec-error" id="booking-patients-error"></div></section><section class="card" id="booking-step-1"><h2 class="card-title">Step 2: Select Doctor</h2><div class="form-row">${select('organization','Organization',[db.clinic],db.clinic)}${select('doctor','Doctor',db.doctors.map(d=>[d.id,`${d.name} (${d.specialty})`]),b.doctor)}</div><div class="form-row">${select('type','Appointment Type',['CONSULTATION','DIAGNOSIS'],b.type)}${select('channel','Channel',['IN_PERSON','ONLINE'],b.channel)}</div>${field('reason','Reason for Visit',b.reason,'text','e.g. Fever, Follow-up')}</section><section class="card" id="booking-step-2"><h2 class="card-title">Step 3: Pick Date and Time Slot</h2>${field('date','Date',b.date,'date')}<div class="form-label">Available Slots</div><div id="booking-slots">${slots()}</div><div class="rec-error" id="booking-slots-error"></div><p class="rec-muted">Struck-through = booked · Blue = selected · White = available. Sundays are closed in this mock schedule.</p>${field('notes','Notes',b.notes,'text','Internal notes (not visible to patient)')}</section><section class="card" id="booking-step-3"><h2 class="card-title">Step 4: Confirm and Payment</h2><div id="booking-summary">${bookingSummary()}</div><div class="rec-actions rec-form-footer">${b.id?btn('Confirm Reschedule','submit-booking','reschedule','primary'):btn('Proceed to Payment','submit-booking','pay','primary')}${b.id?'':btn('Book Without Payment (Schedule only)','submit-booking','schedule')}${btn('Cancel','booking-cancel')}</div></section></form>`;},
    payments(){const pay=ui.payment;const v=visit(pay.id);return head('Payment Collection')+`<form id="payment-form" novalidate><div class="card"><h2 class="card-title">Select Appointment</h2>${summaryErrors()}${select('payment-visit','Patient',[['','Select appointment'],...db.visits.filter(x=>live(x)).map(x=>[x.id,`${full(patient(x.patient))} (${x.patient}) - ${dateText(x.date)} ${x.time} - ${doctor(x.doctor).name}`])],pay.id)}${v?`<div class="form-group"><label class="form-label" for="payment-doctor">Doctor</label><input id="payment-doctor" class="form-control" value="${e(doctor(v.doctor).name)}" readonly></div>`:''}</div>${v?`<div class="card"><h2 class="card-title">Payment for Appointment ${e(v.id)}</h2>${visitSummary(v)}<div class="rec-form-footer">${select('method','Payment Method',[['UPI','UPI (QR Code / VPA)'],['GATEWAY','Razorpay Gateway (Card/UPI/NetBanking)'],['CASH','Cash'],['PENDING','Pay at Center (mark pending)']],pay.method)}</div>${v.paid>=v.fee?`<p class="rec-notice">This appointment is fully paid.</p>${btn('View Bill','bill',v.id)}`:`${pay.method!=='PENDING'?field('amount','Amount (INR)',pay.amount===''?v.fee-v.paid:pay.amount,'number'):''}${['UPI','GATEWAY'].includes(pay.method)?field('reference','Reference / UTR',pay.reference,'text','Transaction reference (for UPI/Card)'):''}${pay.method==='UPI'?'<div class="rec-notice"><b>UPI Payment Details</b><br>VPA: cityhealthclinic@upi<br>Payee Name: City Health Clinic<br>Mock payment only — no money is transferred.</div>':pay.method==='GATEWAY'?'<p class="rec-notice">Mock gateway payment. Confirming records a simulated payment; no checkout is opened.</p>':''}<div class="rec-actions rec-form-footer"><button class="btn btn-success" type="submit">${pay.method==='PENDING'?'Save as Pending':'Confirm Payment Received'}</button>${btn('Cancel','payment-cancel')}</div>`}</div>`:'<div class="rec-empty">Select an appointment to view payment details.</div>'}</form>`;},
    'payment-success'(){const r=ui.receipt;return `<div class="card rec-receipt">${head('Payment Successful')}<p class="rec-muted">Mock payment recorded</p>${receiptBody(r)}<h2 class="card-title rec-form-footer">Share Receipt</h2><div class="rec-actions">${btn('WhatsApp','share','WhatsApp')}${btn('SMS','share','SMS')}${btn('Preview Receipt','receipt-preview')}</div><div class="rec-actions rec-form-footer">${btn('Go to Check-in','nav','checkin','primary')}${btn('Done','nav','dashboard')}</div></div>`;},
    'checkin-success'(){const v=visit(ui.id);return `<div class="card rec-receipt">${head('Check-in Successful')}<p class="rec-notice">${e(full(patient(v.patient)))} is checked in. Token ${e(v.token)}.</p>${visitSummary(v)}<div class="rec-actions rec-form-footer">${btn('Back to Queue','nav','checkin','primary')}${btn('Dashboard','nav','dashboard')}</div></div>`;}
  };
  function visitSummary(v){return details([['Patient',`${full(patient(v.patient))} (${v.patient})`],['Appointment',v.id],['Doctor',doctor(v.doctor).name],['Date/Time',`${dateText(v.date)}, ${v.time}`],['Type/Channel',`${v.type} / ${v.channel}`],['Status',v.arrived?'CHECKED IN':v.status],['Fee',money(v.fee)],['Paid / Balance',`${money(v.paid)} / ${money(Math.max(0,v.fee-v.paid))}`]]);}
  function nextDoctorSlot(id){for(let offset=0;offset<7;offset++){const date=new Date(db.date+'T12:00:00');date.setDate(date.getDate()+offset);if(date.getDay()===0)continue;const day=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');const time=appointmentTimes.find(t=>!db.visits.some(v=>v.doctor===id&&v.date===day&&v.time===t&&live(v)));if(time)return dateText(day)+', '+time;}return 'No slots in the next 7 days';}
  function doctorRows(){const list=db.doctors.filter(d=>(d.name+' '+d.specialty).toLowerCase().includes(doctorQuery.trim().toLowerCase()));return `<p class="rec-muted" role="status">${list.length} doctor${list.length===1?'':'s'} found · Availability follows the mock schedule.</p>`+(list.length?table(['Doctor','Specialty','Consultation fee','Next available slot','Actions'],list.map(d=>[`<b>${e(d.name)}</b>`,e(d.specialty),money(d.fee),nextDoctorSlot(d.id),btn('Book Appointment','book-doctor',d.id,'primary')])):'<p class="rec-notice">No doctors match your search. Try another name or specialty, or clear your search.</p>');}
  function registryRows(){return table(['ID','Name','Phone','Gender/Age','Blood Group','Last Visit','Actions'],db.patients.filter(p=>matches(p,ui.registryQuery)).map(p=>[e(p.id),`<b>${e(full(p))}</b>`,e(p.phone),`${e(p.gender)}, ${age(p)}y`,e(p.blood||'Not recorded'),dateText(p.lastVisit),`<div class="rec-actions">${btn('View','patient',p.id)}${btn('Edit','edit',p.id)}${btn('Book','book',p.id)}</div>`]));}
  function bookingPatients(q){return table(['Select','Name','Phone','Gender/Age','ID'],db.patients.filter(p=>matches(p,q)).map(p=>[`<input type="radio" name="selected-patient" value="${e(p.id)}" aria-label="Select ${e(full(p))} ${e(p.id)}" ${ui.booking.patient===p.id?'checked':''}>`,e(full(p)),e(p.phone),`${p.gender}, ${age(p)}y`,e(p.id)]));}
  function slots(){const b=ui.booking;const closed=!b.date||new Date(b.date+'T12:00:00').getDay()===0||b.date<db.date;return closed?'<p class="rec-notice">No available slots. Choose another date.</p>':`<div class="rec-actions">${appointmentTimes.map(t=>{const busy=db.visits.some(v=>v.id!==b.id&&v.doctor===b.doctor&&v.date===b.date&&v.time===t&&live(v));return `<button type="button" class="rec-slot" data-slot="${t}" aria-pressed="${b.time===t}" ${busy?'disabled':''}>${t}</button>`;}).join('')}</div>`;}
  function bookingSummary(){const b=ui.booking;return details([['Patient',b.patient?`${full(patient(b.patient))} (${b.patient})`:'Select patient'],['Doctor',doctor(b.doctor).name],['Date/Time',`${dateText(b.date)}, ${b.time||'Select slot'}`],['Type',b.type+' / '+b.channel],['Fee',money(b.id?visit(b.id).fee:doctor(b.doctor).fee)],['Org',db.clinic]]);}
  function receiptBody(r){const v=visit(r.visit);return `<h2 class="card-title rec-form-footer">${e(db.clinic)}</h2><p class="rec-muted">123, MG Road, Bangalore 560001</p><p class="rec-muted">Receipt #${e(r.id)}</p><div class="rec-form-footer">${details([['Patient',`${full(patient(v.patient))} (${v.patient})`],['Doctor',doctor(v.doctor).name],['Date/Time',dateText(v.date)+', '+v.time],['Method',r.method],['Reference',r.reference||'Not applicable'],['Recorded',dateText(db.date)],['Appointment',v.id],['Balance after payment',money(r.balance)]])}</div><div class="rec-receipt-total">Total Paid ${money(r.amount)}</div>`;}
  function formErrors(errors){root.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));root.querySelectorAll('.rec-error').forEach(el=>el.textContent='');const box=root.querySelector('#form-errors');box.innerHTML=Object.entries(errors).map(([id,msg])=>`<a href="#${id}">${e(msg)}</a>`).join('');for(const [id,msg] of Object.entries(errors)){const el=document.getElementById(id);el?.setAttribute('aria-invalid','true');el?.setAttribute('aria-describedby',id+'-error');const error=document.getElementById(id+'-error');if(error)error.textContent=msg;}if(Object.keys(errors).length){box.focus();box.scrollIntoView({block:'center'});return true;}return false;}
  function bindPage(){
    root.querySelector('#doctor-search')?.addEventListener('input',event=>{doctorQuery=event.target.value;root.querySelector('#doctor-results').innerHTML=doctorRows();});
    root.querySelector('#registry-search')?.addEventListener('input',event=>{ui.registryQuery=event.target.value;root.querySelector('#registry-results').innerHTML=registryRows();});
    for(const id of ['date-filter','status-filter'])root.querySelector('#'+id)?.addEventListener('change',event=>{ui[id==='date-filter'?'dateFilter':'statusFilter']=event.target.value;render();});
    root.querySelector('#patient-form')?.addEventListener('input',event=>{ui.registration[event.target.name]=event.target.value;ui.dirty=true;});
    root.querySelector('#patient-form')?.addEventListener('change',event=>{ui.registration[event.target.name]=event.target.value;ui.dirty=true;});
    root.querySelector('#patient-form')?.addEventListener('submit',event=>{event.preventDefault();savePatient();});
    root.querySelector('#booking-search')?.addEventListener('input',event=>{root.querySelector('#booking-patients').innerHTML=bookingPatients(event.target.value);});
    root.querySelector('#booking-form')?.addEventListener('change',event=>{const t=event.target;if(t.name==='selected-patient')ui.booking.patient=t.value;else if(['doctor','date','type','channel','organization'].includes(t.name)){if(t.name!=='organization')ui.booking[t.name]=t.value;if(t.name==='doctor'&&root.querySelector('#selected-doctor-notice'))root.querySelector('#selected-doctor-notice').textContent='Booking with '+doctor(t.value).name+' · '+doctor(t.value).specialty+'. Select or register the patient below.';if(['doctor','date'].includes(t.name)){ui.booking.time='';root.querySelector('#booking-slots').innerHTML=slots();}}else return;ui.dirty=true;root.querySelector('#booking-summary').innerHTML=bookingSummary();});
    root.querySelector('#booking-form')?.addEventListener('input',event=>{if(['reason','notes'].includes(event.target.name)){ui.booking[event.target.name]=event.target.value;ui.dirty=true;}});
    root.querySelector('#booking-form')?.addEventListener('submit',event=>event.preventDefault());
    root.querySelector('#payment-visit')?.addEventListener('change',event=>{const id=event.target.value;guarded(()=>{ui.dirty=false;ui.payment={id,method:'UPI',amount:'',reference:''};render();});if(ui.dirty)event.target.value=ui.payment.id;});
    root.querySelector('#method')?.addEventListener('change',event=>{ui.payment.method=event.target.value;ui.payment.reference='';ui.dirty=true;render();});
    root.querySelector('#payment-form')?.addEventListener('input',event=>{if(['amount','reference'].includes(event.target.name)){ui.payment[event.target.name]=event.target.value;ui.dirty=true;}});
    root.querySelector('#payment-form')?.addEventListener('submit',event=>{event.preventDefault();savePayment();});
  }
  function savePatient(allowDuplicate=false){const p=ui.registration;const errors={};for(const [id,label] of [['first','First name'],['last','Last name'],['gender','Gender'],['dob','Date of birth'],['phone','Contact phone']])if(!p[id]?.trim())errors[id]=`${label} is required.`;if(p.phone&&!/^\d{10}$/.test(p.phone))errors.phone='Enter a 10-digit contact phone.';if(p.dob&&p.dob>db.date)errors.dob='Date of birth cannot be after the scenario date.';if(p.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))errors.email='Enter a valid email or leave it empty.';if(p.aadhar&&!/^\d{12}$/.test(p.aadhar))errors.aadhar='Enter 12 digits or leave this optional field empty.';if(p.emergencyPhone&&!/^\d{10}$/.test(p.emergencyPhone))errors.emergencyPhone='Enter 10 digits or leave this optional field empty.';if(formErrors(errors))return;const duplicate=db.patients.find(x=>x.id!==p.id&&(x.phone===p.phone||(full(x).toLowerCase()===full(p).toLowerCase()&&x.dob===p.dob)));if(duplicate&&!allowDuplicate){modal('Possible duplicate patient',`${e(full(duplicate))} (${e(duplicate.id)}) has matching details. A shared phone can belong to different family members. Confirm this is a distinct patient before creating another record.`,[{label:'Inspect existing patient',run:()=>modal('Existing patient',details([['Name',full(duplicate)],['ID',duplicate.id],['Phone',duplicate.phone],['Date of Birth',dateText(duplicate.dob)]]),[{label:'Back to registration'},{label:'Use existing patient',style:'primary',run:()=>finishPatient(duplicate,false)}])},{label:'Continue as distinct patient',style:'primary',run:()=>savePatient(true)},{label:'Keep editing'}]);return;}const isNew=!p.id;const saved={...p,first:p.first.trim(),last:p.last.trim(),id:p.id||`PAT-${db.nextPatient++}`};if(isNew)db.patients.push(saved);else Object.assign(patient(p.id),saved);finishPatient(saved,true);}
  function finishPatient(p,saved){ui.dirty=false;const origin=ui.origin;if(origin?.page==='book-appointment'){ui.booking=origin.booking;ui.booking.patient=p.id;ui.page='book-appointment';ui.dirty=true;}else{ui.page='patient-detail';ui.id=p.id;}render();toast(saved?`Patient saved: ${full(p)} (${p.id}).`:`Selected ${full(p)} (${p.id}).`);}
  function submitBooking(mode){const b=ui.booking;const errors={};if(!b.patient)errors['booking-patients']='Select a patient.';if(!b.date||b.date<db.date)errors.date='Choose an available date on or after the scenario date.';if(!b.time)errors['booking-slots']='Select an available time slot.';if(b.time&&db.visits.some(v=>v.id!==b.id&&live(v)&&v.date===b.date&&v.time===b.time&&v.doctor===b.doctor))errors['booking-slots']='This slot is booked. Choose another slot.';if(formErrors(errors))return;const save=()=>{let v;if(b.id){v=visit(b.id);Object.assign(v,b,{status:'RESCHEDULED',arrived:false});}else{v={...b,id:`APT-${db.nextVisit++}`,status:'SCHEDULED',arrived:false,fee:doctor(b.doctor).fee,paid:0};db.visits.push(v);}ui.dirty=false;ui.booking=null;if(mode==='pay'){ui.page='payments';ui.payment={id:v.id,method:'UPI',amount:'',reference:''};}else{ui.page='appointment-detail';ui.id=v.id;}render();toast(mode==='reschedule'?'Appointment rescheduled.':'Appointment booked.');};if(b.id)modal('Confirm Reschedule',bookingSummary(),[{label:'Keep editing'},{label:'Confirm Reschedule',style:'primary',run:save}]);else save();}
  function savePayment(){const pay=ui.payment,v=visit(pay.id);if(!v)return;if(pay.method==='PENDING'){ui.dirty=false;go('appointment-detail',v.id);toast(v.paid?'Remaining balance stays pending.':'Payment stays pending.');return;}const amount=Number(pay.amount===''?v.fee-v.paid:pay.amount);const errors={};if(!Number.isFinite(amount)||amount<=0||amount>v.fee-v.paid||Math.round(amount*100)!==amount*100)errors.amount='Enter an amount above zero, up to the balance, with at most two decimals.';if(['UPI','GATEWAY'].includes(pay.method)&&!pay.reference.trim())errors.reference='Enter the mock transaction reference.';if(formErrors(errors))return;v.paid=Math.round((v.paid+amount)*100)/100;const r={id:`INV-2026-${db.nextReceipt++}`,visit:v.id,amount,balance:v.fee-v.paid,method:pay.method,reference:pay.reference,date:db.date};db.receipts.push(r);ui.receipt=r;ui.dirty=false;ui.page='payment-success';render();}
  function confirmStatus(id,status){const v=visit(id);modal(status==='CANCELED'?'Cancel Appointment':'Mark No Show',`${e(full(patient(v.patient)))} (${e(v.patient)}) · ${dateText(v.date)} ${e(v.time)} · ${e(doctor(v.doctor).name)}. ${status==='CANCELED'&&v.paid?'Existing payment is retained for billing review; no automatic refund.':''}`,[{label:'Keep appointment'},{label:status==='CANCELED'?'Cancel Appointment':'Mark No Show',style:'danger',run:()=>{v.status=status;v.arrived=false;render();toast(status==='CANCELED'?'Appointment cancelled.':'Appointment marked no-show.');}}]);}
  function actions(action,id){
    if(action==='clear-doctor-search'){doctorQuery='';root.querySelector('#doctor-search').value='';root.querySelector('#doctor-results').innerHTML=doctorRows();root.querySelector('#doctor-search').focus();return;}
    if(action==='book-doctor')return guarded(()=>{bookingFromDoctors=true;ui.booking={patient:'',doctor:id,date:db.date,time:'',type:'CONSULTATION',channel:'IN_PERSON',reason:'',notes:''};ui.page='book-appointment';ui.dirty=false;render();});
    if(action==='nav')return go(id);
    if(action==='patient')return go('patient-detail',id);
    if(action==='appointment')return go('appointment-detail',id);
    if(action==='book')return go('book-appointment',id);
    if(action==='payment')return go('payments',id);
    if(action==='register')return go('register-patient');
    if(action==='edit')return guarded(()=>{ui.registration={...patient(id)};ui.origin={page:'patient-detail',id};ui.page='register-patient';render();});
    if(action==='register-booking'){ui.origin={page:'book-appointment',booking:{...ui.booking}};ui.registration={};ui.page='register-patient';ui.dirty=false;return render();}
    if(action==='registration-cancel')return guarded(()=>{ui.dirty=false;if(ui.origin?.page==='book-appointment'){ui.booking=ui.origin.booking;ui.page='book-appointment';ui.dirty=true;render();}else go(ui.origin?.page||'patients',ui.origin?.id);});
    if(action==='booking-cancel')return go(bookingFromDoctors?'doctors':'appointments');
    if(action==='payment-cancel')return go('dashboard');
    if(action==='submit-booking')return submitBooking(id);
    if(action==='reschedule')return guarded(()=>{bookingFromDoctors=false;ui.booking={...visit(id)};ui.page='book-appointment';ui.dirty=false;render();});
    if(action==='cancel-visit')return confirmStatus(id,'CANCELED');
    if(action==='no-show')return confirmStatus(id,'NO_SHOW');
    if(action==='checkin'){const v=visit(id);return modal('Confirm Check-in',visitSummary(v),[{label:'Cancel'},{label:'Confirm Check-in',style:'success',run:()=>{v.arrived=true;v.status='CONFIRMED';v.token=`T-${String(db.visits.filter(x=>x.arrived).length).padStart(2,'0')}`;ui.page='checkin-success';ui.id=v.id;render();}}]);}
    if(action==='bill'){const v=visit(id);return modal('Bill Preview',`<h3>${e(db.clinic)}</h3><p>Bill ${e(v.id.replace('APT','BILL'))}</p>${visitSummary(v)}<p class="rec-muted">Mock bill preview</p>`,[{label:'Close preview'}]);}
    if(action==='receipt-preview')return modal('Receipt Preview',receiptBody(ui.receipt),[{label:'Close preview'}]);
    if(action==='share')return modal('Share Receipt',`Mock ${e(id)} receipt for ${e(full(patient(visit(ui.receipt.visit).patient)))} will be shown as shared. No message will be sent.`,[{label:'Cancel'},{label:'Simulate sharing',style:'primary',run:()=>toast(`Receipt shared via ${id} (mock).`)}]);
  }
  root.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(b){event.preventDefault();actions(b.dataset.action,b.dataset.id);}const slot=event.target.closest('[data-slot]');if(slot&&!slot.disabled){ui.booking.time=slot.dataset.slot;ui.dirty=true;root.querySelector('#booking-slots').innerHTML=slots();root.querySelector('#booking-summary').innerHTML=bookingSummary();}});
  document.querySelectorAll('.nav-item').forEach(n=>{n.setAttribute('role','button');n.tabIndex=0;n.addEventListener('click',()=>go(n.dataset.screen));n.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();go(n.dataset.screen);}});});
  const toggle=document.querySelector('[title="Toggle sidebar"]');toggle.setAttribute('role','button');toggle.tabIndex=0;toggle.setAttribute('aria-label','Toggle sidebar');toggle.onclick=()=>{const collapsed=document.querySelector('.app').classList.toggle('collapsed');toggle.setAttribute('aria-expanded',String(!collapsed));};toggle.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();toggle.click();}};
  const notifications=document.querySelector('[title="Notifications"]');notifications.setAttribute('role','button');notifications.tabIndex=0;notifications.setAttribute('aria-label','Notifications');notifications.onclick=()=>modal('Notifications',db.visits.filter(v=>live(v)&&v.paid<v.fee).map(v=>`<p>${e(full(patient(v.patient)))} · ${e(v.id)} · payment pending</p>`).join('')||'<p>No pending payment notifications.</p>',[{label:'View Payments',style:'primary',run:()=>go('payments')},{label:'Close'}]);notifications.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();notifications.click();}};
  const search=document.querySelector('.topbar input');search.setAttribute('aria-label','Search patients, appointments');search.parentElement.classList.add('topbar-search');const results=document.createElement('div');results.className='search-results';results.hidden=true;search.parentElement.append(results);
  search.addEventListener('input',()=>{const q=search.value.trim();results.hidden=!q;if(!q)return;const patients=db.patients.filter(p=>matches(p,q));const visits=db.visits.filter(v=>`${v.id} ${full(patient(v.patient))}`.toLowerCase().includes(q.toLowerCase()));results.innerHTML=patients.map(p=>`<button data-search-patient="${p.id}">${e(full(p))} · ${p.id}</button>`).join('')+visits.map(v=>`<button data-search-visit="${v.id}">${v.id} · ${e(full(patient(v.patient)))} · ${dateText(v.date)}</button>`).join('')+(!patients.length&&!visits.length?'<p>No matching patients or appointments.</p>':'')+'<button data-search-close>Close results</button>';});
  results.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;results.hidden=true;search.value='';if(b.dataset.searchPatient)go('patient-detail',b.dataset.searchPatient);if(b.dataset.searchVisit)go('appointment-detail',b.dataset.searchVisit);});search.addEventListener('keydown',event=>{if(event.key==='Escape')results.hidden=true;});
  document.querySelector('.switch-role').addEventListener('click',event=>{if(ui.dirty){event.preventDefault();guarded(()=>location.href='index.html');}});
  window.addEventListener('beforeunload',event=>{if(ui.dirty){event.preventDefault();event.returnValue='';}});
  const note=document.createElement('p');note.className='rec-scenario';note.textContent='Mock scenario: 04 Aug 2026. Changes reset when this page reloads.';document.querySelector('main').append(note);
  render();
})();
