(() => {
  'use strict';
  const db = window.createRoleMockStore();
  const root = document.getElementById('screen-content');
  const names = {dashboard:'Dashboard',doctors:'Doctors',appointments:'Appointments','book-appointment':'Book Appointment',checkin:'Check-in Queue',patients:'Patient Registry','register-patient':'Register New Patient',payments:'Payments','patient-detail':'Patient Details','appointment-detail':'Appointment Details','payment-success':'Payment Success','checkin-success':'Check-in Success'};
  let doctorQuery = '', bookingFromDoctors = false;
  const appointmentTimes = ['09:00','09:15','09:30','09:45','10:00','10:15','10:30','10:45','11:00','11:15','11:30','14:00'];
  const ui = {page:'dashboard',id:null,dirty:false,registryQuery:'',dateFilter:'Today',statusFilter:'All Statuses',queueDoctor:'all',queueStatus:'all',queueOrder:'time',booking:null,bookingStep:0,registration:null,origin:null,payment:null,paymentOrigin:null,receipt:null,walkin:false};
  const e = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const patient = id => db.patients.find(p=>p.id===id);
  const doctor = id => db.doctors.find(d=>d.id===id);
  const visit = id => db.visits.find(v=>v.id===id);
  const full = p => p ? `${p.first} ${p.last}` : 'Select patient';
  const dateText = d => d ? new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}) : 'Not recorded';
  const money = n => `INR ${Number(n).toFixed(2)}`;
  const age = p => Math.floor((new Date(db.date)-new Date(p.dob))/31557600000);
  const live = v => !['CANCELED','NO_SHOW','COMPLETED'].includes(v.status);
  const paymentState = v => v.resolution?.type==='REFUND'?'REFUNDED':v.resolution?.type==='CREDIT'?'CREDITED':v.resolution?.type==='TRANSFER'?'TRANSFERRED':v.refunded?'REFUNDED':v.paid>=v.fee?'PAID':v.paid>0?'PARTIALLY PAID':'PENDING';
  const statusLabel = s => ({IN_PERSON:'In person',ONLINE:'Online',NO_SHOW:'No show',PARTIALLY_PAID:'Partially paid',CANCELED:'Canceled',CHECKED_IN:'Checked in',AWAITING_NURSE:'Awaiting Nurse',HANDOFF_SENT:'Handoff sent',PENDING:'Pending',PAID:'Paid',REFUNDED:'Refunded',CREDITED:'Credited',TRANSFERRED:'Transferred',WAITING:'Waiting',PROMOTED:'Promoted',SCHEDULED:'Scheduled',CONFIRMED:'Confirmed',RESCHEDULED:'Rescheduled',COMPLETED:'Completed',CONSULTATION:'Consultation',DIAGNOSIS:'Diagnosis',REFUND:'Refund',CREDIT:'Patient credit',TRANSFER:'Transferred payment',CASH:'Cash',GATEWAY:'Mock gateway'})[String(s).replaceAll(' ','_')]||String(s).replaceAll('_',' ');
  const badge = s => `<span class="badge badge-${['PAID','CONFIRMED','CHECKED IN','COMPLETED','HANDOFF SENT'].includes(s)?'green':['PENDING','PARTIALLY PAID','SCHEDULED','AWAITING NURSE'].includes(s)?'yellow':'gray'}">${e(statusLabel(s))}</span>`;
  const btn = (label,action,id='',style='ghost') => `<button type="button" class="btn btn-${style}" data-action="${action}" data-id="${e(id)}">${e(label)}</button>`;
  const head = (title,actions='') => `<div class="page-header"><h1 class="page-title-lg" tabindex="-1">${e(title)}</h1><div class="header-spacer"></div>${actions}</div>`;
  const table = (headers,rows) => `<div class="rec-table-wrap"><table class="rec-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map((cell,i)=>`<td data-label="${e(headers[i])}"><div>${cell}</div></td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}"><div class="rec-empty">No matching records.</div></td></tr>`}</tbody></table></div>`;
  const identity = v => `<b>${e(full(patient(v.patient)))}</b><br><span class="rec-muted">${e(v.patient)}</span>`;
  const details = pairs => `<div class="rec-summary">${pairs.map(([k,v])=>`<div><strong>${e(k)}</strong>${e(v)}</div>`).join('')}</div>`;
  const select = (id,label,options,value) => `<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><select class="form-control" id="${id}" name="${id}">${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${e(v)}" ${v===value?'selected':''}>${e(l)}</option>`;}).join('')}</select><div class="rec-error" id="${id}-error"></div></div>`;
  const field = (id,label,value='',type='text',placeholder='') => {const completion={first:'given-name',last:'family-name',dob:'bday',phone:'tel',email:'email',address:'street-address',emergencyPhone:'tel'}[id];return `<div class="form-group"><label class="form-label" for="${id}">${e(label)}</label><input class="form-control" id="${id}" name="${id}" type="${type}" value="${e(value)}" placeholder="${e(placeholder)}" ${completion?`autocomplete="${completion}"`:''} ${['phone','emergencyPhone','aadhar'].includes(id)?'inputmode="numeric"':''}><div class="rec-error" id="${id}-error"></div></div>`;};
  const summaryErrors = () => '<div id="form-errors" class="rec-errors" tabindex="-1" role="alert"></div>';
  const matches = (p,q) => `${full(p)} ${p.id} ${p.phone}`.toLowerCase().includes(q.trim().toLowerCase());
  let toastTimer, dialogReturnFocus;
  function clearToast(){clearTimeout(toastTimer);document.querySelector('.rec-toast')?.remove();}
  function toast(text) {clearToast();const el=document.createElement('div');el.className='rec-toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);toastTimer=setTimeout(()=>el.remove(),4500);}
  const dialog = document.createElement('dialog');dialog.className='rec-dialog';document.body.append(dialog);
  function closeDialog(){dialog.close();if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus();}
  function modal(title,body,actions=[]){clearToast();dialogReturnFocus=document.activeElement;dialog.innerHTML=`<div class="rec-dialog-header"><h2 id="dialog-title">${e(title)}</h2><button class="btn btn-ghost" data-close>Close</button></div><div class="rec-dialog-body">${body}</div><div class="rec-dialog-footer">${actions.map((a,i)=>`<button class="btn btn-${a.style||'ghost'}" data-modal="${i}">${e(a.label)}</button>`).join('')}</div>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.querySelector('[data-close]').onclick=closeDialog;dialog.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>{const action=actions[Number(b.dataset.modal)];if(!action.keepOpen)closeDialog();action.run?.();});if(!dialog.open)dialog.showModal();}
  dialog.addEventListener('cancel',()=>{if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus();});
  function guarded(run){if(ui.dirty)modal('Discard unsaved changes?','Your changes have not been saved. Stay to continue editing, or discard them to leave.',[{label:'Keep editing'},{label:'Discard changes',style:'danger',run:()=>{ui.dirty=false;run();}}]);else run();}
  function go(page,id=null){guarded(()=>{if(page==='payments')ui.paymentOrigin={page:ui.page,id:ui.id,scroll:window.scrollY};ui.page=page;ui.id=id;ui.dirty=false;if(page==='book-appointment'){bookingFromDoctors=false;ui.walkin=false;ui.bookingStep=0;ui.booking={patient:id||'',doctor:'priya',date:db.date,time:'',type:'CONSULTATION',channel:'IN_PERSON',reason:'',notes:''};}if(page==='register-patient'){ui.origin={page:'patients'};ui.registration={};}if(page==='payments'){ui.payment={id:id||db.visits.find(v=>live(v)&&v.paid<v.fee)?.id||'',method:'UPI',amount:'',reference:''};}render();});}
  function render(){
    clearToast();
    root.innerHTML=pages[ui.page]();
    if(ui.page==='payments'&&ui.payment?.id){const selected=visit(ui.payment.id);const available=db.credits[selected.patient]||0;if(available>0){root.querySelector('#method')?.insertAdjacentHTML('beforeend',`<option value="CREDIT" ${ui.payment.method==='CREDIT'?'selected':''}>Patient credit (${money(available)} available)</option>`);root.querySelector('#method')?.parentElement.insertAdjacentHTML('afterend',`<p class="rec-muted">Available patient credit: ${money(available)}. Applying credit records a mock payment.</p>`);}}
    if(ui.page==='patient-detail'&&db.credits[ui.id])root.querySelector('.card')?.insertAdjacentHTML('afterend',`<p class="rec-notice">Available patient credit: ${money(db.credits[ui.id])}</p>`);
    if(ui.page==='book-appointment'&&bookingFromDoctors){const notice=document.createElement('p');notice.className='rec-notice';notice.id='selected-doctor-notice';notice.textContent='Booking with '+doctor(ui.booking.doctor).name+' · '+doctor(ui.booking.doctor).specialty+'. Select or register the patient below.';root.querySelector('.page-header').after(notice);}
    const pageTitle=document.getElementById('page-title');pageTitle.textContent=names[ui.page]||ui.page;pageTitle.style.display=ui.page==='dashboard'?'':'none';
    document.querySelectorAll('.nav-item').forEach(n=>{n.classList.toggle('active',n.dataset.screen===ui.page);n.setAttribute('aria-current',n.dataset.screen===ui.page?'page':'false');});
    document.querySelector('.nav-badge').textContent=db.visits.filter(v=>v.date===db.date).length;
    const notificationBadge=document.querySelector('[title="Notifications"] div');
    if(notificationBadge)notificationBadge.textContent=db.visits.filter(v=>live(v)&&v.paid<v.fee).length;
    bindPage();root.querySelector('h1')?.focus({preventScroll:true});window.scrollTo({top:0});
  }
  function eligible(v){return v.paid>=v.fee||Boolean(v.exception?.approved&&(v.exception.expires||v.exception.date)>=db.date);}
  function handoff(v){return v.handoff==='SENT'?'Handoff sent':v.arrived?'Awaiting Nurse':'Not checked in';}
  function arrivalAction(v){if(!live(v))return badge(v.status);if(v.channel==='ONLINE')return '<span class="rec-muted">Online - No check-in</span>';if(v.arrived)return `<span>${badge('CHECKED IN')} ${e(handoff(v))}</span>`;if(v.date!==db.date)return '<span class="rec-muted">Check-in is available on the appointment date.</span>';return !eligible(v)?btn('Collect Payment','payment',v.id,'primary'):btn('Check In','checkin',v.id,'success');}
  function appointmentActions(v){return `<div class="rec-actions">${btn('View','appointment',v.id)}${live(v)?btn('Reschedule','reschedule',v.id)+(v.paid<v.fee?btn('Collect','payment',v.id,'primary'):'')+btn('Cancel','cancel-visit',v.id):''}</div>`;}
  function filteredVisits(){return db.visits.filter(v=>(ui.dateFilter==='All'||(ui.dateFilter==='Today'?v.date===db.date:v.date>=db.date&&v.date<='2026-08-10'))&&(ui.statusFilter==='All Statuses'||v.status===ui.statusFilter));}
  function paymentHistory(v){const records=db.receipts.filter(r=>r.visit===v.id);return `<div class="card"><h2 class="card-title">Payment History</h2>${records.length?table(['Receipt','Method','Amount','Balance','Action'],records.map(r=>[e(r.id),e(statusLabel(r.method)),money(r.amount),money(r.balance),btn('Preview Receipt','receipt-by-id',r.id)])):`<p class="rec-muted">${v.paid?'No itemized mock transactions are available for this seeded appointment.':'No payment has been recorded for this appointment.'}</p>`}${v.resolution?`<p class="rec-notice">${e(statusLabel(v.resolution.type))}: ${money(v.resolution.amount)} · ${e(v.resolution.id)} · ${e(v.resolution.date)}${v.resolution.target?` · ${e(v.resolution.target)}`:''}</p>`:''}</div>`;}
  function visitTimeline(v){return `<div class="card"><h2 class="card-title">Arrival and Nurse Handoff</h2>${details([['Arrival',v.arrivalAt||'Not checked in'],['Token',v.token||'Not issued'],['Nurse handoff',handoff(v)]])}${v.arrived&&v.handoff!=='SENT'?`<div class="rec-actions rec-form-footer">${btn('Send Nurse Handoff','handoff',v.id,'primary')}</div>`:''}</div>`;}
  function queueVisits(){let list=db.visits.filter(v=>v.date===db.date);if(ui.queueDoctor!=='all')list=list.filter(v=>v.doctor===ui.queueDoctor);if(ui.queueStatus==='waiting')list=list.filter(v=>live(v)&&!v.arrived&&v.channel==='IN_PERSON');if(ui.queueStatus==='checked')list=list.filter(v=>v.arrived);if(ui.queueStatus==='pending')list=list.filter(v=>live(v)&&!eligible(v));if(ui.queueStatus==='handoff')list=list.filter(v=>v.arrived&&v.handoff!=='SENT');if(ui.queueOrder==='longest')list.sort((a,b)=>a.time.localeCompare(b.time));return list;}
  function waitlistMatches(){return db.waitlist.filter(w=>w.status==='WAITING'&&appointmentTimes.some(t=>slotAvailable(w.doctor,w.date,t)&&!w.availableAtJoin.includes(t)&&(w.window==='Any time'||(w.window==='Morning'?t<'12:00':t>='12:00'))));}
  function slotAvailable(doctorId,date,time,exceptId=''){return !db.visits.some(v=>v.id!==exceptId&&v.doctor===doctorId&&v.date===date&&v.time===time&&live(v));}
  const pages = {
    doctors(){return head('Doctors')+'<p class="rec-notice">Find a doctor by name or specialty, then book an appointment for your patient.</p><div class="rec-actions">'+field('doctor-search','Search doctors',doctorQuery,'search','Search by doctor name or specialty')+btn('Clear search','clear-doctor-search')+'</div><div id="doctor-results">'+doctorRows()+'</div>';},
    dashboard(){const todays=db.visits.filter(v=>v.date===db.date);const outstanding=todays.filter(v=>live(v)&&!eligible(v));const handoffs=todays.filter(v=>v.arrived&&v.handoff!=='SENT');return `<div class="stat-grid">${[[todays.length,"Today's Appointments",'appointments'],[todays.filter(v=>v.arrived).length,'Checked In','checkin'],[todays.filter(v=>live(v)&&!v.arrived&&v.channel==='IN_PERSON').length,'Waiting','checkin'],[outstanding.length,'Pending Payment','payments']].map(([n,l,a])=>`<button class="stat-card" data-action="nav" data-id="${a}"><div class="stat-value">${n}</div><div class="stat-label">${l}</div></button>`).join('')}</div>${handoffs.length||db.visits.some(v=>v.status==='CANCELED'&&v.paid&&!v.resolution)?`<div class="rec-notice">${handoffs.length} awaiting Nurse handoff · ${db.visits.filter(v=>v.status==='CANCELED'&&v.paid&&!v.resolution).length} billing resolutions needed. ${btn('Open Check-in Queue','nav','checkin')}</div>`:''}<div class="card"><h1 class="card-title" tabindex="-1">Today's Queue</h1>${table(['Time','Patient','Doctor','Type','Status','Payment','Actions'],todays.map(v=>[e(v.time),identity(v),e(doctor(v.doctor).name),v.channel==='ONLINE'?'Online':e(v.reason==='Follow-up'?'Follow-up':'Consultation'),badge(v.arrived?'CHECKED IN':v.status),badge(paymentState(v)),arrivalAction(v)]).concat([['11:00','<b>New Patient</b>','Dr. Amit Joshi','Walk-in','—','—',btn('Book Now','walkin','','ghost')]]))}</div>`;},
    appointments(){const matches=waitlistMatches();return head('All Appointments',`<div class="rec-actions">${select('date-filter','Date',['Today','This Week','All'],ui.dateFilter)}${select('status-filter','Status',['All Statuses','SCHEDULED','CONFIRMED','COMPLETED','CANCELED','NO_SHOW','RESCHEDULED'],ui.statusFilter)}${btn('New Appointment','book','','primary')}</div>`)+table(['Date/Time','Patient','Doctor','Type/Channel','Status','Payment','Actions'],filteredVisits().map(v=>[`${dateText(v.date)}<br>${e(v.time)}`,identity(v),e(doctor(v.doctor).name),e(statusLabel(v.type)+' / '+statusLabel(v.channel)),badge(v.arrived?'CHECKED IN':v.status),badge(paymentState(v)),appointmentActions(v)]))+`<div class="card"><h2 class="card-title">Waitlist</h2>${db.waitlist.length?table(['Patient','Doctor','Preferred date/window','Contact','Status','Action'],db.waitlist.map(w=>[e(full(patient(w.patient)))+' · '+e(w.patient),e(doctor(w.doctor).name),dateText(w.date)+' · '+e(w.window),e(w.contact),e(statusLabel(w.status)),w.status==='WAITING'&&matches.includes(w)?btn('Promote to Booking','promote-waitlist',w.id,'primary'):'—'])):'<p class="rec-muted">No patients are waiting for a slot.</p>'}</div>`;},
    checkin(){return head('Check-in Queue')+'<p class="rec-notice">Confirm arrival for in-person appointments after payment or an approved exception. Online appointments do not require physical check-in.</p><div class="rec-queue-filters">'+select('queue-doctor','Doctor',[['all','All doctors'],...db.doctors.map(d=>[d.id,d.name])],ui.queueDoctor)+select('queue-status','Status',[['all','All statuses'],['waiting','Waiting'],['checked','Checked in'],['pending','Pending payment'],['handoff','Awaiting Nurse']],ui.queueStatus)+select('queue-order','Order',[['time','Appointment time'],['longest','Longest waiting']],ui.queueOrder)+'</div>'+table(['Time','Patient','Doctor','Status','Payment','Nurse handoff','Actions'],queueVisits().map(v=>[e(v.time),identity(v),e(doctor(v.doctor).name),badge(v.arrived?'CHECKED IN':v.status)+(v.channel==='IN_PERSON'&&live(v)&&!v.arrived&&v.time<'09:28'?'<span class="rec-delay">Delayed arrival</span>':''),badge(paymentState(v)),e(handoff(v)),v.arrived?`${btn('View','appointment',v.id)}${v.handoff!=='SENT'?btn('Send Nurse Handoff','handoff',v.id,'primary'):''}`:v.channel==='ONLINE'||!live(v)?arrivalAction(v):`<div class="rec-actions">${!eligible(v)?btn('Collect Payment First','payment',v.id,'primary'):btn('Confirm Check-in','checkin',v.id,'success')}${btn('No Show','no-show',v.id)}</div>`]));},
    patients(){return head('Patient Registry',btn('Register New Patient','register','','primary'))+field('registry-search','Search patients',ui.registryQuery,'search','Search by name, phone, or PAT ID...')+`<div id="registry-results">${registryRows()}</div>`;},
    'patient-detail'(){const p=patient(ui.id);return head(full(p),`<div class="rec-actions">${btn('Back to Patient Registry','nav','patients')}${btn('Edit','edit',p.id)}${btn('Book','book',p.id,'primary')}</div>`)+`<div class="card">${details([['Patient ID',p.id],['Name',full(p)],['Phone',p.phone],['Gender/Age',`${p.gender}, ${age(p)}y`],['Blood Group',p.blood||'Not recorded'],['Date of Birth',dateText(p.dob)],['Email',p.email||'Not recorded'],['Address',p.address||'Not recorded']])}</div><div class="card"><h2 class="card-title">Appointment History</h2>${table(['Date/Time','Doctor','Status','Payment','Actions'],db.visits.filter(v=>v.patient===p.id).map(v=>[dateText(v.date)+' '+e(v.time),e(doctor(v.doctor).name),badge(v.status),badge(paymentState(v)),btn('View','appointment',v.id)]))}</div>`;},
    'appointment-detail'(){const v=visit(ui.id);return head('Appointment Details',btn('Back to Appointments','nav','appointments'))+`<div class="card">${visitSummary(v)}<div class="rec-actions rec-form-footer">${live(v)?btn('Reschedule','reschedule',v.id)+btn('Cancel','cancel-visit',v.id):''}${live(v)&&!eligible(v)?btn('Collect Payment','payment',v.id,'primary'):arrivalAction(v)}${btn('View Bill','bill',v.id)}${btn('Service Note','service-note',v.id)}</div></div>${v.serviceNote?`<div class="rec-notice">Service note: ${e(v.serviceNote)}</div>`:''}${v.status==='CANCELED'&&v.paid&&!v.resolution?`<div class="rec-notice">Payment needs billing resolution. ${btn('Resolve Payment','resolve-payment',v.id,'primary')}</div>`:''}${visitTimeline(v)}${paymentHistory(v)}`;},
    'register-patient'(){const p=ui.registration;return head(p.id?'Edit Patient':'Register New Patient')+`<form id="patient-form" novalidate><div class="card"><h2 class="card-title">Basic Information</h2>${summaryErrors()}<div class="form-row-3">${field('first','First Name *',p.first,'text','First name')}${field('last','Last Name *',p.last,'text','Last name')}${select('gender','Gender *',[['','Select'],'MALE','FEMALE','OTHER'],p.gender||'')}</div><div class="form-row-3">${field('dob','Date of Birth *',p.dob,'date')}${select('blood','Blood Group',[['','Select'],'A+','A-','B+','B-','AB+','AB-','O+','O-'],p.blood||'')}${select('marital','Marital Status',[['','Select'],'Single','Married','Divorced','Widowed'],p.marital||'')}</div><h2 class="card-title rec-form-footer">Contact and administrative details</h2><div class="form-row">${field('phone','Contact Phone *',p.phone,'tel','10-digit mobile')}${field('email','Email',p.email,'email','Optional email')}</div><div class="form-row">${field('aadhar','Aadhar Number',p.aadhar,'text','12-digit Aadhar (optional)')}${field('emergencyPhone','Emergency Contact Phone',p.emergencyPhone,'tel','Emergency contact')}</div>${field('address','Address',p.address,'text','Full address')}<div class="form-row">${select('category','Patient Category',['General','Senior Citizen','Child','Staff','VIP'],p.category||'General')}${field('insurance','Insurance ID',p.insurance,'text','If insured')}</div><div class="rec-actions rec-form-footer"><button class="btn btn-primary" type="submit">Save and Continue</button>${btn('Cancel','registration-cancel')}</div></div></form>`;},
    'book-appointment'(){const b=ui.booking;const steps=['Select Patient','Select Doctor','Pick Date/Slot','Confirm and Pay'];return head(b.id?'Reschedule Appointment':ui.walkin?'Walk-in Check-in':'Book New Appointment')+`<nav class="rec-booking-progress" aria-label="Booking progress">${steps.map((s,i)=>`<button type="button" class="rec-progress-step ${i===ui.bookingStep?'active':i<ui.bookingStep?'done':''}" data-action="booking-step" data-id="${i}" ${i>ui.bookingStep?'disabled':''} aria-current="${i===ui.bookingStep?'step':'false'}">${i+1}. ${s}</button>`).join('')}</nav><form id="booking-form" novalidate>${summaryErrors()}<section class="card rec-booking-stage" id="booking-step-0" ${ui.bookingStep!==0?'hidden':''}><h2 class="card-title">Step 1: Patient Selection</h2><div class="form-row">${field('booking-search','Search Patient (Name or Phone)','','search','Type name, phone number or PAT ID...')}<div><label class="form-label">Or Register New</label>${btn('Register New Patient','register-booking')}</div></div><div id="booking-patients">${bookingPatients('')}</div><div class="rec-error" id="booking-patients-error"></div></section><section class="card rec-booking-stage" id="booking-step-1" ${ui.bookingStep!==1?'hidden':''}><h2 class="card-title">Step 2: Select Doctor</h2><div class="form-row">${select('organization','Organization',[db.clinic],db.clinic)}${select('doctor','Doctor',db.doctors.map(d=>[d.id,`${d.name} (${d.specialty})`]),b.doctor)}</div><div class="form-row">${select('type','Appointment Type',['CONSULTATION','DIAGNOSIS'],b.type)}${select('channel','Channel',['IN_PERSON','ONLINE'],b.channel)}</div>${field('reason','Reason for Visit',b.reason,'text','e.g. Fever, Follow-up')}</section><section class="card rec-booking-stage" id="booking-step-2" ${ui.bookingStep!==2?'hidden':''}><h2 class="card-title">Step 3: Pick Date and Time Slot</h2>${field('date','Date',b.date,'date')}<div class="form-label">Available Slots</div><div id="booking-slots">${slots()}</div><div class="rec-error" id="booking-slots-error"></div><p class="rec-muted">Struck-through = booked · Blue = selected · White = available. Sundays are closed in this mock schedule.</p>${field('notes','Notes',b.notes,'text','Internal notes (not visible to patient)')}</section><section class="card rec-booking-stage" id="booking-step-3" ${ui.bookingStep!==3?'hidden':''}><h2 class="card-title">Step 4: Confirm and Payment</h2><div id="booking-summary">${bookingSummary()}</div><div class="rec-actions rec-form-footer">${b.id?btn('Confirm Reschedule','submit-booking','reschedule','primary'):btn('Proceed to Payment','submit-booking','pay','primary')}${b.id?'':btn('Book Without Payment (Schedule only)','submit-booking','schedule')}</div></section><div class="rec-actions rec-booking-navigation">${ui.bookingStep>0?btn('Back','booking-back'):''}${ui.bookingStep<3?btn('Next','booking-next','','primary'):''}${btn('Cancel','booking-cancel')}</div></form>`;},
    payments(){const pay=ui.payment;const v=visit(pay.id);return head('Payment Collection')+`<form id="payment-form" novalidate><div class="card"><h2 class="card-title">Select Appointment</h2>${summaryErrors()}${select('payment-visit','Patient',[['','Select appointment'],...db.visits.filter(x=>live(x)).map(x=>[x.id,`${full(patient(x.patient))} (${x.patient}) - ${dateText(x.date)} ${x.time} - ${doctor(x.doctor).name}`])],pay.id)}${v?`<div class="form-group"><label class="form-label" for="payment-doctor">Doctor</label><input id="payment-doctor" class="form-control" value="${e(doctor(v.doctor).name)}" readonly></div>`:''}</div>${v?`<div class="card"><h2 class="card-title">Payment for Appointment ${e(v.id)}</h2>${visitSummary(v)}<div class="rec-form-footer">${select('method','Payment Method',[['UPI','UPI (QR Code / VPA)'],['GATEWAY','Razorpay Gateway (Card/UPI/NetBanking)'],['CASH','Cash'],['PENDING','Pay at Center (mark pending)'],['EXCEPTION','Approved payment exception']],pay.method)}</div>${v.paid>=v.fee?`<p class="rec-notice">This appointment is fully paid.</p>${btn('View Bill','bill',v.id)}`:`${!['PENDING','EXCEPTION'].includes(pay.method)?field('amount','Amount (INR)',pay.amount===''?v.fee-v.paid:pay.amount,'number'):''}${['UPI','GATEWAY'].includes(pay.method)?field('reference','Reference / UTR',pay.reference,'text','Transaction reference (for UPI/Card)'):''}${pay.method==='EXCEPTION'?`${field('exceptionReason','Exception Reason *',pay.exceptionReason||'','text','Why may this visit proceed?')}${field('exceptionApprover','Approved By *',pay.exceptionApprover||'','text','Approving staff member or role')}<p class="rec-muted">The remaining balance ${money(v.fee-v.paid)} and approval date are recorded automatically. Mock approval only.</p>`:''}${pay.method==='UPI'?'<div class="rec-notice"><b>UPI Payment Details</b><br>VPA: cityhealthclinic@upi<br>Payee Name: City Health Clinic<br>Mock payment only — no money is transferred.</div>':pay.method==='GATEWAY'?'<p class="rec-notice">Mock gateway payment. Confirming records a simulated payment; no checkout is opened.</p>':''}<div class="rec-actions rec-form-footer"><button class="btn btn-success" type="submit">${pay.method==='PENDING'?'Save as Pending':pay.method==='EXCEPTION'?'Approve Exception':'Confirm Payment Received'}</button>${btn('Cancel','payment-cancel')}</div>`}</div>`:'<div class="rec-empty">Select an appointment to view payment details.</div>'}</form>${v?paymentHistory(v):''}`;},
    'payment-success'(){const r=ui.receipt;return `<div class="card rec-receipt">${head('Payment Successful')}<p class="rec-muted">Mock payment recorded</p>${receiptBody(r)}<h2 class="card-title rec-form-footer">Share Receipt</h2><div class="rec-actions">${btn('WhatsApp','share','WhatsApp')}${btn('SMS','share','SMS')}${btn('Preview Receipt','receipt-preview')}</div><div class="rec-actions rec-form-footer">${btn('Go to Check-in','nav','checkin','primary')}${btn('Done','nav','dashboard')}</div></div>`;},
    'checkin-success'(){const v=visit(ui.id);return `<div class="card rec-receipt">${head('Check-in Successful')}<p class="rec-notice">${e(full(patient(v.patient)))} is checked in. Token ${e(v.token)}. Nurse handoff: ${e(handoff(v))}.</p>${visitSummary(v)}${details([['Arrival',v.arrivalAt||'Not recorded'],['Nurse handoff',handoff(v)]])}<div class="rec-actions rec-form-footer">${v.handoff!=='SENT'?btn('Send Nurse Handoff','handoff',v.id,'primary'):''}${btn('Back to Queue','nav','checkin','primary')}${btn('Dashboard','nav','dashboard')}</div></div>`;}
  };
  function visitSummary(v){return details([['Patient',`${full(patient(v.patient))} (${v.patient})`],['Appointment',v.id],['Doctor',doctor(v.doctor).name],['Date/Time',`${dateText(v.date)}, ${v.time}`],['Type/Channel',`${statusLabel(v.type)} / ${statusLabel(v.channel)}`],['Arrival type',v.walkin?'Walk-in':'Scheduled'],['Status',v.arrived?'Checked in':statusLabel(v.status)],['Fee',money(v.fee)],['Paid / Balance',`${money(v.paid)} / ${money(Math.max(0,v.fee-v.paid))}`],['Payment exception',v.exception?.approved?`${v.exception.approver} · ${v.exception.reason}`:'None'],...(v.resolution?[['Payment resolution',`${statusLabel(v.resolution.type)} · ${money(v.resolution.amount)} · ${v.resolution.id}${v.resolution.target?` · ${v.resolution.target}`:''}`]]:[])]);}
  function nextDoctorSlot(id){for(let offset=0;offset<7;offset++){const date=new Date(db.date+'T12:00:00');date.setDate(date.getDate()+offset);if(date.getDay()===0)continue;const day=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');const time=appointmentTimes.find(t=>!db.visits.some(v=>v.doctor===id&&v.date===day&&v.time===t&&live(v)));if(time)return dateText(day)+', '+time;}return 'No slots in the next 7 days';}
  function doctorRows(){const list=db.doctors.filter(d=>(d.name+' '+d.specialty).toLowerCase().includes(doctorQuery.trim().toLowerCase()));return `<p class="rec-muted" role="status">${list.length} doctor${list.length===1?'':'s'} found · Availability follows the mock schedule.</p>`+(list.length?table(['Doctor','Specialty','Consultation fee','Next available slot','Actions'],list.map(d=>[`<b>${e(d.name)}</b>`,e(d.specialty),money(d.fee),nextDoctorSlot(d.id),btn('Book Appointment','book-doctor',d.id,'primary')])):'<p class="rec-notice">No doctors match your search. Try another name or specialty, or clear your search.</p>');}
  function registryRows(){return table(['ID','Name','Phone','Gender/Age','Blood Group','Last Visit','Actions'],db.patients.filter(p=>matches(p,ui.registryQuery)).map(p=>[e(p.id),`<b>${e(full(p))}</b>`,e(p.phone),`${e(p.gender)}, ${age(p)}y`,e(p.blood||'Not recorded'),dateText(p.lastVisit),`<div class="rec-actions">${btn('View','patient',p.id)}${btn('Edit','edit',p.id)}${btn('Book','book',p.id)}</div>`]));}
  function bookingPatients(q){const picked=patient(ui.booking.patient);const query=q.trim();const list=query?db.patients.filter(p=>matches(p,query)):picked?[picked]:db.patients.slice(0,3);return `<p class="rec-muted">${query?'Matching patients':'Recent patients — search to find others'}</p>`+table(['Select','Name','Phone','Gender/Age','ID'],list.map(p=>[`<label class="rec-patient-choice"><input type="radio" name="selected-patient" value="${e(p.id)}" aria-label="Select ${e(full(p))} ${e(p.id)}" ${ui.booking.patient===p.id?'checked':''}></label>`,e(full(p)),ui.booking.patient===p.id?e(p.phone):`••••••${e(p.phone.slice(-4))}`,`${p.gender}, ${age(p)}y`,e(p.id)]));}
  function slots(){const b=ui.booking;const closed=!b.date||new Date(b.date+'T12:00:00').getDay()===0||b.date<db.date;if(closed)return '<p class="rec-notice">No available slots. Choose another date.</p>';const available=appointmentTimes.filter(t=>slotAvailable(b.doctor,b.date,t,b.id));const group=(name,times)=>`<div class="rec-slot-group"><h3>${name}</h3><div class="rec-actions">${times.map(t=>`<button type="button" class="rec-slot" data-slot="${t}" aria-pressed="${b.time===t}" ${!slotAvailable(b.doctor,b.date,t,b.id)?'disabled':''}>${t}</button>`).join('')}</div></div>`;return `${available.length?`<p class="rec-muted">Next available: ${e(available[0])} ${btn('Select next available','next-slot')}</p>`:`<p class="rec-notice">No open slots for this doctor and date. ${b.patient?btn('Join Waitlist','waitlist',b.patient,'primary'):'Select a patient to join the waitlist.'}</p>`}${group('Morning',appointmentTimes.filter(t=>t<'12:00'))}${group('Afternoon',appointmentTimes.filter(t=>t>='12:00'))}`;}
  function bookingSummary(){const b=ui.booking;return details([['Patient',b.patient?`${full(patient(b.patient))} (${b.patient})`:'Select patient'],['Doctor',doctor(b.doctor).name],['Date/Time',`${dateText(b.date)}, ${b.time||'Select slot'}`],['Type',statusLabel(b.type)+' / '+statusLabel(b.channel)],['Fee',money(b.id?visit(b.id).fee:doctor(b.doctor).fee)],['Org',db.clinic]]);}
  function receiptBody(r){const v=visit(r.visit);return `<h2 class="card-title rec-form-footer">${e(db.clinic)}</h2><p class="rec-muted">123, MG Road, Bangalore 560001</p><p class="rec-muted">Receipt #${e(r.id)}</p><div class="rec-form-footer">${details([['Patient',`${full(patient(v.patient))} (${v.patient})`],['Doctor',doctor(v.doctor).name],['Date/Time',dateText(v.date)+', '+v.time],['Method',statusLabel(r.method)],['Reference',r.reference||'Not applicable'],['Recorded',dateText(db.date)],['Appointment',v.id],['Balance after payment',money(r.balance)]])}</div><div class="rec-receipt-total">Total Paid ${money(r.amount)}</div>`;}
  function formErrors(errors){root.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));root.querySelectorAll('.rec-error').forEach(el=>el.textContent='');const box=root.querySelector('#form-errors');box.innerHTML=Object.entries(errors).map(([id,msg])=>`<a href="#${id}">${e(msg)}</a>`).join('');for(const [id,msg] of Object.entries(errors)){const el=document.getElementById(id);el?.setAttribute('aria-invalid','true');el?.setAttribute('aria-describedby',id+'-error');const error=document.getElementById(id+'-error');if(error)error.textContent=msg;}if(Object.keys(errors).length){box.focus();box.scrollIntoView({block:'center'});return true;}return false;}
  function bindPage(){
    root.querySelector('#doctor-search')?.addEventListener('input',event=>{doctorQuery=event.target.value;root.querySelector('#doctor-results').innerHTML=doctorRows();});
    root.querySelector('#registry-search')?.addEventListener('input',event=>{ui.registryQuery=event.target.value;root.querySelector('#registry-results').innerHTML=registryRows();});
    for(const id of ['date-filter','status-filter'])root.querySelector('#'+id)?.addEventListener('change',event=>{ui[id==='date-filter'?'dateFilter':'statusFilter']=event.target.value;render();});
    for(const [id,key] of [['queue-doctor','queueDoctor'],['queue-status','queueStatus'],['queue-order','queueOrder']])root.querySelector('#'+id)?.addEventListener('change',event=>{ui[key]=event.target.value;render();});
    root.querySelector('#patient-form')?.addEventListener('input',event=>{ui.registration[event.target.name]=event.target.value;ui.dirty=true;});
    root.querySelector('#patient-form')?.addEventListener('change',event=>{ui.registration[event.target.name]=event.target.value;ui.dirty=true;});
    root.querySelector('#patient-form')?.addEventListener('submit',event=>{event.preventDefault();savePatient();});
    root.querySelector('#booking-search')?.addEventListener('input',event=>{root.querySelector('#booking-patients').innerHTML=bookingPatients(event.target.value);});
    root.querySelector('#booking-form')?.addEventListener('change',event=>{const t=event.target;if(t.name==='selected-patient'){ui.booking.patient=t.value;root.querySelector('#booking-patients').innerHTML=bookingPatients(root.querySelector('#booking-search')?.value||'');}else if(['doctor','date','type','channel','organization'].includes(t.name)){if(t.name!=='organization')ui.booking[t.name]=t.value;if(t.name==='doctor'&&root.querySelector('#selected-doctor-notice'))root.querySelector('#selected-doctor-notice').textContent='Booking with '+doctor(t.value).name+' · '+doctor(t.value).specialty+'. Select or register the patient below.';if(['doctor','date'].includes(t.name)){ui.booking.time='';root.querySelector('#booking-slots').innerHTML=slots();}}else return;ui.dirty=true;root.querySelector('#booking-summary').innerHTML=bookingSummary();});
    root.querySelector('#booking-form')?.addEventListener('input',event=>{if(['reason','notes'].includes(event.target.name)){ui.booking[event.target.name]=event.target.value;ui.dirty=true;}});
    root.querySelector('#booking-form')?.addEventListener('submit',event=>event.preventDefault());
    root.querySelector('#payment-visit')?.addEventListener('change',event=>{const id=event.target.value;guarded(()=>{ui.dirty=false;ui.payment={id,method:'UPI',amount:'',reference:''};render();});if(ui.dirty)event.target.value=ui.payment.id;});
    root.querySelector('#method')?.addEventListener('change',event=>{ui.payment.method=event.target.value;ui.payment.reference='';ui.dirty=true;render();});
    root.querySelector('#payment-form')?.addEventListener('input',event=>{if(['amount','reference','exceptionReason','exceptionApprover'].includes(event.target.name)){ui.payment[event.target.name]=event.target.value;ui.dirty=true;}});
    root.querySelector('#payment-form')?.addEventListener('submit',event=>{event.preventDefault();if(ui.payment?.method==='CREDIT')saveCreditPayment();else savePayment();});
  }
  function savePatient(allowDuplicate=false){const p=ui.registration;const errors={};for(const [id,label] of [['first','First name'],['last','Last name'],['gender','Gender'],['dob','Date of birth'],['phone','Contact phone']])if(!p[id]?.trim())errors[id]=`${label} is required.`;if(p.phone&&!/^\d{10}$/.test(p.phone))errors.phone='Enter a 10-digit contact phone.';if(p.dob&&p.dob>db.date)errors.dob='Date of birth cannot be after the scenario date.';if(p.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))errors.email='Enter a valid email or leave it empty.';if(p.aadhar&&!/^\d{12}$/.test(p.aadhar))errors.aadhar='Enter 12 digits or leave this optional field empty.';if(p.emergencyPhone&&!/^\d{10}$/.test(p.emergencyPhone))errors.emergencyPhone='Enter 10 digits or leave this optional field empty.';if(formErrors(errors))return;const duplicate=db.patients.find(x=>x.id!==p.id&&(x.phone===p.phone||(full(x).toLowerCase()===full(p).toLowerCase()&&x.dob===p.dob)));if(duplicate&&!allowDuplicate){modal('Possible duplicate patient',`${e(full(duplicate))} (${e(duplicate.id)}) has matching details. A shared phone can belong to different family members. Confirm this is a distinct patient before creating another record.`,[{label:'Inspect existing patient',run:()=>modal('Existing patient',details([['Name',full(duplicate)],['ID',duplicate.id],['Phone',duplicate.phone],['Date of Birth',dateText(duplicate.dob)]]),[{label:'Back to registration'},{label:'Use existing patient',style:'primary',run:()=>finishPatient(duplicate,false)}])},{label:'Continue as distinct patient',style:'primary',run:()=>savePatient(true)},{label:'Keep editing'}]);return;}const isNew=!p.id;const saved={...p,first:p.first.trim(),last:p.last.trim(),id:p.id||`PAT-${db.nextPatient++}`};if(isNew)db.patients.push(saved);else Object.assign(patient(p.id),saved);finishPatient(saved,true);}
  function finishPatient(p,saved){ui.dirty=false;const origin=ui.origin;if(origin?.page==='book-appointment'){ui.booking=origin.booking;ui.booking.patient=p.id;ui.page='book-appointment';ui.dirty=true;}else{ui.page='patient-detail';ui.id=p.id;}render();toast(saved?`Patient saved: ${full(p)} (${p.id}).`:`Selected ${full(p)} (${p.id}).`);}
  function submitBooking(mode){if(ui.page!=='book-appointment'||!ui.booking)return;const b=ui.booking;const errors={};if(!b.patient)errors['booking-patients']='Select a patient.';if(!b.date||b.date<db.date)errors.date='Choose an available date on or after the scenario date.';if(!b.time)errors['booking-slots']='Select an available time slot.';if(b.time&&!slotAvailable(b.doctor,b.date,b.time,b.id))errors['booking-slots']='This slot is booked. Choose another slot.';if(Object.keys(errors).length){ui.bookingStep=errors['booking-patients']?0:2;render();formErrors(errors);return;}const save=()=>{if(ui.page!=='book-appointment'||ui.booking!==b)return;let v;if(b.id){v=visit(b.id);Object.assign(v,b,{status:'RESCHEDULED',arrived:false,handoff:null,arrivalAt:null,token:null});}else{v={...b,id:`APT-${db.nextVisit++}`,status:'SCHEDULED',arrived:false,fee:doctor(b.doctor).fee,paid:0};db.visits.push(v);}if(b.waitlistId){const w=db.waitlist.find(x=>x.id===b.waitlistId);if(w){w.status='PROMOTED';w.appointment=v.id;}}ui.dirty=false;ui.booking=null;if(mode==='pay'){ui.paymentOrigin={page:'appointment-detail',id:v.id};ui.page='payments';ui.payment={id:v.id,method:'UPI',amount:'',reference:''};}else{ui.page='appointment-detail';ui.id=v.id;}render();toast(mode==='reschedule'?'Appointment rescheduled.':'Appointment booked.');};if(b.id)modal('Confirm Reschedule',bookingSummary(),[{label:'Keep editing'},{label:'Confirm Reschedule',style:'primary',run:save}]);else save();}
  function savePayment(){if(ui.page!=='payments'||!ui.payment)return;const pay=ui.payment,v=visit(pay.id);if(!v||v.paid>=v.fee)return;if(pay.method==='PENDING'){ui.dirty=false;go('appointment-detail',v.id);toast(v.paid?'Remaining balance stays pending.':'Payment stays pending.');return;}if(pay.method==='EXCEPTION'){const errors={};if(!pay.exceptionReason?.trim())errors.exceptionReason='Enter the reason for this exception.';if(!pay.exceptionApprover?.trim())errors.exceptionApprover='Enter the approving staff member or role.';if(formErrors(errors))return;v.exception={approved:true,reason:pay.exceptionReason.trim(),approver:pay.exceptionApprover.trim(),amount:v.fee-v.paid,date:db.date,actor:'Receptionist'};db.audit.push({visit:v.id,action:'PAYMENT_EXCEPTION_APPROVED',...v.exception});ui.dirty=false;ui.page='appointment-detail';ui.id=v.id;render();toast('Payment exception recorded. Balance remains due.');return;}const amount=Number(pay.amount===''?v.fee-v.paid:pay.amount);const errors={};if(!Number.isFinite(amount)||amount<=0||amount>v.fee-v.paid||Math.round(amount*100)!==amount*100)errors.amount='Enter an amount above zero, up to the balance, with at most two decimals.';if(['UPI','GATEWAY'].includes(pay.method)&&!pay.reference.trim())errors.reference='Enter the mock transaction reference.';if(formErrors(errors))return;v.paid=Math.round((v.paid+amount)*100)/100;const r={id:`INV-2026-${db.nextReceipt++}`,visit:v.id,amount,balance:v.fee-v.paid,method:pay.method,reference:pay.reference,date:db.date};db.receipts.push(r);if(v.paid>=v.fee)v.exception=null;ui.receipt=r;ui.dirty=false;ui.page='payment-success';render();}
  function saveCreditPayment(){const pay=ui.payment,v=visit(pay.id),available=db.credits[v?.patient]||0;if(!v||!available)return;const amount=Number(pay.amount===''?Math.min(available,v.fee-v.paid):pay.amount);if(!Number.isFinite(amount)||amount<=0||amount>available||amount>v.fee-v.paid||Math.round(amount*100)!==amount*100){formErrors({amount:`Enter an amount above zero, up to ${money(Math.min(available,v.fee-v.paid))}.`});return;}db.credits[v.patient]=Math.round((available-amount)*100)/100;v.paid=Math.round((v.paid+amount)*100)/100;const r={id:`INV-2026-${db.nextReceipt++}`,visit:v.id,amount,balance:v.fee-v.paid,method:'CREDIT',reference:'Patient credit',date:db.date};db.receipts.push(r);if(v.paid>=v.fee)v.exception=null;ui.receipt=r;ui.dirty=false;ui.page='payment-success';render();}
  function confirmStatus(id,status){const v=visit(id);modal(status==='CANCELED'?'Cancel Appointment':'Mark No Show',`${e(full(patient(v.patient)))} (${e(v.patient)}) · ${dateText(v.date)} ${e(v.time)} · ${e(doctor(v.doctor).name)}. ${status==='CANCELED'&&v.paid?'A billing-resolution work item will remain until the payment is resolved.':''}`,[{label:'Keep appointment'},{label:status==='CANCELED'?'Cancel Appointment':'Mark No Show',style:'danger',run:()=>{v.status=status;v.arrived=false;v.handoff=null;render();toast(status==='CANCELED'?'Appointment cancelled.':'Appointment marked no-show.');}}]);}
  function resolvePayment(id){const v=visit(id);if(!v||v.status!=='CANCELED'||!v.paid||v.resolution)return;const candidates=db.visits.filter(x=>x.id!==id&&x.patient===v.patient&&live(x)&&x.fee-x.paid>=v.paid);modal('Resolve Canceled Payment',`<p>${e(full(patient(v.patient)))} · ${e(v.id)} · ${money(v.paid)} retained. Choose how the mock amount is handled.</p>${candidates.length?`<label class="form-label" for="resolution-target">Transfer to appointment</label><select class="form-control" id="resolution-target">${candidates.map(x=>`<option value="${e(x.id)}">${e(x.id)} · ${dateText(x.date)} ${e(x.time)}</option>`).join('')}</select>`:''}`,[{label:'Keep unresolved'},{label:'Mock Refund',run:()=>finishResolution(v,'REFUND')},{label:'Patient Credit',run:()=>finishResolution(v,'CREDIT')},...(candidates.length?[{label:'Transfer Payment',style:'primary',run:()=>finishResolution(v,'TRANSFER',dialog.querySelector('#resolution-target')?.value)}]:[])]);}
  function finishResolution(v,type,targetId=''){const amount=v.paid;if(type==='TRANSFER'){const target=visit(targetId);if(!target||target.patient!==v.patient||target.fee-target.paid<amount){toast('Choose an eligible appointment for transfer.');return;}target.paid=Math.round((target.paid+amount)*100)/100;target.transferFrom=v.id;db.receipts.push({id:`INV-2026-${db.nextReceipt++}`,visit:target.id,amount,balance:target.fee-target.paid,method:'TRANSFER',reference:v.id,date:db.date});}if(type==='CREDIT')db.credits[v.patient]=Math.round(((db.credits[v.patient]||0)+amount)*100)/100;v.resolution={id:`RES-2026-${db.nextResolution++}`,type,amount,date:db.date,target:targetId};v.refunded=type==='REFUND';db.audit.push({visit:v.id,action:'PAYMENT_RESOLUTION',...v.resolution});render();toast('Payment resolution recorded (mock).');}
  function openWaitlist(id){const b=ui.booking;if(!b?.patient||b.patient!==id)return toast('Select a patient before joining the waitlist.');modal('Join Doctor Waitlist',`<p>${e(full(patient(id)))} · ${e(doctor(b.doctor).name)} · ${dateText(b.date)}</p><div class="form-group"><label class="form-label" for="wait-window">Preferred window</label><select id="wait-window" class="form-control"><option>Any time</option><option>Morning</option><option>Afternoon</option></select></div><div class="form-group"><label class="form-label" for="wait-contact">Contact preference</label><select id="wait-contact" class="form-control"><option>Phone</option><option>SMS</option></select></div><p class="rec-error" id="wait-error"></p>`,[{label:'Keep booking'},{label:'Add to Waitlist',style:'primary',run:()=>{const existing=db.waitlist.find(w=>w.status==='WAITING'&&w.patient===id&&w.doctor===b.doctor&&w.date===b.date);if(existing){toast('This patient is already on the waitlist.');return;}db.waitlist.push({id:`WAIT-${String(db.nextWaitlist++).padStart(3,'0')}`,patient:id,doctor:b.doctor,date:b.date,window:dialog.querySelector('#wait-window')?.value||'Any time',contact:dialog.querySelector('#wait-contact')?.value||'Phone',availableAtJoin:appointmentTimes.filter(t=>slotAvailable(b.doctor,b.date,t)),status:'WAITING'});ui.dirty=false;ui.page='appointments';render();toast('Patient added to the waitlist.');}}]);}
  function promoteWaitlist(id){const w=db.waitlist.find(x=>x.id===id&&x.status==='WAITING');if(!w)return;const slots=appointmentTimes.filter(t=>slotAvailable(w.doctor,w.date,t)&&!w.availableAtJoin.includes(t)&& (w.window==='Any time'||(w.window==='Morning'?t<'12:00':t>='12:00')));if(!slots.length)return toast('No newly released matching slot remains available.');ui.booking={patient:w.patient,doctor:w.doctor,date:w.date,time:slots[0],type:'CONSULTATION',channel:'IN_PERSON',reason:'',notes:'',waitlistId:w.id};ui.bookingStep=3;ui.walkin=false;ui.page='book-appointment';ui.dirty=false;render();}
  function editServiceNote(id){const v=visit(id);if(!v)return;modal('Service Note',`<p>Optional operational assistance or contact preference for ${e(full(patient(v.patient)))} · ${e(v.id)}. Do not enter clinical notes.</p><label class="form-label" for="service-note-input">Service note</label><textarea id="service-note-input" class="form-control" rows="4" maxlength="240">${e(v.serviceNote||'')}</textarea>`,[{label:'Cancel'},{label:'Remove Note',run:()=>{v.serviceNote='';render();toast('Service note removed.');}},{label:'Save Note',style:'primary',run:()=>{v.serviceNote=dialog.querySelector('#service-note-input')?.value.trim()||'';render();toast('Service note saved.');}}]);}
  function actions(action,id){
    if(action==='clear-doctor-search'){doctorQuery='';root.querySelector('#doctor-search').value='';root.querySelector('#doctor-results').innerHTML=doctorRows();root.querySelector('#doctor-search').focus();return;}
    if(action==='book-doctor')return guarded(()=>{bookingFromDoctors=true;ui.walkin=false;ui.bookingStep=0;ui.booking={patient:'',doctor:id,date:db.date,time:'',type:'CONSULTATION',channel:'IN_PERSON',reason:'',notes:''};ui.page='book-appointment';ui.dirty=false;render();});
    if(action==='nav')return go(id);
    if(action==='patient')return go('patient-detail',id);
    if(action==='appointment')return go('appointment-detail',id);
    if(action==='book')return go('book-appointment',id);
    if(action==='payment')return go('payments',id);
    if(action==='register')return go('register-patient');
    if(action==='edit')return guarded(()=>{ui.registration={...patient(id)};ui.origin={page:'patient-detail',id};ui.page='register-patient';render();});
    if(action==='register-booking'){ui.origin={page:'book-appointment',booking:{...ui.booking}};ui.registration={};ui.page='register-patient';ui.dirty=false;return render();}
    if(action==='registration-cancel')return guarded(()=>{ui.dirty=false;if(ui.origin?.page==='book-appointment'){ui.booking=ui.origin.booking;ui.page='book-appointment';ui.dirty=true;render();}else go(ui.origin?.page||'patients',ui.origin?.id);});
    if(action==='booking-cancel')return go(bookingFromDoctors?'doctors':'appointments');
    if(action==='payment-cancel')return guarded(()=>{const origin=ui.paymentOrigin||{page:'dashboard'};ui.dirty=false;ui.page=origin.page;ui.id=origin.id||null;render();if(origin.scroll)window.scrollTo({top:origin.scroll});});
    if(action==='walkin')return guarded(()=>{ui.walkin=true;ui.bookingStep=0;ui.booking={patient:'',doctor:'amit',date:db.date,time:'',type:'CONSULTATION',channel:'IN_PERSON',reason:'',notes:'',walkin:true};ui.page='book-appointment';ui.dirty=false;render();});
    if(action==='booking-step'){const target=Number(id);if(target<=ui.bookingStep){ui.bookingStep=target;render();}return;}
    if(action==='booking-back'){ui.bookingStep=Math.max(0,ui.bookingStep-1);render();return;}
    if(action==='booking-next'){if(ui.bookingStep===0&&!ui.booking.patient){formErrors({'booking-patients':'Select a patient.'});return;}if(ui.bookingStep===2&&!ui.booking.time){formErrors({'booking-slots':'Select an available time slot.'});return;}ui.bookingStep=Math.min(3,ui.bookingStep+1);render();return;}
    if(action==='next-slot'){const b=ui.booking;const time=appointmentTimes.find(t=>slotAvailable(b.doctor,b.date,t,b.id));if(time){b.time=time;ui.dirty=true;root.querySelector('#booking-slots').innerHTML=slots();root.querySelector('#booking-summary').innerHTML=bookingSummary();}return;}
    if(action==='waitlist')return openWaitlist(id);
    if(action==='promote-waitlist')return promoteWaitlist(id);
    if(action==='submit-booking')return submitBooking(id);
    if(action==='reschedule')return guarded(()=>{bookingFromDoctors=false;ui.walkin=false;ui.bookingStep=0;ui.booking={...visit(id)};ui.page='book-appointment';ui.dirty=false;render();});
    if(action==='cancel-visit')return confirmStatus(id,'CANCELED');
    if(action==='no-show')return confirmStatus(id,'NO_SHOW');
    if(action==='checkin'){const v=visit(id);if(!eligible(v))return toast('Collect payment or record an approved exception before check-in.');return modal('Confirm Check-in',visitSummary(v),[{label:'Cancel'},{label:'Confirm Check-in',style:'success',run:()=>{v.arrived=true;v.status='CONFIRMED';v.token=`T-${String(db.visits.filter(x=>x.arrived).length).padStart(2,'0')}`;v.arrivalAt=`${dateText(db.date)}, 09:28`;v.handoff='AWAITING';ui.page='checkin-success';ui.id=v.id;render();}}]);}
    if(action==='handoff'){const v=visit(id);if(!v?.arrived||v.handoff==='SENT')return;v.handoff='SENT';v.handoffAt=`${dateText(db.date)}, 09:28`;db.audit.push({visit:v.id,action:'NURSE_HANDOFF_SENT',at:v.handoffAt});render();toast('Nurse handoff sent (mock).');return;}
    if(action==='resolve-payment')return resolvePayment(id);
    if(action==='receipt-by-id'){const receipt=db.receipts.find(r=>r.id===id);if(receipt)return modal('Receipt Preview',receiptBody(receipt),[{label:'Print Receipt',keepOpen:true,run:()=>window.print()},{label:'Close preview'}]);return;}
    if(action==='service-note')return editServiceNote(id);
    if(action==='bill'){const v=visit(id);return modal('Bill Preview',`<h3>${e(db.clinic)}</h3><p>Bill ${e(v.id.replace('APT','BILL'))}</p>${visitSummary(v)}<p class="rec-muted">Mock bill preview</p>`,[{label:'Close preview'}]);}
    if(action==='receipt-preview')return modal('Receipt Preview',receiptBody(ui.receipt),[{label:'Print Receipt',keepOpen:true,run:()=>window.print()},{label:'Close preview'}]);
    if(action==='share')return modal('Share Receipt',`Mock ${e(id)} receipt for ${e(full(patient(visit(ui.receipt.visit).patient)))} will be shown as shared. No message will be sent.`,[{label:'Cancel'},{label:'Simulate sharing',style:'primary',run:()=>toast(`Receipt shared via ${id} (mock).`)}]);
  }
  root.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(b){event.preventDefault();actions(b.dataset.action,b.dataset.id);}const slot=event.target.closest('[data-slot]');if(slot&&!slot.disabled){ui.booking.time=slot.dataset.slot;ui.dirty=true;root.querySelector('#booking-slots').innerHTML=slots();root.querySelector('#booking-summary').innerHTML=bookingSummary();}});
  document.querySelectorAll('.nav-item').forEach(n=>{n.setAttribute('role','button');n.tabIndex=0;n.addEventListener('click',()=>go(n.dataset.screen));n.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();go(n.dataset.screen);}});});
  const toggle=document.querySelector('[title="Toggle sidebar"]');toggle.setAttribute('role','button');toggle.tabIndex=0;toggle.setAttribute('aria-label','Toggle sidebar');toggle.onclick=()=>{const collapsed=document.querySelector('.app').classList.toggle('collapsed');toggle.setAttribute('aria-expanded',String(!collapsed));};toggle.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();toggle.click();}};
  const notifications=document.querySelector('[title="Notifications"]');notifications.setAttribute('role','button');notifications.tabIndex=0;notifications.setAttribute('aria-label','Notifications');notifications.onclick=()=>modal('Notifications',db.visits.filter(v=>live(v)&&v.paid<v.fee).map(v=>`<p>${e(full(patient(v.patient)))} · ${e(v.id)} · payment pending</p>`).join('')||'<p>No pending payment notifications.</p>',[{label:'View Payments',style:'primary',run:()=>go('payments')},{label:'Close'}]);notifications.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();notifications.click();}};
  const search=document.querySelector('.topbar input');search.setAttribute('aria-label','Search patients, appointments');search.parentElement.classList.add('topbar-search');const results=document.createElement('div');results.className='search-results';results.hidden=true;search.parentElement.append(results);
  search.addEventListener('input',()=>{const q=search.value.trim();results.hidden=!q;if(!q)return;const patients=db.patients.filter(p=>matches(p,q));const visits=db.visits.filter(v=>`${v.id} ${full(patient(v.patient))}`.toLowerCase().includes(q.toLowerCase()));results.innerHTML=patients.map(p=>`<button data-search-patient="${p.id}">${e(full(p))} · ${p.id}</button>`).join('')+visits.map(v=>`<button data-search-visit="${v.id}">${v.id} · ${e(full(patient(v.patient)))} · ${dateText(v.date)}</button>`).join('')+(!patients.length&&!visits.length?'<p>No matching patients or appointments.</p>':'')+'<button data-search-close>Close results</button>';});
  results.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;results.hidden=true;search.value='';if(b.dataset.searchPatient)go('patient-detail',b.dataset.searchPatient);if(b.dataset.searchVisit)go('appointment-detail',b.dataset.searchVisit);});search.addEventListener('keydown',event=>{if(event.key==='Escape')results.hidden=true;});
  document.querySelector('.switch-role').addEventListener('click',event=>{if(ui.dirty){event.preventDefault();guarded(()=>location.href='index.html');}});
  window.addEventListener('beforeunload',event=>{if(ui.dirty){event.preventDefault();event.returnValue='';}});
  const note=document.createElement('p');note.className='rec-scenario';note.textContent='Mock scenario: 04 Aug 2026. Changes reset when this page reloads.';document.querySelector('main').append(note);
  render();
})();
